// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fdb_compose_folded_cpp
NumericMatrix fdb_compose_folded_cpp(int Nc, int n_out, List shapes, List Glist, List Hlist);
RcppExport SEXP _dynhr_fdb_compose_folded_cpp(SEXP NcSEXP, SEXP n_outSEXP, SEXP shapesSEXP, SEXP GlistSEXP, SEXP HlistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< List >::type shapes(shapesSEXP);
    Rcpp::traits::input_parameter< List >::type Glist(GlistSEXP);
    Rcpp::traits::input_parameter< List >::type Hlist(HlistSEXP);
    rcpp_result_gen = Rcpp::wrap(fdb_compose_folded_cpp(Nc, n_out, shapes, Glist, Hlist));
    return rcpp_result_gen;
END_RCPP
}
// hank_ar_slab_adjoint_psi_cpp
Rcpp::NumericMatrix hank_ar_slab_adjoint_psi_cpp(const Rcpp::NumericMatrix& Bvec, const Rcpp::NumericMatrix& Psi);
RcppExport SEXP _dynhr_hank_ar_slab_adjoint_psi_cpp(SEXP BvecSEXP, SEXP PsiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Bvec(BvecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Psi(PsiSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_ar_slab_adjoint_psi_cpp(Bvec, Psi));
    return rcpp_result_gen;
END_RCPP
}
// hank_ar_score_weights_cpp
Rcpp::NumericVector hank_ar_score_weights_cpp(const Rcpp::IntegerMatrix& Sidx, const Rcpp::NumericMatrix& Sinv, const Rcpp::NumericVector& v, int n_g);
RcppExport SEXP _dynhr_hank_ar_score_weights_cpp(SEXP SidxSEXP, SEXP SinvSEXP, SEXP vSEXP, SEXP n_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type Sidx(SidxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Sinv(SinvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n_g(n_gSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_ar_score_weights_cpp(Sidx, Sinv, v, n_g));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm_step_cpp
List hank_egm_step_cpp(NumericMatrix Va_p_, NumericVector a_grid_, NumericVector y_, double r, double beta, double eis, NumericMatrix Pi_, double amin);
RcppExport SEXP _dynhr_hank_egm_step_cpp(SEXP Va_p_SEXP, SEXP a_grid_SEXP, SEXP y_SEXP, SEXP rSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP Pi_SEXP, SEXP aminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Va_p_(Va_p_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< double >::type amin(aminSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm_step_cpp(Va_p_, a_grid_, y_, r, beta, eis, Pi_, amin));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm_solve_cpp
List hank_egm_solve_cpp(NumericVector a_grid_, NumericVector y_, double r, double beta, double eis, NumericMatrix Pi_, double amin, double tol, int maxit, Nullable<NumericMatrix> Va_init_);
RcppExport SEXP _dynhr_hank_egm_solve_cpp(SEXP a_grid_SEXP, SEXP y_SEXP, SEXP rSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP Pi_SEXP, SEXP aminSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP Va_init_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< double >::type amin(aminSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Va_init_(Va_init_SEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm_solve_cpp(a_grid_, y_, r, beta, eis, Pi_, amin, tol, maxit, Va_init_));
    return rcpp_result_gen;
END_RCPP
}
// hank_stationary_dist_cpp
List hank_stationary_dist_cpp(NumericMatrix a_pol_, NumericVector a_grid_, NumericMatrix Pi_, double tol, int maxit);
RcppExport SEXP _dynhr_hank_stationary_dist_cpp(SEXP a_pol_SEXP, SEXP a_grid_SEXP, SEXP Pi_SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a_pol_(a_pol_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_stationary_dist_cpp(a_pol_, a_grid_, Pi_, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// hank_stationary_dist_lambda_cpp
List hank_stationary_dist_lambda_cpp(IntegerVector p, IntegerVector i, NumericVector x, int n, NumericVector d0, double tol, int maxit);
RcppExport SEXP _dynhr_hank_stationary_dist_lambda_cpp(SEXP pSEXP, SEXP iSEXP, SEXP xSEXP, SEXP nSEXP, SEXP d0SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_stationary_dist_lambda_cpp(p, i, x, n, d0, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm2_step_cpp
List hank_egm2_step_cpp(NumericVector Vb_p_, NumericVector Va_p_, NumericVector b_grid_, NumericVector a_grid_, NumericVector k_grid_, NumericVector y_, double rb, double ra, double beta, double eis, double chi0, double chi1, double chi2, NumericMatrix Pi_, NumericMatrix Psi1_grid_, int threads);
RcppExport SEXP _dynhr_hank_egm2_step_cpp(SEXP Vb_p_SEXP, SEXP Va_p_SEXP, SEXP b_grid_SEXP, SEXP a_grid_SEXP, SEXP k_grid_SEXP, SEXP y_SEXP, SEXP rbSEXP, SEXP raSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP chi0SEXP, SEXP chi1SEXP, SEXP chi2SEXP, SEXP Pi_SEXP, SEXP Psi1_grid_SEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Vb_p_(Vb_p_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Va_p_(Va_p_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_grid_(b_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_grid_(k_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< double >::type rb(rbSEXP);
    Rcpp::traits::input_parameter< double >::type ra(raSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< double >::type chi0(chi0SEXP);
    Rcpp::traits::input_parameter< double >::type chi1(chi1SEXP);
    Rcpp::traits::input_parameter< double >::type chi2(chi2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Psi1_grid_(Psi1_grid_SEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm2_step_cpp(Vb_p_, Va_p_, b_grid_, a_grid_, k_grid_, y_, rb, ra, beta, eis, chi0, chi1, chi2, Pi_, Psi1_grid_, threads));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm2_solve_cpp
List hank_egm2_solve_cpp(NumericVector Vb_init, NumericVector Va_init, NumericVector b_grid_, NumericVector a_grid_, NumericVector k_grid_, NumericVector y_, double rb, double ra, double beta, double eis, double chi0, double chi1, double chi2, NumericMatrix Pi_, NumericMatrix Psi1_grid_, double tol, int maxit, int threads);
RcppExport SEXP _dynhr_hank_egm2_solve_cpp(SEXP Vb_initSEXP, SEXP Va_initSEXP, SEXP b_grid_SEXP, SEXP a_grid_SEXP, SEXP k_grid_SEXP, SEXP y_SEXP, SEXP rbSEXP, SEXP raSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP chi0SEXP, SEXP chi1SEXP, SEXP chi2SEXP, SEXP Pi_SEXP, SEXP Psi1_grid_SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Vb_init(Vb_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Va_init(Va_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_grid_(b_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_grid_(k_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< double >::type rb(rbSEXP);
    Rcpp::traits::input_parameter< double >::type ra(raSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< double >::type chi0(chi0SEXP);
    Rcpp::traits::input_parameter< double >::type chi1(chi1SEXP);
    Rcpp::traits::input_parameter< double >::type chi2(chi2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Psi1_grid_(Psi1_grid_SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm2_solve_cpp(Vb_init, Va_init, b_grid_, a_grid_, k_grid_, y_, rb, ra, beta, eis, chi0, chi1, chi2, Pi_, Psi1_grid_, tol, maxit, threads));
    return rcpp_result_gen;
END_RCPP
}
// hank_curly_sweep2_cpp
List hank_curly_sweep2_cpp(NumericVector Vb_ss_, NumericVector Va_ss_, NumericVector dVb0_, NumericVector dVa0_, NumericVector b_grid_, NumericVector a_grid_, NumericVector k_grid_, NumericVector y_, double rb, double ra, double beta, double eis, double chi0, double chi1, double chi2, NumericMatrix Pi_, NumericMatrix Psi1_grid_, double delta_va, int T_h, int threads);
RcppExport SEXP _dynhr_hank_curly_sweep2_cpp(SEXP Vb_ss_SEXP, SEXP Va_ss_SEXP, SEXP dVb0_SEXP, SEXP dVa0_SEXP, SEXP b_grid_SEXP, SEXP a_grid_SEXP, SEXP k_grid_SEXP, SEXP y_SEXP, SEXP rbSEXP, SEXP raSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP chi0SEXP, SEXP chi1SEXP, SEXP chi2SEXP, SEXP Pi_SEXP, SEXP Psi1_grid_SEXP, SEXP delta_vaSEXP, SEXP T_hSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Vb_ss_(Vb_ss_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Va_ss_(Va_ss_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dVb0_(dVb0_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dVa0_(dVa0_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_grid_(b_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid_(a_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_grid_(k_grid_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< double >::type rb(rbSEXP);
    Rcpp::traits::input_parameter< double >::type ra(raSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< double >::type chi0(chi0SEXP);
    Rcpp::traits::input_parameter< double >::type chi1(chi1SEXP);
    Rcpp::traits::input_parameter< double >::type chi2(chi2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Psi1_grid_(Psi1_grid_SEXP);
    Rcpp::traits::input_parameter< double >::type delta_va(delta_vaSEXP);
    Rcpp::traits::input_parameter< int >::type T_h(T_hSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_curly_sweep2_cpp(Vb_ss_, Va_ss_, dVb0_, dVa0_, b_grid_, a_grid_, k_grid_, y_, rb, ra, beta, eis, chi0, chi1, chi2, Pi_, Psi1_grid_, delta_va, T_h, threads));
    return rcpp_result_gen;
END_RCPP
}
// hank_forward_apply3_cpp
NumericVector hank_forward_apply3_cpp(NumericVector d_pol, NumericVector f_pol, NumericVector a_pol, NumericVector d_grid, NumericVector f_grid, NumericVector a_grid, NumericMatrix Pi, NumericVector x, bool transpose);
RcppExport SEXP _dynhr_hank_forward_apply3_cpp(SEXP d_polSEXP, SEXP f_polSEXP, SEXP a_polSEXP, SEXP d_gridSEXP, SEXP f_gridSEXP, SEXP a_gridSEXP, SEXP PiSEXP, SEXP xSEXP, SEXP transposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d_pol(d_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_pol(f_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_pol(a_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d_grid(d_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_grid(f_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid(a_gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_forward_apply3_cpp(d_pol, f_pol, a_pol, d_grid, f_grid, a_grid, Pi, x, transpose));
    return rcpp_result_gen;
END_RCPP
}
// hank_forward_direction3_cpp
NumericVector hank_forward_direction3_cpp(NumericVector d_pol, NumericVector f_pol, NumericVector a_pol, NumericVector dd, NumericVector df, NumericVector da, NumericVector d_grid, NumericVector f_grid, NumericVector a_grid, NumericMatrix Pi, NumericVector dist, double delta, Nullable<NumericMatrix> Pi_p, Nullable<NumericMatrix> Pi_m);
RcppExport SEXP _dynhr_hank_forward_direction3_cpp(SEXP d_polSEXP, SEXP f_polSEXP, SEXP a_polSEXP, SEXP ddSEXP, SEXP dfSEXP, SEXP daSEXP, SEXP d_gridSEXP, SEXP f_gridSEXP, SEXP a_gridSEXP, SEXP PiSEXP, SEXP distSEXP, SEXP deltaSEXP, SEXP Pi_pSEXP, SEXP Pi_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d_pol(d_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_pol(f_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_pol(a_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dd(ddSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type da(daSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d_grid(d_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_grid(f_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid(a_gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Pi_p(Pi_pSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type Pi_m(Pi_mSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_forward_direction3_cpp(d_pol, f_pol, a_pol, dd, df, da, d_grid, f_grid, a_grid, Pi, dist, delta, Pi_p, Pi_m));
    return rcpp_result_gen;
END_RCPP
}
// hank_forward_legs3_cpp
NumericVector hank_forward_legs3_cpp(NumericVector d_plus, NumericVector f_plus, NumericVector a_plus, NumericVector d_minus, NumericVector f_minus, NumericVector a_minus, NumericVector d_grid, NumericVector f_grid, NumericVector a_grid, NumericMatrix Pi_plus, NumericMatrix Pi_minus, NumericVector dist, double step);
RcppExport SEXP _dynhr_hank_forward_legs3_cpp(SEXP d_plusSEXP, SEXP f_plusSEXP, SEXP a_plusSEXP, SEXP d_minusSEXP, SEXP f_minusSEXP, SEXP a_minusSEXP, SEXP d_gridSEXP, SEXP f_gridSEXP, SEXP a_gridSEXP, SEXP Pi_plusSEXP, SEXP Pi_minusSEXP, SEXP distSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d_plus(d_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_plus(f_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_plus(a_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d_minus(d_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_minus(f_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_minus(a_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d_grid(d_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_grid(f_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid(a_gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_plus(Pi_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_minus(Pi_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_forward_legs3_cpp(d_plus, f_plus, a_plus, d_minus, f_minus, a_minus, d_grid, f_grid, a_grid, Pi_plus, Pi_minus, dist, step));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm3_step_cpp
List hank_egm3_step_cpp(NumericVector Vd_, NumericVector Vf_, NumericVector Va_, NumericVector dg_, NumericVector fg_, NumericVector ag_, NumericVector y_, NumericMatrix Pi_, double rd, double rf, double ra, double beta, double eis, double chi0, double chi1, double chi2, double phi0, double phi1, double phi2, double px, int threads);
RcppExport SEXP _dynhr_hank_egm3_step_cpp(SEXP Vd_SEXP, SEXP Vf_SEXP, SEXP Va_SEXP, SEXP dg_SEXP, SEXP fg_SEXP, SEXP ag_SEXP, SEXP y_SEXP, SEXP Pi_SEXP, SEXP rdSEXP, SEXP rfSEXP, SEXP raSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP chi0SEXP, SEXP chi1SEXP, SEXP chi2SEXP, SEXP phi0SEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP pxSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Vd_(Vd_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Vf_(Vf_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Va_(Va_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dg_(dg_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fg_(fg_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ag_(ag_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi_(Pi_SEXP);
    Rcpp::traits::input_parameter< double >::type rd(rdSEXP);
    Rcpp::traits::input_parameter< double >::type rf(rfSEXP);
    Rcpp::traits::input_parameter< double >::type ra(raSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< double >::type chi0(chi0SEXP);
    Rcpp::traits::input_parameter< double >::type chi1(chi1SEXP);
    Rcpp::traits::input_parameter< double >::type chi2(chi2SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type px(pxSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm3_step_cpp(Vd_, Vf_, Va_, dg_, fg_, ag_, y_, Pi_, rd, rf, ra, beta, eis, chi0, chi1, chi2, phi0, phi1, phi2, px, threads));
    return rcpp_result_gen;
END_RCPP
}
// hank_egm3_solve_cpp
List hank_egm3_solve_cpp(NumericVector Vd, NumericVector Vf, NumericVector Va, NumericVector dg, NumericVector fg, NumericVector ag, NumericVector y, NumericMatrix Pi, double rd, double rf, double ra, double beta, double eis, double chi0, double chi1, double chi2, double phi0, double phi1, double phi2, double tol, int maxit, double relax, double px, int threads);
RcppExport SEXP _dynhr_hank_egm3_solve_cpp(SEXP VdSEXP, SEXP VfSEXP, SEXP VaSEXP, SEXP dgSEXP, SEXP fgSEXP, SEXP agSEXP, SEXP ySEXP, SEXP PiSEXP, SEXP rdSEXP, SEXP rfSEXP, SEXP raSEXP, SEXP betaSEXP, SEXP eisSEXP, SEXP chi0SEXP, SEXP chi1SEXP, SEXP chi2SEXP, SEXP phi0SEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP relaxSEXP, SEXP pxSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Vd(VdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Vf(VfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Va(VaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dg(dgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fg(fgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ag(agSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< double >::type rd(rdSEXP);
    Rcpp::traits::input_parameter< double >::type rf(rfSEXP);
    Rcpp::traits::input_parameter< double >::type ra(raSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eis(eisSEXP);
    Rcpp::traits::input_parameter< double >::type chi0(chi0SEXP);
    Rcpp::traits::input_parameter< double >::type chi1(chi1SEXP);
    Rcpp::traits::input_parameter< double >::type chi2(chi2SEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type relax(relaxSEXP);
    Rcpp::traits::input_parameter< double >::type px(pxSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_egm3_solve_cpp(Vd, Vf, Va, dg, fg, ag, y, Pi, rd, rf, ra, beta, eis, chi0, chi1, chi2, phi0, phi1, phi2, tol, maxit, relax, px, threads));
    return rcpp_result_gen;
END_RCPP
}
// hank_fnv1a64_cpp
std::string hank_fnv1a64_cpp(RawVector x);
RcppExport SEXP _dynhr_hank_fnv1a64_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_fnv1a64_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// hank_forward_push2_scatter_cpp
NumericVector hank_forward_push2_scatter_cpp(NumericVector b_pol, NumericVector a_pol, NumericVector b_grid, NumericVector a_grid, NumericVector Dv, int n_e, int n_b, int n_a);
RcppExport SEXP _dynhr_hank_forward_push2_scatter_cpp(SEXP b_polSEXP, SEXP a_polSEXP, SEXP b_gridSEXP, SEXP a_gridSEXP, SEXP DvSEXP, SEXP n_eSEXP, SEXP n_bSEXP, SEXP n_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b_pol(b_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_pol(a_polSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_grid(b_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_grid(a_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Dv(DvSEXP);
    Rcpp::traits::input_parameter< int >::type n_e(n_eSEXP);
    Rcpp::traits::input_parameter< int >::type n_b(n_bSEXP);
    Rcpp::traits::input_parameter< int >::type n_a(n_aSEXP);
    rcpp_result_gen = Rcpp::wrap(hank_forward_push2_scatter_cpp(b_pol, a_pol, b_grid, a_grid, Dv, n_e, n_b, n_a));
    return rcpp_result_gen;
END_RCPP
}
// eval_jac_tape_cpp
arma::mat eval_jac_tape_cpp(const arma::vec& dy, const arma::vec& params, const arma::vec& ss, const arma::ivec& op, const arma::ivec& ia, const arma::vec& da, const arma::ivec& expr_len, const arma::ivec& out_row, const arma::ivec& out_col, int n_eq, int total_cols);
RcppExport SEXP _dynhr_eval_jac_tape_cpp(SEXP dySEXP, SEXP paramsSEXP, SEXP ssSEXP, SEXP opSEXP, SEXP iaSEXP, SEXP daSEXP, SEXP expr_lenSEXP, SEXP out_rowSEXP, SEXP out_colSEXP, SEXP n_eqSEXP, SEXP total_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dy(dySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type op(opSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ia(iaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type expr_len(expr_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type out_row(out_rowSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type out_col(out_colSEXP);
    Rcpp::traits::input_parameter< int >::type n_eq(n_eqSEXP);
    Rcpp::traits::input_parameter< int >::type total_cols(total_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_jac_tape_cpp(dy, params, ss, op, ia, da, expr_len, out_row, out_col, n_eq, total_cols));
    return rcpp_result_gen;
END_RCPP
}
// eval_triplet_tape_cpp
arma::vec eval_triplet_tape_cpp(const arma::vec& dy, const arma::vec& params, const arma::vec& ss, const arma::ivec& op, const arma::ivec& ia, const arma::vec& da, const arma::ivec& expr_len);
RcppExport SEXP _dynhr_eval_triplet_tape_cpp(SEXP dySEXP, SEXP paramsSEXP, SEXP ssSEXP, SEXP opSEXP, SEXP iaSEXP, SEXP daSEXP, SEXP expr_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dy(dySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type op(opSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ia(iaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type expr_len(expr_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_triplet_tape_cpp(dy, params, ss, op, ia, da, expr_len));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_cpp
List kf_adjoint_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& shock_scale_mat, const arma::mat& me_extra_mat, const bool return_bars);
RcppExport SEXP _dynhr_kf_adjoint_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP shock_scale_matSEXP, SEXP me_extra_matSEXP, SEXP return_barsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shock_scale_mat(shock_scale_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_extra_mat(me_extra_matSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_bars(return_barsSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat, return_bars));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_uni_cpp
List kf_adjoint_uni_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& P0_in, bool p0_supplied);
RcppExport SEXP _dynhr_kf_adjoint_uni_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP P0_inSEXP, SEXP p0_suppliedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0_in(P0_inSEXP);
    Rcpp::traits::input_parameter< bool >::type p0_supplied(p0_suppliedSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_uni_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, P0_in, p0_supplied));
    return rcpp_result_gen;
END_RCPP
}
// kalman_ss_loop_cpp
List kalman_ss_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& ZZ, const arma::mat& TT, const arma::mat& K_ss, const arma::mat& F_inv_ss, double ll_ss_const, arma::vec s, int start_t, int end_t, bool return_filtered);
RcppExport SEXP _dynhr_kalman_ss_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZZSEXP, SEXP TTSEXP, SEXP K_ssSEXP, SEXP F_inv_ssSEXP, SEXP ll_ss_constSEXP, SEXP sSEXP, SEXP start_tSEXP, SEXP end_tSEXP, SEXP return_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K_ss(K_ssSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F_inv_ss(F_inv_ssSEXP);
    Rcpp::traits::input_parameter< double >::type ll_ss_const(ll_ss_constSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type start_t(start_tSEXP);
    Rcpp::traits::input_parameter< int >::type end_t(end_tSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_ss_loop_cpp(Y_minus_d, ZZ, TT, K_ss, F_inv_ss, ll_ss_const, s, start_t, end_t, return_filtered));
    return rcpp_result_gen;
END_RCPP
}
// kalman_standard_loop_cpp
List kalman_standard_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& ZZ, const arma::mat& TT, const arma::mat& RR, const arma::mat& DD, const arma::mat& HH_full, const arma::mat& Sigma_e, const arma::mat& SS, arma::mat P, double ll_const, double ss_tol, double ll_min, bool return_filtered);
RcppExport SEXP _dynhr_kalman_standard_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZZSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP DDSEXP, SEXP HH_fullSEXP, SEXP Sigma_eSEXP, SEXP SSSEXP, SEXP PSEXP, SEXP ll_constSEXP, SEXP ss_tolSEXP, SEXP ll_minSEXP, SEXP return_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type HH_full(HH_fullSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type ll_const(ll_constSEXP);
    Rcpp::traits::input_parameter< double >::type ss_tol(ss_tolSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_standard_loop_cpp(Y_minus_d, ZZ, TT, RR, DD, HH_full, Sigma_e, SS, P, ll_const, ss_tol, ll_min, return_filtered));
    return rcpp_result_gen;
END_RCPP
}
// kalman_univariate_loop_cpp
List kalman_univariate_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& Zb, const arma::mat& Tb, const arma::mat& QQb, arma::vec a, arma::mat P_star, arma::mat P_inf, double me_variance, double kalman_tol, double diffuse_tol, double conv_tol, int max_diffuse, double ll_min, bool return_filtered, int n_state, bool ss_lock);
RcppExport SEXP _dynhr_kalman_univariate_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZbSEXP, SEXP TbSEXP, SEXP QQbSEXP, SEXP aSEXP, SEXP P_starSEXP, SEXP P_infSEXP, SEXP me_varianceSEXP, SEXP kalman_tolSEXP, SEXP diffuse_tolSEXP, SEXP conv_tolSEXP, SEXP max_diffuseSEXP, SEXP ll_minSEXP, SEXP return_filteredSEXP, SEXP n_stateSEXP, SEXP ss_lockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zb(ZbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Tb(TbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type QQb(QQbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_star(P_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_inf(P_infSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type kalman_tol(kalman_tolSEXP);
    Rcpp::traits::input_parameter< double >::type diffuse_tol(diffuse_tolSEXP);
    Rcpp::traits::input_parameter< double >::type conv_tol(conv_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_diffuse(max_diffuseSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    Rcpp::traits::input_parameter< int >::type n_state(n_stateSEXP);
    Rcpp::traits::input_parameter< bool >::type ss_lock(ss_lockSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_univariate_loop_cpp(Y_minus_d, Zb, Tb, QQb, a, P_star, P_inf, me_variance, kalman_tol, diffuse_tol, conv_tol, max_diffuse, ll_min, return_filtered, n_state, ss_lock));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_diffuse_cpp
List kf_adjoint_diffuse_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d_obs, const arma::mat& Sigma_e, double me_variance, double ur_tol);
RcppExport SEXP _dynhr_kf_adjoint_diffuse_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP d_obsSEXP, SEXP Sigma_eSEXP, SEXP me_varianceSEXP, SEXP ur_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ur_tol(ur_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_diffuse_cpp(Y, TT, RR, ZZ, DD, d_obs, Sigma_e, me_variance, ur_tol));
    return rcpp_result_gen;
END_RCPP
}
// kf_loglik_dG_cpp
List kf_loglik_dG_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::mat& dTT, const arma::mat& dRR, const arma::mat& dZZ, const arma::mat& dDD, const arma::vec& dd_dir, const arma::mat& dSig, double me_variance, double ll_min);
RcppExport SEXP _dynhr_kf_loglik_dG_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTTSEXP, SEXP dRRSEXP, SEXP dZZSEXP, SEXP dDDSEXP, SEXP dd_dirSEXP, SEXP dSigSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dTT(dTTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dRR(dRRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dZZ(dZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dDD(dDDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dd_dir(dd_dirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dSig(dSigSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_loglik_dG_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT, dRR, dZZ, dDD, dd_dir, dSig, me_variance, ll_min));
    return rcpp_result_gen;
END_RCPP
}
// kf_score_sigma_cpp
List kf_score_sigma_cpp(const arma::mat& Yd, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::mat& Sigma_e, const arma::mat& HH, const arma::mat& SS, const arma::mat& me_diag, const arma::mat& P0, const List& dSigma, const List& dH, const List& dS, const List& dP0, double ss_tol);
RcppExport SEXP _dynhr_kf_score_sigma_cpp(SEXP YdSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP Sigma_eSEXP, SEXP HHSEXP, SEXP SSSEXP, SEXP me_diagSEXP, SEXP P0SEXP, SEXP dSigmaSEXP, SEXP dHSEXP, SEXP dSSEXP, SEXP dP0SEXP, SEXP ss_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Yd(YdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type HH(HHSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_diag(me_diagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const List& >::type dSigma(dSigmaSEXP);
    Rcpp::traits::input_parameter< const List& >::type dH(dHSEXP);
    Rcpp::traits::input_parameter< const List& >::type dS(dSSEXP);
    Rcpp::traits::input_parameter< const List& >::type dP0(dP0SEXP);
    Rcpp::traits::input_parameter< double >::type ss_tol(ss_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_score_sigma_cpp(Yd, TT, RR, ZZ, DD, Sigma_e, HH, SS, me_diag, P0, dSigma, dH, dS, dP0, ss_tol));
    return rcpp_result_gen;
END_RCPP
}
// kf_tangent_cpp
List kf_tangent_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& shock_scale_mat, const arma::mat& me_extra_mat);
RcppExport SEXP _dynhr_kf_tangent_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP shock_scale_matSEXP, SEXP me_extra_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shock_scale_mat(shock_scale_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_extra_mat(me_extra_matSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_tangent_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat));
    return rcpp_result_gen;
END_RCPP
}
// mcp_sparse_solve_cpp
NumericVector mcp_sparse_solve_cpp(IntegerVector i_idx, IntegerVector j_idx, NumericVector x_vals, NumericVector rhs, int n_dim);
RcppExport SEXP _dynhr_mcp_sparse_solve_cpp(SEXP i_idxSEXP, SEXP j_idxSEXP, SEXP x_valsSEXP, SEXP rhsSEXP, SEXP n_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i_idx(i_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j_idx(j_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< int >::type n_dim(n_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(mcp_sparse_solve_cpp(i_idx, j_idx, x_vals, rhs, n_dim));
    return rcpp_result_gen;
END_RCPP
}
// ordered_qz_cpp
List ordered_qz_cpp(const arma::mat& E, const arma::mat& D, double critmod);
RcppExport SEXP _dynhr_ordered_qz_cpp(SEXP ESEXP, SEXP DSEXP, SEXP critmodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type critmod(critmodSEXP);
    rcpp_result_gen = Rcpp::wrap(ordered_qz_cpp(E, D, critmod));
    return rcpp_result_gen;
END_RCPP
}
// hank_peak_rss
double hank_peak_rss();
RcppExport SEXP _dynhr_hank_peak_rss() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hank_peak_rss());
    return rcpp_result_gen;
END_RCPP
}
// qr_static_transform_cpp
List qr_static_transform_cpp(const arma::mat& f_static, const arma::mat& f_minus_r, const arma::mat& f_zero_r, const arma::mat& f_plus_r, const arma::mat& f_exo_r);
RcppExport SEXP _dynhr_qr_static_transform_cpp(SEXP f_staticSEXP, SEXP f_minus_rSEXP, SEXP f_zero_rSEXP, SEXP f_plus_rSEXP, SEXP f_exo_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type f_static(f_staticSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_minus_r(f_minus_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_zero_r(f_zero_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_plus_r(f_plus_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_exo_r(f_exo_rSEXP);
    rcpp_result_gen = Rcpp::wrap(qr_static_transform_cpp(f_static, f_minus_r, f_zero_r, f_plus_r, f_exo_r));
    return rcpp_result_gen;
END_RCPP
}
// sv_rbpf_loglik_cpp
double sv_rbpf_loglik_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& ZZ, const arma::mat& RR, const arma::mat& DD, const arma::mat& Sigma_e, const arma::vec& d, const arma::mat& P0, const arma::uvec& sv_idx1, const arma::vec& mu, const arma::vec& rho, const arma::vec& seta, const int n_particles, const arma::vec& me_diag);
RcppExport SEXP _dynhr_sv_rbpf_loglik_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP ZZSEXP, SEXP RRSEXP, SEXP DDSEXP, SEXP Sigma_eSEXP, SEXP dSEXP, SEXP P0SEXP, SEXP sv_idx1SEXP, SEXP muSEXP, SEXP rhoSEXP, SEXP setaSEXP, SEXP n_particlesSEXP, SEXP me_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sv_idx1(sv_idx1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type seta(setaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type me_diag(me_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(sv_rbpf_loglik_cpp(Y, TT, ZZ, RR, DD, Sigma_e, d, P0, sv_idx1, mu, rho, seta, n_particles, me_diag));
    return rcpp_result_gen;
END_RCPP
}
// tpf_propagate_particles
arma::mat tpf_propagate_particles(const arma::mat& particles, const arma::mat& shocks, const arma::mat& hx, const arma::mat& hu, const arma::mat& hxx, const arma::mat& hxu, const arma::mat& huu, const arma::vec& hss);
RcppExport SEXP _dynhr_tpf_propagate_particles(SEXP particlesSEXP, SEXP shocksSEXP, SEXP hxSEXP, SEXP huSEXP, SEXP hxxSEXP, SEXP hxuSEXP, SEXP huuSEXP, SEXP hssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hu(huSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hxx(hxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hxu(hxuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type huu(huuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hss(hssSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_propagate_particles(particles, shocks, hx, hu, hxx, hxu, huu, hss));
    return rcpp_result_gen;
END_RCPP
}
// tpf_run_period_cpp
List tpf_run_period_cpp(arma::mat particles, const arma::vec y_t, const arma::mat L_e, const arma::mat hx, const arma::mat hu, const arma::mat hxx, const arma::mat hxu, const arma::mat huu, const arma::vec hss, const arma::mat ZZ, const arma::mat DD, const arma::vec d_obs, const arma::vec ghss_obs, double me_variance, double ess_target, int n_mh, double mh_scale, int max_stages, Rcpp::Nullable<arma::mat> U_normals, Rcpp::Nullable<double> U_resample, Rcpp::Nullable<arma::vec> U_mid, Rcpp::Nullable<arma::mat> U_mutation);
RcppExport SEXP _dynhr_tpf_run_period_cpp(SEXP particlesSEXP, SEXP y_tSEXP, SEXP L_eSEXP, SEXP hxSEXP, SEXP huSEXP, SEXP hxxSEXP, SEXP hxuSEXP, SEXP huuSEXP, SEXP hssSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP d_obsSEXP, SEXP ghss_obsSEXP, SEXP me_varianceSEXP, SEXP ess_targetSEXP, SEXP n_mhSEXP, SEXP mh_scaleSEXP, SEXP max_stagesSEXP, SEXP U_normalsSEXP, SEXP U_resampleSEXP, SEXP U_midSEXP, SEXP U_mutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_t(y_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type L_e(L_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hu(huSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hxx(hxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hxu(hxuSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type huu(huuSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type hss(hssSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ghss_obs(ghss_obsSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ess_target(ess_targetSEXP);
    Rcpp::traits::input_parameter< int >::type n_mh(n_mhSEXP);
    Rcpp::traits::input_parameter< double >::type mh_scale(mh_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type max_stages(max_stagesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type U_normals(U_normalsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type U_resample(U_resampleSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type U_mid(U_midSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type U_mutation(U_mutationSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_run_period_cpp(particles, y_t, L_e, hx, hu, hxx, hxu, huu, hss, ZZ, DD, d_obs, ghss_obs, me_variance, ess_target, n_mh, mh_scale, max_stages, U_normals, U_resample, U_mid, U_mutation));
    return rcpp_result_gen;
END_RCPP
}
// tpf_log_weights
arma::vec tpf_log_weights(const arma::mat& particles, const arma::vec& y_t, const arma::mat& ZZ, const arma::mat& DD, const arma::mat& shocks, const arma::vec& d_obs, const arma::vec& ghss_obs, double me_variance, double phi);
RcppExport SEXP _dynhr_tpf_log_weights(SEXP particlesSEXP, SEXP y_tSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP shocksSEXP, SEXP d_obsSEXP, SEXP ghss_obsSEXP, SEXP me_varianceSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_t(y_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ghss_obs(ghss_obsSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_log_weights(particles, y_t, ZZ, DD, shocks, d_obs, ghss_obs, me_variance, phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynhr_fdb_compose_folded_cpp", (DL_FUNC) &_dynhr_fdb_compose_folded_cpp, 5},
    {"_dynhr_hank_ar_slab_adjoint_psi_cpp", (DL_FUNC) &_dynhr_hank_ar_slab_adjoint_psi_cpp, 2},
    {"_dynhr_hank_ar_score_weights_cpp", (DL_FUNC) &_dynhr_hank_ar_score_weights_cpp, 4},
    {"_dynhr_hank_egm_step_cpp", (DL_FUNC) &_dynhr_hank_egm_step_cpp, 8},
    {"_dynhr_hank_egm_solve_cpp", (DL_FUNC) &_dynhr_hank_egm_solve_cpp, 10},
    {"_dynhr_hank_stationary_dist_cpp", (DL_FUNC) &_dynhr_hank_stationary_dist_cpp, 5},
    {"_dynhr_hank_stationary_dist_lambda_cpp", (DL_FUNC) &_dynhr_hank_stationary_dist_lambda_cpp, 7},
    {"_dynhr_hank_egm2_step_cpp", (DL_FUNC) &_dynhr_hank_egm2_step_cpp, 16},
    {"_dynhr_hank_egm2_solve_cpp", (DL_FUNC) &_dynhr_hank_egm2_solve_cpp, 18},
    {"_dynhr_hank_curly_sweep2_cpp", (DL_FUNC) &_dynhr_hank_curly_sweep2_cpp, 20},
    {"_dynhr_hank_forward_apply3_cpp", (DL_FUNC) &_dynhr_hank_forward_apply3_cpp, 9},
    {"_dynhr_hank_forward_direction3_cpp", (DL_FUNC) &_dynhr_hank_forward_direction3_cpp, 14},
    {"_dynhr_hank_forward_legs3_cpp", (DL_FUNC) &_dynhr_hank_forward_legs3_cpp, 13},
    {"_dynhr_hank_egm3_step_cpp", (DL_FUNC) &_dynhr_hank_egm3_step_cpp, 21},
    {"_dynhr_hank_egm3_solve_cpp", (DL_FUNC) &_dynhr_hank_egm3_solve_cpp, 24},
    {"_dynhr_hank_fnv1a64_cpp", (DL_FUNC) &_dynhr_hank_fnv1a64_cpp, 1},
    {"_dynhr_hank_forward_push2_scatter_cpp", (DL_FUNC) &_dynhr_hank_forward_push2_scatter_cpp, 8},
    {"_dynhr_eval_jac_tape_cpp", (DL_FUNC) &_dynhr_eval_jac_tape_cpp, 11},
    {"_dynhr_eval_triplet_tape_cpp", (DL_FUNC) &_dynhr_eval_triplet_tape_cpp, 7},
    {"_dynhr_kf_adjoint_cpp", (DL_FUNC) &_dynhr_kf_adjoint_cpp, 18},
    {"_dynhr_kf_adjoint_uni_cpp", (DL_FUNC) &_dynhr_kf_adjoint_uni_cpp, 17},
    {"_dynhr_kalman_ss_loop_cpp", (DL_FUNC) &_dynhr_kalman_ss_loop_cpp, 10},
    {"_dynhr_kalman_standard_loop_cpp", (DL_FUNC) &_dynhr_kalman_standard_loop_cpp, 13},
    {"_dynhr_kalman_univariate_loop_cpp", (DL_FUNC) &_dynhr_kalman_univariate_loop_cpp, 16},
    {"_dynhr_kf_adjoint_diffuse_cpp", (DL_FUNC) &_dynhr_kf_adjoint_diffuse_cpp, 9},
    {"_dynhr_kf_loglik_dG_cpp", (DL_FUNC) &_dynhr_kf_loglik_dG_cpp, 15},
    {"_dynhr_kf_score_sigma_cpp", (DL_FUNC) &_dynhr_kf_score_sigma_cpp, 15},
    {"_dynhr_kf_tangent_cpp", (DL_FUNC) &_dynhr_kf_tangent_cpp, 17},
    {"_dynhr_mcp_sparse_solve_cpp", (DL_FUNC) &_dynhr_mcp_sparse_solve_cpp, 5},
    {"_dynhr_ordered_qz_cpp", (DL_FUNC) &_dynhr_ordered_qz_cpp, 3},
    {"_dynhr_hank_peak_rss", (DL_FUNC) &_dynhr_hank_peak_rss, 0},
    {"_dynhr_qr_static_transform_cpp", (DL_FUNC) &_dynhr_qr_static_transform_cpp, 5},
    {"_dynhr_sv_rbpf_loglik_cpp", (DL_FUNC) &_dynhr_sv_rbpf_loglik_cpp, 14},
    {"_dynhr_tpf_propagate_particles", (DL_FUNC) &_dynhr_tpf_propagate_particles, 8},
    {"_dynhr_tpf_run_period_cpp", (DL_FUNC) &_dynhr_tpf_run_period_cpp, 22},
    {"_dynhr_tpf_log_weights", (DL_FUNC) &_dynhr_tpf_log_weights, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynhr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
