// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fdb_compose_folded_cpp
NumericMatrix fdb_compose_folded_cpp(int Nc, int n_out, List shapes, List Glist, List Hlist);
RcppExport SEXP _dynhr_fdb_compose_folded_cpp(SEXP NcSEXP, SEXP n_outSEXP, SEXP shapesSEXP, SEXP GlistSEXP, SEXP HlistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< List >::type shapes(shapesSEXP);
    Rcpp::traits::input_parameter< List >::type Glist(GlistSEXP);
    Rcpp::traits::input_parameter< List >::type Hlist(HlistSEXP);
    rcpp_result_gen = Rcpp::wrap(fdb_compose_folded_cpp(Nc, n_out, shapes, Glist, Hlist));
    return rcpp_result_gen;
END_RCPP
}
// eval_jac_tape_cpp
arma::mat eval_jac_tape_cpp(const arma::vec& dy, const arma::vec& params, const arma::vec& ss, const arma::ivec& op, const arma::ivec& ia, const arma::vec& da, const arma::ivec& expr_len, const arma::ivec& out_row, const arma::ivec& out_col, int n_eq, int total_cols);
RcppExport SEXP _dynhr_eval_jac_tape_cpp(SEXP dySEXP, SEXP paramsSEXP, SEXP ssSEXP, SEXP opSEXP, SEXP iaSEXP, SEXP daSEXP, SEXP expr_lenSEXP, SEXP out_rowSEXP, SEXP out_colSEXP, SEXP n_eqSEXP, SEXP total_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dy(dySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type op(opSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ia(iaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type expr_len(expr_lenSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type out_row(out_rowSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type out_col(out_colSEXP);
    Rcpp::traits::input_parameter< int >::type n_eq(n_eqSEXP);
    Rcpp::traits::input_parameter< int >::type total_cols(total_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_jac_tape_cpp(dy, params, ss, op, ia, da, expr_len, out_row, out_col, n_eq, total_cols));
    return rcpp_result_gen;
END_RCPP
}
// eval_triplet_tape_cpp
arma::vec eval_triplet_tape_cpp(const arma::vec& dy, const arma::vec& params, const arma::vec& ss, const arma::ivec& op, const arma::ivec& ia, const arma::vec& da, const arma::ivec& expr_len);
RcppExport SEXP _dynhr_eval_triplet_tape_cpp(SEXP dySEXP, SEXP paramsSEXP, SEXP ssSEXP, SEXP opSEXP, SEXP iaSEXP, SEXP daSEXP, SEXP expr_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dy(dySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type op(opSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ia(iaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type expr_len(expr_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_triplet_tape_cpp(dy, params, ss, op, ia, da, expr_len));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_cpp
List kf_adjoint_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& shock_scale_mat, const arma::mat& me_extra_mat);
RcppExport SEXP _dynhr_kf_adjoint_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP shock_scale_matSEXP, SEXP me_extra_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shock_scale_mat(shock_scale_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_extra_mat(me_extra_matSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_uni_cpp
List kf_adjoint_uni_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& P0_in, bool p0_supplied);
RcppExport SEXP _dynhr_kf_adjoint_uni_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP P0_inSEXP, SEXP p0_suppliedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0_in(P0_inSEXP);
    Rcpp::traits::input_parameter< bool >::type p0_supplied(p0_suppliedSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_uni_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, P0_in, p0_supplied));
    return rcpp_result_gen;
END_RCPP
}
// kalman_ss_loop_cpp
List kalman_ss_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& ZZ, const arma::mat& TT, const arma::mat& K_ss, const arma::mat& F_inv_ss, double ll_ss_const, arma::vec s, int start_t, int end_t, bool return_filtered);
RcppExport SEXP _dynhr_kalman_ss_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZZSEXP, SEXP TTSEXP, SEXP K_ssSEXP, SEXP F_inv_ssSEXP, SEXP ll_ss_constSEXP, SEXP sSEXP, SEXP start_tSEXP, SEXP end_tSEXP, SEXP return_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K_ss(K_ssSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type F_inv_ss(F_inv_ssSEXP);
    Rcpp::traits::input_parameter< double >::type ll_ss_const(ll_ss_constSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type start_t(start_tSEXP);
    Rcpp::traits::input_parameter< int >::type end_t(end_tSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_ss_loop_cpp(Y_minus_d, ZZ, TT, K_ss, F_inv_ss, ll_ss_const, s, start_t, end_t, return_filtered));
    return rcpp_result_gen;
END_RCPP
}
// kalman_standard_loop_cpp
List kalman_standard_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& ZZ, const arma::mat& TT, const arma::mat& RR, const arma::mat& DD, const arma::mat& HH_full, const arma::mat& Sigma_e, const arma::mat& SS, arma::mat P, double ll_const, double ss_tol, double ll_min, bool return_filtered);
RcppExport SEXP _dynhr_kalman_standard_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZZSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP DDSEXP, SEXP HH_fullSEXP, SEXP Sigma_eSEXP, SEXP SSSEXP, SEXP PSEXP, SEXP ll_constSEXP, SEXP ss_tolSEXP, SEXP ll_minSEXP, SEXP return_filteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type HH_full(HH_fullSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type ll_const(ll_constSEXP);
    Rcpp::traits::input_parameter< double >::type ss_tol(ss_tolSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_standard_loop_cpp(Y_minus_d, ZZ, TT, RR, DD, HH_full, Sigma_e, SS, P, ll_const, ss_tol, ll_min, return_filtered));
    return rcpp_result_gen;
END_RCPP
}
// kalman_univariate_loop_cpp
List kalman_univariate_loop_cpp(const arma::mat& Y_minus_d, const arma::mat& Zb, const arma::mat& Tb, const arma::mat& QQb, arma::vec a, arma::mat P_star, arma::mat P_inf, double me_variance, double kalman_tol, double diffuse_tol, double conv_tol, int max_diffuse, double ll_min, bool return_filtered, int n_state, bool ss_lock);
RcppExport SEXP _dynhr_kalman_univariate_loop_cpp(SEXP Y_minus_dSEXP, SEXP ZbSEXP, SEXP TbSEXP, SEXP QQbSEXP, SEXP aSEXP, SEXP P_starSEXP, SEXP P_infSEXP, SEXP me_varianceSEXP, SEXP kalman_tolSEXP, SEXP diffuse_tolSEXP, SEXP conv_tolSEXP, SEXP max_diffuseSEXP, SEXP ll_minSEXP, SEXP return_filteredSEXP, SEXP n_stateSEXP, SEXP ss_lockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_minus_d(Y_minus_dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zb(ZbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Tb(TbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type QQb(QQbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_star(P_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_inf(P_infSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type kalman_tol(kalman_tolSEXP);
    Rcpp::traits::input_parameter< double >::type diffuse_tol(diffuse_tolSEXP);
    Rcpp::traits::input_parameter< double >::type conv_tol(conv_tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_diffuse(max_diffuseSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< bool >::type return_filtered(return_filteredSEXP);
    Rcpp::traits::input_parameter< int >::type n_state(n_stateSEXP);
    Rcpp::traits::input_parameter< bool >::type ss_lock(ss_lockSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_univariate_loop_cpp(Y_minus_d, Zb, Tb, QQb, a, P_star, P_inf, me_variance, kalman_tol, diffuse_tol, conv_tol, max_diffuse, ll_min, return_filtered, n_state, ss_lock));
    return rcpp_result_gen;
END_RCPP
}
// kf_adjoint_diffuse_cpp
List kf_adjoint_diffuse_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d_obs, const arma::mat& Sigma_e, double me_variance, double ur_tol);
RcppExport SEXP _dynhr_kf_adjoint_diffuse_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP d_obsSEXP, SEXP Sigma_eSEXP, SEXP me_varianceSEXP, SEXP ur_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ur_tol(ur_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_adjoint_diffuse_cpp(Y, TT, RR, ZZ, DD, d_obs, Sigma_e, me_variance, ur_tol));
    return rcpp_result_gen;
END_RCPP
}
// kf_loglik_dG_cpp
List kf_loglik_dG_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::mat& dTT, const arma::mat& dRR, const arma::mat& dZZ, const arma::mat& dDD, const arma::vec& dd_dir, const arma::mat& dSig, double me_variance, double ll_min);
RcppExport SEXP _dynhr_kf_loglik_dG_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTTSEXP, SEXP dRRSEXP, SEXP dZZSEXP, SEXP dDDSEXP, SEXP dd_dirSEXP, SEXP dSigSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dTT(dTTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dRR(dRRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dZZ(dZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dDD(dDDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dd_dir(dd_dirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dSig(dSigSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_loglik_dG_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT, dRR, dZZ, dDD, dd_dir, dSig, me_variance, ll_min));
    return rcpp_result_gen;
END_RCPP
}
// kf_score_sigma_cpp
List kf_score_sigma_cpp(const arma::mat& Yd, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::mat& Sigma_e, const arma::mat& HH, const arma::mat& SS, const arma::mat& me_diag, const arma::mat& P0, const List& dSigma, const List& dH, const List& dS, const List& dP0, double ss_tol);
RcppExport SEXP _dynhr_kf_score_sigma_cpp(SEXP YdSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP Sigma_eSEXP, SEXP HHSEXP, SEXP SSSEXP, SEXP me_diagSEXP, SEXP P0SEXP, SEXP dSigmaSEXP, SEXP dHSEXP, SEXP dSSEXP, SEXP dP0SEXP, SEXP ss_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Yd(YdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type HH(HHSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_diag(me_diagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const List& >::type dSigma(dSigmaSEXP);
    Rcpp::traits::input_parameter< const List& >::type dH(dHSEXP);
    Rcpp::traits::input_parameter< const List& >::type dS(dSSEXP);
    Rcpp::traits::input_parameter< const List& >::type dP0(dP0SEXP);
    Rcpp::traits::input_parameter< double >::type ss_tol(ss_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_score_sigma_cpp(Yd, TT, RR, ZZ, DD, Sigma_e, HH, SS, me_diag, P0, dSigma, dH, dS, dP0, ss_tol));
    return rcpp_result_gen;
END_RCPP
}
// kf_tangent_cpp
List kf_tangent_cpp(const arma::mat& Y, const arma::mat& TT, const arma::mat& RR, const arma::mat& ZZ, const arma::mat& DD, const arma::vec& d, const arma::mat& Sigma_e, const arma::cube& dTT_cube, const arma::cube& dRR_cube, const arma::cube& dZZ_cube, const arma::cube& dDD_cube, const arma::mat& dd_mat, const arma::cube& dSigma_cube, double me_variance, double ll_min, const arma::mat& shock_scale_mat, const arma::mat& me_extra_mat);
RcppExport SEXP _dynhr_kf_tangent_cpp(SEXP YSEXP, SEXP TTSEXP, SEXP RRSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP dSEXP, SEXP Sigma_eSEXP, SEXP dTT_cubeSEXP, SEXP dRR_cubeSEXP, SEXP dZZ_cubeSEXP, SEXP dDD_cubeSEXP, SEXP dd_matSEXP, SEXP dSigma_cubeSEXP, SEXP me_varianceSEXP, SEXP ll_minSEXP, SEXP shock_scale_matSEXP, SEXP me_extra_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_e(Sigma_eSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dTT_cube(dTT_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dRR_cube(dRR_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dZZ_cube(dZZ_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dDD_cube(dDD_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dd_mat(dd_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dSigma_cube(dSigma_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ll_min(ll_minSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shock_scale_mat(shock_scale_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me_extra_mat(me_extra_matSEXP);
    rcpp_result_gen = Rcpp::wrap(kf_tangent_cpp(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat));
    return rcpp_result_gen;
END_RCPP
}
// mcp_sparse_solve_cpp
NumericVector mcp_sparse_solve_cpp(IntegerVector i_idx, IntegerVector j_idx, NumericVector x_vals, NumericVector rhs, int n_dim);
RcppExport SEXP _dynhr_mcp_sparse_solve_cpp(SEXP i_idxSEXP, SEXP j_idxSEXP, SEXP x_valsSEXP, SEXP rhsSEXP, SEXP n_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i_idx(i_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j_idx(j_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< int >::type n_dim(n_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(mcp_sparse_solve_cpp(i_idx, j_idx, x_vals, rhs, n_dim));
    return rcpp_result_gen;
END_RCPP
}
// ordered_qz_cpp
List ordered_qz_cpp(const arma::mat& E, const arma::mat& D, double critmod);
RcppExport SEXP _dynhr_ordered_qz_cpp(SEXP ESEXP, SEXP DSEXP, SEXP critmodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type critmod(critmodSEXP);
    rcpp_result_gen = Rcpp::wrap(ordered_qz_cpp(E, D, critmod));
    return rcpp_result_gen;
END_RCPP
}
// qr_static_transform_cpp
List qr_static_transform_cpp(const arma::mat& f_static, const arma::mat& f_minus_r, const arma::mat& f_zero_r, const arma::mat& f_plus_r, const arma::mat& f_exo_r);
RcppExport SEXP _dynhr_qr_static_transform_cpp(SEXP f_staticSEXP, SEXP f_minus_rSEXP, SEXP f_zero_rSEXP, SEXP f_plus_rSEXP, SEXP f_exo_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type f_static(f_staticSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_minus_r(f_minus_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_zero_r(f_zero_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_plus_r(f_plus_rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type f_exo_r(f_exo_rSEXP);
    rcpp_result_gen = Rcpp::wrap(qr_static_transform_cpp(f_static, f_minus_r, f_zero_r, f_plus_r, f_exo_r));
    return rcpp_result_gen;
END_RCPP
}
// tpf_propagate_particles
arma::mat tpf_propagate_particles(const arma::mat& particles, const arma::mat& shocks, const arma::mat& hx, const arma::mat& hu, const arma::mat& hxx, const arma::mat& hxu, const arma::mat& huu, const arma::vec& hss);
RcppExport SEXP _dynhr_tpf_propagate_particles(SEXP particlesSEXP, SEXP shocksSEXP, SEXP hxSEXP, SEXP huSEXP, SEXP hxxSEXP, SEXP hxuSEXP, SEXP huuSEXP, SEXP hssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hu(huSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hxx(hxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hxu(hxuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type huu(huuSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hss(hssSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_propagate_particles(particles, shocks, hx, hu, hxx, hxu, huu, hss));
    return rcpp_result_gen;
END_RCPP
}
// tpf_run_period_cpp
List tpf_run_period_cpp(arma::mat particles, const arma::vec y_t, const arma::mat L_e, const arma::mat hx, const arma::mat hu, const arma::mat hxx, const arma::mat hxu, const arma::mat huu, const arma::vec hss, const arma::mat ZZ, const arma::mat DD, const arma::vec d_obs, const arma::vec ghss_obs, double me_variance, double ess_target, int n_mh, double mh_scale, int max_stages, Rcpp::Nullable<arma::mat> U_normals, Rcpp::Nullable<double> U_resample, Rcpp::Nullable<arma::vec> U_mid, Rcpp::Nullable<arma::mat> U_mutation);
RcppExport SEXP _dynhr_tpf_run_period_cpp(SEXP particlesSEXP, SEXP y_tSEXP, SEXP L_eSEXP, SEXP hxSEXP, SEXP huSEXP, SEXP hxxSEXP, SEXP hxuSEXP, SEXP huuSEXP, SEXP hssSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP d_obsSEXP, SEXP ghss_obsSEXP, SEXP me_varianceSEXP, SEXP ess_targetSEXP, SEXP n_mhSEXP, SEXP mh_scaleSEXP, SEXP max_stagesSEXP, SEXP U_normalsSEXP, SEXP U_resampleSEXP, SEXP U_midSEXP, SEXP U_mutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_t(y_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type L_e(L_eSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hu(huSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hxx(hxxSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type hxu(hxuSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type huu(huuSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type hss(hssSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ghss_obs(ghss_obsSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type ess_target(ess_targetSEXP);
    Rcpp::traits::input_parameter< int >::type n_mh(n_mhSEXP);
    Rcpp::traits::input_parameter< double >::type mh_scale(mh_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type max_stages(max_stagesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type U_normals(U_normalsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type U_resample(U_resampleSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type U_mid(U_midSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type U_mutation(U_mutationSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_run_period_cpp(particles, y_t, L_e, hx, hu, hxx, hxu, huu, hss, ZZ, DD, d_obs, ghss_obs, me_variance, ess_target, n_mh, mh_scale, max_stages, U_normals, U_resample, U_mid, U_mutation));
    return rcpp_result_gen;
END_RCPP
}
// tpf_log_weights
arma::vec tpf_log_weights(const arma::mat& particles, const arma::vec& y_t, const arma::mat& ZZ, const arma::mat& DD, const arma::mat& shocks, const arma::vec& d_obs, const arma::vec& ghss_obs, double me_variance, double phi);
RcppExport SEXP _dynhr_tpf_log_weights(SEXP particlesSEXP, SEXP y_tSEXP, SEXP ZZSEXP, SEXP DDSEXP, SEXP shocksSEXP, SEXP d_obsSEXP, SEXP ghss_obsSEXP, SEXP me_varianceSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type particles(particlesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_t(y_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shocks(shocksSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ghss_obs(ghss_obsSEXP);
    Rcpp::traits::input_parameter< double >::type me_variance(me_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(tpf_log_weights(particles, y_t, ZZ, DD, shocks, d_obs, ghss_obs, me_variance, phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynhr_fdb_compose_folded_cpp", (DL_FUNC) &_dynhr_fdb_compose_folded_cpp, 5},
    {"_dynhr_eval_jac_tape_cpp", (DL_FUNC) &_dynhr_eval_jac_tape_cpp, 11},
    {"_dynhr_eval_triplet_tape_cpp", (DL_FUNC) &_dynhr_eval_triplet_tape_cpp, 7},
    {"_dynhr_kf_adjoint_cpp", (DL_FUNC) &_dynhr_kf_adjoint_cpp, 17},
    {"_dynhr_kf_adjoint_uni_cpp", (DL_FUNC) &_dynhr_kf_adjoint_uni_cpp, 17},
    {"_dynhr_kalman_ss_loop_cpp", (DL_FUNC) &_dynhr_kalman_ss_loop_cpp, 10},
    {"_dynhr_kalman_standard_loop_cpp", (DL_FUNC) &_dynhr_kalman_standard_loop_cpp, 13},
    {"_dynhr_kalman_univariate_loop_cpp", (DL_FUNC) &_dynhr_kalman_univariate_loop_cpp, 16},
    {"_dynhr_kf_adjoint_diffuse_cpp", (DL_FUNC) &_dynhr_kf_adjoint_diffuse_cpp, 9},
    {"_dynhr_kf_loglik_dG_cpp", (DL_FUNC) &_dynhr_kf_loglik_dG_cpp, 15},
    {"_dynhr_kf_score_sigma_cpp", (DL_FUNC) &_dynhr_kf_score_sigma_cpp, 15},
    {"_dynhr_kf_tangent_cpp", (DL_FUNC) &_dynhr_kf_tangent_cpp, 17},
    {"_dynhr_mcp_sparse_solve_cpp", (DL_FUNC) &_dynhr_mcp_sparse_solve_cpp, 5},
    {"_dynhr_ordered_qz_cpp", (DL_FUNC) &_dynhr_ordered_qz_cpp, 3},
    {"_dynhr_qr_static_transform_cpp", (DL_FUNC) &_dynhr_qr_static_transform_cpp, 5},
    {"_dynhr_tpf_propagate_particles", (DL_FUNC) &_dynhr_tpf_propagate_particles, 8},
    {"_dynhr_tpf_run_period_cpp", (DL_FUNC) &_dynhr_tpf_run_period_cpp, 22},
    {"_dynhr_tpf_log_weights", (DL_FUNC) &_dynhr_tpf_log_weights, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynhr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
