## R/hank-mixture-estimation.R
## --------------------------------------------------------------------------
## Phase-1 Wave-2 (part 2): the STRUCTURAL JOINT estimator for the het-
## preferences-in-HANK research line (brief-17).
##
## Phase-1 Wave-1 (R/hank-reweighting.R, hank_phase1_joint_gate) showed that a
## JOINT objective -- a noisy MACRO aggregate path plus the net cross-section
## REWEIGHTING loss -- can recover both the beta-mixture's centre and spread,
## where either loss alone is degenerate along one grid direction. Its macro
## side used a simple noisy-IRF-path proxy (hank_macro_loss / AC_hat_macro),
## which turned out to be MORE informative about the centre than a real
## macroeconometrician would have: an econometrician does not observe the
## clean impulse-response path AC_star + iid noise at every t of a KNOWN
## shock date/size, they observe a finite TIME SERIES generated by repeated,
## a priori unknown shock realizations, filtered through a Kalman filter that
## must integrate out the shock path itself.
##
## This file replaces that macro proxy with the REALISTIC one: a Kalman
## filter (R/hank-kalman.R's hank_state_space / hank_kalman_loglik) evaluated
## on a synthetic macro TIME SERIES of finite length T_data, simulated from
## the mixture model's own truncated-MA state space. Because a finite series
## carries only finite information about the underlying preference mixture,
## the beta-mixture (centre, spread) is here GENUINELY weakly identified from
## macro data alone -- exactly the setting in which the reweighting side's
## contribution (Phase-0/Phase-1 Wave-1) is expected to show its value, in
## contrast to Wave-1's overly-informative clean-IRF macro proxy.
##
## PIPELINE (per function):
##   hank_mixture_kf_loglik():  eta = (betas, omega) -> mixture steady state
##     (hank_mixture_ks_steady) -> mixture GE model (hank_mixture_ks_model)
##     -> truncated-MA state space (hank_state_space) -> Kalman loglik
##     (hank_kalman_loglik). This is the "structural" macro likelihood: unlike
##     hank_macro_loss's noiseless IRF-moment proxy, it is a genuine Gaussian
##     likelihood over a stochastic time series, integrating over the shock's
##     own realization via the state-space recursion.
##   hank_mixture_simulate():   draws that same synthetic time series from a
##     given mixture model's MA representation (mirrors
##     hank_simulate_aggregate() in R/hank-estimation.R, generalized to the
##     multi-observable / hank_state_space() convention).
##   hank_phase2_recovery():    the (centre, spread) grid-search driver,
##     combining hank_mixture_kf_loglik (macro-alone), hank_reweighting_loss
##     (reweight-alone, reusing Phase-0/1 machinery) and their sum (joint),
##     across a T_data_grid to show how the macro side sharpens as the series
##     lengthens while the reweighting side remains available regardless of
##     T_data (it comes from a snapshot survey pair, not the time series).
## --------------------------------------------------------------------------


#' Structural (Kalman-filter) macro log-likelihood of a beta-mixture HANK model
#'
#' The eta-dependent structural macro log-likelihood at a candidate
#' beta-mixture calibration \code{eta = (betas, omega)}: solves the mixture
#' steady state and GE model at \code{eta}, converts it to a truncated-MA
#' state space, and evaluates dynhr's Gaussian Kalman filter on the observed
#' aggregate time series \code{data}. Unlike \code{\link{hank_macro_loss}}'s
#' noiseless-IRF-moment proxy (Phase-1 Wave-1), this is a genuine Gaussian
#' likelihood over a STOCHASTIC time series of finite length, integrating
#' over the shock's own realization via the state-space recursion -- the
#' "realistic" macro likelihood this Phase-2 wave is built around.
#'
#' \strong{Stochastic singularity}: with \code{length(observables) > 1} but a
#' single exogenous shock (\code{n_obs = 2 > n_shock = 1} for the default
#' \code{observables = c("C","K")}), the model-implied observation covariance
#' is rank-\code{n_shock} and thus singular whenever \code{n_obs > n_shock}.
#' \code{me_variance > 0} is therefore \strong{required} in that regime (as in
#' \code{\link{hank_kalman_loglik}}'s own singularity note) -- it is not
#' optional measurement-error realism here, it is what keeps the observation
#' covariance non-singular so the Gaussian density is well-defined.
#'
#' @param betas Numeric length-K vector of discount factors, one per mixture
#'   type (see \code{\link{hank_mixture_ks_steady}}).
#' @param omega Numeric length-K mixture weights, non-negative, summing to 1.
#' @param data \code{T_data x length(observables)} matrix of demeaned
#'   observations, columns in the order of \code{obs_vars} (as expected by
#'   \code{\link{hank_kalman_loglik}}).
#' @param obs_vars Character vector of observable names produced by the
#'   mixture model (default \code{c("C","K")}).
#' @param shock_specs Named list, one entry per exogenous shock, each
#'   \code{list(rho = <AR(1) persistence>, sigma = <innovation std>)} (see
#'   \code{\link{hank_state_space}}). The Krusell-Smith-style mixture model
#'   built by \code{\link{hank_mixture_ks_model}} has a single exogenous
#'   shock \code{"Z"}, so \code{shock_specs} is typically
#'   \code{list(Z = list(rho = ..., sigma = ...))}.
#' @param a_grid,Pi,e Household asset grid, income transition, income levels
#'   (shared by every mixture type; see \code{\link{hank_mixture_ks_steady}}).
#' @param eis Elasticity of intertemporal substitution, shared across types
#'   (default 1).
#' @param alpha,delta Capital share and depreciation.
#' @param Z Steady-state TFP (default 1).
#' @param T_h Integer GE/impulse-response horizon (see
#'   \code{\link{hank_mixture_ks_model}}, \code{\link{hank_state_space}}).
#' @param q Optional truncation horizon passed to \code{\link{hank_state_space}}
#'   (default \code{T_h}, i.e. no truncation beyond the GE horizon).
#' @param me_variance Measurement-error variance added to every observable's
#'   diagonal in the Kalman filter (see \code{\link{hank_kalman_loglik}}).
#'   \strong{Required to be strictly positive} whenever
#'   \code{length(observables) > 1} for a single-shock model (see Details).
#'
#' @return The scalar Gaussian log-likelihood (higher is better).
#' @seealso \code{\link{hank_mixture_ks_steady}}, \code{\link{hank_mixture_ks_model}},
#'   \code{\link{hank_state_space}}, \code{\link{hank_kalman_loglik}},
#'   \code{\link{hank_mixture_simulate}}, \code{\link{hank_phase2_recovery}}
#' @export
hank_mixture_kf_loglik <- function(betas, omega, data, obs_vars = c("C", "K"),
                                    shock_specs, a_grid, Pi, e, eis = 1,
                                    alpha, delta, Z = 1, T_h, q = NULL,
                                    me_variance) {
  if (length(obs_vars) > length(shock_specs) &&
      (missing(me_variance) || !is.numeric(me_variance) || length(me_variance) != 1L ||
       !is.finite(me_variance) || me_variance <= 0))
    stop("hank_mixture_kf_loglik(): n_obs = ", length(obs_vars),
         " > n_shock = ", length(shock_specs),
         " is stochastically singular; 'me_variance' must be a single strictly ",
         "positive number to keep the observation covariance non-singular.")

  mks   <- hank_mixture_ks_steady(a_grid, Pi, e, betas, omega, eis = eis,
                                   alpha = alpha, delta = delta, Z = Z)
  model <- hank_mixture_ks_model(mks, T_h)
  ss    <- hank_state_space(model, shock_specs, obs_vars, q = q)
  hank_kalman_loglik(data, ss, me_variance = me_variance)
}


#' Simulate a synthetic macro time series from a mixture model's MA state space
#'
#' Draws a synthetic aggregate time series of length \code{T_data} from a
#' \code{\link{hank_model}}'s truncated-MA state space
#' (\code{\link{hank_state_space}}), for use as the "observed" macro data fed
#' to \code{\link{hank_mixture_kf_loglik}} / \code{\link{hank_kalman_loglik}}.
#'
#' Simulates directly off the MA representation (the same construction as
#' \code{\link{hank_simulate_aggregate}} in R/hank-estimation.R, generalized
#' to \code{\link{hank_state_space}}'s multi-shock / multi-observable
#' convention): for each exogenous shock, innovations
#' \eqn{\epsilon_t \sim N(0, \sigma^2)} are drawn independently for
#' \code{t = 1, ..., T_data}, and
#' \deqn{y_{o,t} = \Sigma_{s=0}^{q-1} \Theta_{shock}[s+1, o]\, \epsilon_{t-s} + N(0, me\_var),}
#' treating \eqn{\epsilon_{t-s} = 0} for \code{t - s < 1} (the process starts
#' from rest -- no pre-sample shock history), matching this exactly is what
#' keeps the simulated data on the SAME law that
#' \code{\link{hank_kalman_loglik}} evaluates (avoids any timing mismatch
#' between simulation and likelihood).
#'
#' The returned series is \strong{demeaned} (its own column means are
#' subtracted), because \code{\link{hank_kalman_loglik}} (via
#' \code{\link{hank_state_space}}'s zero-mean state-space form) expects
#' demeaned observations. Since the underlying process is already a
#' zero-mean deviation-from-steady-state law, this demeaning only removes
#' finite-sample Monte Carlo noise in the sample mean -- it does not change
#' the population data-generating process.
#'
#' @param model A \code{\link{hank_model}} (e.g. \code{\link{hank_mixture_ks_model}}'s
#'   output).
#' @param shock_specs Named list, one entry per \code{model$exogenous} shock
#'   (see \code{\link{hank_state_space}}).
#' @param obs_vars Character vector of observable names (default
#'   \code{c("C","K")}).
#' @param T_data Integer: length of the simulated series.
#' @param me_variance Measurement-error variance added to every observable
#'   (independently at every date); use \code{0} for a noiseless simulation.
#' @param seed Optional RNG seed (via \code{set.seed()}) for reproducibility;
#'   if \code{NULL}, the caller's current RNG stream is used unmodified.
#' @param q Optional truncation horizon passed to \code{\link{hank_state_space}}
#'   (default \code{model$T_h}).
#'
#' @return A \code{T_data x length(observables)} numeric matrix (columns named
#'   by \code{obs_vars}), demeaned (see Details), finite, and reproducible
#'   given the same \code{seed}.
#' @seealso \code{\link{hank_state_space}}, \code{\link{hank_mixture_kf_loglik}},
#'   \code{\link{hank_simulate_aggregate}}
#' @export
hank_mixture_simulate <- function(model, shock_specs, obs_vars = c("C", "K"),
                                   T_data, me_variance, seed = NULL, q = NULL) {
  if (!is.null(seed)) set.seed(seed)
  ss <- hank_state_space(model, shock_specs, obs_vars, q = q)
  n_obs   <- length(obs_vars)
  exo     <- ss$shock_names
  T_h_reg <- nrow(ss$Theta_list[[1L]])          # q (rows of each Theta block)

  Y <- matrix(0, T_data, n_obs)
  for (z in exo) {
    sigma_z <- shock_specs[[z]]$sigma
    eps <- stats::rnorm(T_data, 0, sigma_z)
    Theta <- ss$Theta_list[[z]]                 # T_h x n_obs (see hank_state_space)
    for (t in seq_len(T_data)) {
      s <- 0:min(t - 1L, T_h_reg - 1L)          # Theta_s eps_{t-s}, eps_{<1} = 0
      Y[t, ] <- Y[t, ] + colSums(Theta[s + 1L, , drop = FALSE] * eps[t - s])
    }
  }
  if (me_variance > 0)
    Y <- Y + matrix(stats::rnorm(T_data * n_obs, 0, sqrt(me_variance)), T_data, n_obs)

  Y <- scale(Y, center = TRUE, scale = FALSE)   # demean (see Details)
  attr(Y, "scaled:center") <- NULL
  matrix(Y, T_data, n_obs, dimnames = list(NULL, obs_vars))
}


## --------------------------------------------------------------------------
## Phase-2: structural joint (macro-KF + reweighting) recovery driver.
## --------------------------------------------------------------------------


#' Phase-2 structural joint (macro-KF + reweighting) recovery driver
#'
#' The Phase-2 companion to \code{\link{hank_phase1_joint_gate}}: replaces
#' Wave-1's noiseless clean-IRF-path macro proxy
#' (\code{\link{hank_macro_loss}}) with the REALISTIC structural macro
#' likelihood -- a Kalman filter (\code{\link{hank_mixture_kf_loglik}}) on a
#' synthetic macro time series of finite length \code{T_data}
#' (\code{\link{hank_mixture_simulate}}) -- while reusing the IDENTICAL
#' reweighting-side construction (\code{\link{.hank_phase0_survey}},
#' \code{\link{hank_reweight_metric}}, \code{\link{hank_reweighting_loss}}) as
#' Phase-0/Phase-1. For each \code{T_data} in \code{T_data_grid} it: (a)
#' builds the TRUTH mixture model and simulates a macro series of that
#' length; (b) generates the synthetic survey net-reweighting \code{dD_hat}
#' and its proper GLS metric \code{W}; (c) scores a \code{(centre, spread)}
#' grid of candidate mixtures against three objectives --
#' \code{rho_KF = -hank_mixture_kf_loglik(...)} (macro-alone, as a LOSS: the
#' Kalman filter returns a log-LIKELIHOOD, higher is better, so it is
#' NEGATED here to match the loss convention that lower is better, shared by
#' the other two surfaces), \code{rho_rw = hank_reweighting_loss(...)}
#' (reweight-alone), and \code{joint = rho_KF + lambda * rho_rw}.
#'
#' This function performs the MECHANICS only, mirroring
#' \code{\link{hank_phase0_reweight_gate}} / \code{\link{hank_phase1_joint_gate}}'s
#' convention: it returns the raw grids and per-\code{T_data} argmins without
#' computing or asserting any verdict on whether macro, reweighting, or the
#' joint objective "recovers" the truth -- that judgment is left to the
#' caller/orchestrator.
#'
#' \strong{Measurement-error choice}: for each simulated \code{T_data} series,
#' \code{me_variance} is set to \code{(me_frac * sd(column))^2} PER OBSERVABLE
#' COLUMN of that simulated series (i.e. a fixed fraction of the realized
#' series' own variation, analogous to \code{hank_phase1_joint_gate}'s
#' \code{sigma_macro_frac} convention) -- a simple scale-invariant way to
#' inject "the macro series is observed with some noise" without hand-picking
#' absolute noise units per observable. Because
#' \code{\link{hank_kalman_loglik}}/\code{\link{hank_mixture_kf_loglik}} take
#' a single scalar \code{me_variance} (one measurement-error variance shared
#' across observables, not a per-observable vector), the LARGER of the two
#' per-observable \code{me_variance} values is used, so the shared scalar is never
#' smaller than what either observable's own noise fraction would imply
#' (conservative: avoids an under-dispersed, potentially singular effective
#' covariance for the noisier observable).
#'
#' \strong{Truth parameterization} (as in
#' \code{\link{hank_phase0_reweight_gate}}): with \code{centre* = mean(betas)}
#' and \code{spread* = diff(betas)/2}, keep \code{centre_grid + spread_grid <
#' 1} (i.e. every candidate \code{beta = centre -+ spread < 1}) to avoid EGM
#' non-convergence at/above the discounting boundary.
#'
#' @param betas Length-2 truth discount factors; \code{centre* = mean(betas)},
#'   \code{spread* = diff(betas)/2}.
#' @param omega Length-2 truth mixture weights (non-negative, sum to 1).
#' @param n_e,n_a,amax Household grid size/extent (shared truth + candidate).
#' @param alpha,delta Capital share and depreciation.
#' @param Z Steady-state TFP (default 1).
#' @param T_h Integer GE/impulse-response horizon (shared by the macro-KF
#'   state space and the reweighting Jacobians).
#' @param shock_spec List \code{list(rho, sigma)}: the AR(1) TFP shock driving
#'   the macro-KF side (the mixture model's single exogenous shock \code{"Z"};
#'   see \code{\link{hank_mixture_ks_model}}).
#' @param me_frac Fraction of each simulated series' own column standard
#'   deviation used to set the Kalman filter's measurement-error variance
#'   (see Details).
#' @param N_survey Sample size drawn for EACH synthetic survey (pre- and
#'   post-shock; passed to \code{\link{.hank_phase0_survey}}).
#' @param T_data_grid Integer vector: the macro time-series lengths to sweep.
#' @param centre_grid,spread_grid Numeric vectors: the grid of candidate
#'   \code{centre}/\code{spread} mixture calibrations to score (kept
#'   \code{centre + spread < 1}; see Details).
#' @param lambda Non-negative scalar weight on the reweighting loss in the
#'   joint objective \code{joint = rho_KF + lambda * rho_rw}.
#' @param seed RNG seed for the synthetic sampling (macro series simulation,
#'   survey draws, and design weights).
#'
#' @return A list with:
#'   \item{T_data_grid}{As passed in.}
#'   \item{centre_grid,spread_grid}{The grids as passed in.}
#'   \item{truth}{\code{list(centre, spread)} at the truth calibration.}
#'   \item{per_T}{A list, one entry per \code{T_data_grid} value, each a list
#'     with \code{T_data}, the three grid surfaces \code{rho_KF, rho_rw,
#'     joint} (each \code{length(centre_grid) x length(spread_grid)}), and
#'     \code{argmin_KF, argmin_rw, argmin_joint} (each
#'     \code{list(centre, spread)} at that surface's grid argmin).}
#' @seealso \code{\link{hank_mixture_kf_loglik}}, \code{\link{hank_mixture_simulate}},
#'   \code{\link{hank_phase1_joint_gate}}, \code{\link{hank_reweighting_loss}}
#' @keywords internal
#' @export
hank_phase2_recovery <- function(betas = c(0.95, 0.98), omega = c(0.5, 0.5),
                                  n_e = 3L, n_a = 50L, amax = 60,
                                  alpha = 0.36, delta = 0.025, Z = 1,
                                  T_h = 20L,
                                  shock_spec = list(rho = 0.9, sigma = 0.007),
                                  me_frac = 0.1, N_survey = 5000L,
                                  T_data_grid = c(100L, 200L, 400L),
                                  centre_grid, spread_grid,
                                  lambda = 1, seed = 1L) {
  if (length(betas) != 2L) stop("hank_phase2_recovery(): 'betas' must have length 2.")
  if (!is.numeric(lambda) || length(lambda) != 1L || !is.finite(lambda) || lambda < 0)
    stop("hank_phase2_recovery(): 'lambda' must be a single non-negative finite number.")
  set.seed(seed)

  inc <- hank_income_rouwenhorst(rho = 0.9, sigma = 0.7, n = n_e)
  ag  <- hank_asset_grid(amax = amax, n = n_a, amin = 0)
  observables  <- c("C", "K")
  shock_specs  <- list(Z = list(rho = shock_spec$rho, sigma = shock_spec$sigma))

  ## ---- TRUTH mixture (shared reweighting side, Phase-0/1 machinery) -----
  centre_star <- mean(betas); spread_star <- diff(betas) / 2
  mks_truth   <- hank_mixture_ks_steady(ag, inc$Pi, inc$e, betas, omega,
                                         eis = 1, alpha = alpha, delta = delta, Z = Z)
  model_truth <- hank_mixture_ks_model(mks_truth, T_h)

  ## Reweighting shock: a price/interest impulse, as in Phase-0/1 (kept at
  ## the Phase-1 default so the reweighting side is numerically identical to
  ## the earlier waves' construction -- only the macro side is new here).
  rw_shock <- list(r = 0.01 * 0.8^(seq_len(T_h) - 1L))
  sv <- .hank_phase0_survey(ag, inc, betas, omega, eis = 1, r = mks_truth$r, w = mks_truth$w,
                             T_h = T_h, shock = rw_shock, N = N_survey)
  W_rw <- hank_reweight_metric(sv$D0, sv$D1, N = N_survey)$W

  argmin_idx <- function(M) {
    idx <- which(M == min(M), arr.ind = TRUE)[1L, ]
    list(centre = centre_grid[idx[1L]], spread = spread_grid[idx[2L]])
  }

  n_c <- length(centre_grid); n_s <- length(spread_grid)
  per_T <- vector("list", length(T_data_grid))
  names(per_T) <- paste0("T_data_", T_data_grid)

  for (Ti in seq_along(T_data_grid)) {
    T_data <- T_data_grid[Ti]

    ## ---- (a) simulate a macro series from the TRUTH model ---------------
    Y_sim <- hank_mixture_simulate(model_truth, shock_specs, observables,
                                    T_data = T_data, me_variance = 0, seed = NULL)
    me_var_col <- (me_frac * apply(Y_sim, 2, stats::sd))^2
    me_var_T   <- max(me_var_col)             # shared-scalar convention (see Details)
    Y_obs <- Y_sim + matrix(stats::rnorm(T_data * length(observables), 0,
                                          sqrt(me_var_T)),
                             T_data, length(observables))
    Y_obs <- scale(Y_obs, center = TRUE, scale = FALSE)
    attr(Y_obs, "scaled:center") <- NULL
    Y_obs <- matrix(Y_obs, T_data, length(observables), dimnames = list(NULL, observables))

    ## ---- (c) grid of candidate (centre, spread) mixtures -----------------
    rho_KF_mat  <- matrix(NA_real_, n_c, n_s)
    rho_rw_mat  <- matrix(NA_real_, n_c, n_s)
    joint_mat   <- matrix(NA_real_, n_c, n_s)

    for (ci in seq_len(n_c)) for (si in seq_len(n_s)) {
      cc <- centre_grid[ci]; ss <- spread_grid[si]
      betas_cand <- c(cc - ss, cc + ss)

      ll <- hank_mixture_kf_loglik(betas_cand, omega, Y_obs, obs_vars = observables,
                                    shock_specs = shock_specs, a_grid = ag, Pi = inc$Pi,
                                    e = inc$e, eis = 1, alpha = alpha, delta = delta, Z = Z,
                                    T_h = T_h, me_variance = me_var_T)
      rho_KF_mat[ci, si] <- -ll                # negate: loglik (higher=better) -> loss

      blocks_cand <- hank_mixture_blocks(ag, inc$Pi, inc$e, betas = betas_cand,
                                          eis = 1, r = mks_truth$r, w = mks_truth$w)
      JD_cand <- hank_mixture_dist_jacobian(blocks_cand, omega, T_h, inputs = names(rw_shock))
      loss_rw <- hank_reweighting_loss(sv$dD_hat, JD_cand, rw_shock, W = W_rw)
      rho_rw_mat[ci, si] <- loss_rw$rho

      joint_mat[ci, si] <- rho_KF_mat[ci, si] + lambda * rho_rw_mat[ci, si]
    }

    per_T[[Ti]] <- list(T_data = T_data,
                         rho_KF = rho_KF_mat, rho_rw = rho_rw_mat, joint = joint_mat,
                         argmin_KF    = argmin_idx(rho_KF_mat),
                         argmin_rw    = argmin_idx(rho_rw_mat),
                         argmin_joint = argmin_idx(joint_mat))
  }

  list(T_data_grid = T_data_grid, centre_grid = centre_grid, spread_grid = spread_grid,
       truth = list(centre = centre_star, spread = spread_star),
       per_T = per_T)
}


## --------------------------------------------------------------------------
## Wave-3: joint macro-KF + single-snapshot-reweighting log-posterior, as
## tested package API (promotes the het-preferences estimator's core object).
## --------------------------------------------------------------------------


#' Joint macro-KF + LEVEL + single-snapshot-reweighting log-posterior for a
#' beta-mixture
#'
#' @section Recommended posterior route (read before hand-rolling a sampler):
#' The \code{(centre, spread)} posterior is a TILTED, strongly ANISOTROPIC
#' ridge -- the coordinates are highly correlated and the per-channel Fisher
#' informations differ by orders of magnitude (LEVEL identifies \code{spread}
#' with Fisher \eqn{\sim 10^7}; macro identifies \code{centre} with Fisher
#' \eqn{\sim 10^4}; the price-shock RESPONSE channel is nearly flat). A
#' DIAGONAL-metric random-walk Metropolis fails on this geometry. Use one of
#' the two supported routes instead: (i) the exact evaluation GRID via
#' \code{\link{hank_mixture_emulator}} + \code{\link{hank_mixture_sbc}}
#' (\code{sampler = "grid"} is the only implemented SBC sampler, for exactly
#' this reason), or (ii) a CURVATURE-AWARE proposal from
#' \code{\link{hank_mixture_laplace}} (mode + Laplace covariance of THIS
#' log-posterior) to seed / scale a tilted-ridge or independence sampler.
#'
#' The het-preferences-in-HANK estimator's core object: the JOINT
#' log-posterior of a 2-type discount-factor mixture over up to THREE
#' composable, all-optional observable channels, each evaluated over ONE
#' shared mixture general-equilibrium steady state
#' (\code{\link{hank_mixture_ks_steady}}) at the candidate calibration:
#' \describe{
#'   \item{macro}{the structural macro Kalman-filter log-likelihood
#'     (\code{\link{hank_mixture_kf_loglik}}) on an observed aggregate time
#'     series \code{data}; active iff \code{data} is supplied.}
#'   \item{level}{the grid-invariant functional LEVEL log-likelihood
#'     (\code{\link{hank_reweight_functional_loss}} against
#'     \code{\link{hank_reweight_level_metric}}) of a SINGLE stationary
#'     wealth cross-section survey \code{m_lev_hat} against the candidate's
#'     stationary distribution \code{D0}; active iff \code{m_lev_hat} is
#'     supplied.}
#'   \item{response}{the grid-invariant functional REWEIGHTING log-likelihood
#'     (\code{\link{hank_reweight_functional_loss}}) of a SINGLE post-shock
#'     cross-section snapshot (\code{\link{hank_dist_response_snapshot}})
#'     against an observed net reweighting \code{dD_hat}; active iff both
#'     \code{dD_hat} and \code{metric} are supplied.}
#' }
#' At least one channel must be active.
#'
#' \strong{The LEVEL channel is the corrected identifier of the mixture
#' spread}: the discount-factor SPREAD is identified by the stationary
#' wealth-distribution LEVEL (how differently the two types' stationary
#' asset holdings are distributed), not by the price-shock reweighting
#' RESPONSE (which differences out most of that level signal at a realistic
#' survey size and shock, and is nearly inert about the spread -- see the
#' file section comment above and the LEVEL cross-section observable's
#' certification log). The macro block remains informative about the
#' \code{centre} (the average discount factor governs the aggregate
#' capital/consumption response to a TFP shock). The response channel is
#' kept for completeness/backward compatibility (the original Wave-3
#' construction) but is not, on its own, an effective spread identifier.
#'
#' The return value keeps \code{loglik} (the data-driven log-likelihood
#' alone) separate from \code{logpost} (which additionally folds in
#' \code{log_prior}): this avoids the "\code{$loglik} footgun" where a
#' sampler mistakenly reads a prior-contaminated scalar as a pure
#' likelihood (e.g. for a likelihood-ratio diagnostic, an SBC rank statistic,
#' or a nested annealing/tempering scheme that must apply its own
#' temperature to the likelihood only) -- a caller wanting a Bayesian
#' posterior for MCMC should use \code{logpost}; a caller building its own
#' prior/temperature externally, or auditing the likelihood in isolation,
#' should use \code{loglik} (further decomposed into \code{loglik_macro},
#' \code{loglik_rw} and \code{loglik_level} for diagnosing which block is
#' driving the result).
#'
#' @param theta A list with \code{$centre} (the mixture's mean discount
#'   factor) and \code{$spread} (half the gap between the two types' discount
#'   factors, so \code{betas = c(centre - spread, centre + spread)}); may
#'   optionally include \code{$omega} (length-2 mixture weights), in which
#'   case it OVERRIDES \code{config$omega} for this evaluation (e.g. when a
#'   sampler is also exploring the mixture weight); if \code{theta$omega} is
#'   \code{NULL}, \code{config$omega} is used.
#' @param data \code{T_data x length(config$observables)} matrix of demeaned
#'   macro observations, as expected by \code{\link{hank_mixture_kf_loglik}}
#'   / \code{\link{hank_kalman_loglik}}; \code{NULL} (default) disables the
#'   macro channel.
#' @param dD_hat Observed net reweighting, a length-\code{n_cell} numeric
#'   vector (e.g. \code{Dhat1 - Dhat0} of two independently-sampled survey
#'   cross-sections, pre- and post-shock; see
#'   \code{\link{hank_reweight_functional_loss}}); \code{NULL} (default)
#'   disables the response channel (together with \code{metric}).
#' @param metric A metric object from
#'   \code{\link{hank_reweight_functional_metric}} (built once from a
#'   reference \code{(D0, D1)} pair and reused across candidate mixtures);
#'   \code{NULL} (default) disables the response channel (together with
#'   \code{dD_hat}).
#' @param config A list of items shared across every evaluation of this
#'   log-posterior (typically fixed for a whole sampler run), with:
#'   \describe{
#'     \item{\code{a_grid, Pi, e}}{Household asset grid, income transition,
#'       income levels, shared across mixture types (see
#'       \code{\link{hank_mixture_ks_steady}}).}
#'     \item{\code{eis}}{Elasticity of intertemporal substitution, shared
#'       across types.}
#'     \item{\code{alpha, delta}}{Capital share and depreciation.}
#'     \item{\code{Z}}{Steady-state TFP.}
#'     \item{\code{T_h}}{Integer GE/impulse-response horizon (shared by the
#'       macro state space and the reweighting Jacobians); only required when
#'       the macro or response channel is active.}
#'     \item{\code{observables}}{Character vector of observable names for the
#'       macro block (see \code{\link{hank_mixture_kf_loglik}}); only required
#'       when the macro channel is active.}
#'     \item{\code{shock_specs}}{Named list, one entry per exogenous macro
#'       shock, each \code{list(rho, sigma)} (see
#'       \code{\link{hank_state_space}}); only required when the macro
#'       channel is active.}
#'     \item{\code{me_var}}{Macro measurement-error variance (see
#'       \code{\link{hank_kalman_loglik}}); only required when the macro
#'       channel is active.}
#'     \item{\code{rw_shock}}{Named list, one length-\code{T_h} shock path per
#'       reweighting input (see \code{\link{hank_dist_response_snapshot}}'s
#'       \code{dZ}); only required when the response channel is active.}
#'     \item{\code{t_star}}{Integer output date in \code{1..T_h} at which the
#'       single reweighting snapshot is taken (see
#'       \code{\link{hank_dist_response_snapshot}}); only required when the
#'       response channel is active.}
#'     \item{\code{rw_scale}}{Scalar multiplier applied to the snapshot
#'       response before scoring against \code{dD_hat} (the size of the
#'       reweighting-side shock); only required when the response channel is
#'       active.}
#'     \item{\code{omega}}{Default length-2 mixture weights, used whenever
#'       \code{theta$omega} is \code{NULL}.}
#'     \item{\code{q}}{Optional truncation horizon passed to
#'       \code{\link{hank_state_space}} (default \code{T_h} if absent/\code{NULL});
#'       only relevant when the macro channel is active.}
#'   }
#' @param m_lev_hat Observed LEVEL survey: a length-\code{ncol(level_metric$B)}
#'   numeric vector, the projection \code{t(B) Dhat} of a SINGLE size-\code{N}
#'   multinomial cross-section \code{Dhat} drawn from a stationary wealth
#'   distribution (see \code{\link{hank_reweight_level_metric}}); \code{NULL}
#'   (default) disables the level channel.
#' @param level_metric A metric object from
#'   \code{\link{hank_reweight_level_metric}} (built once from a reference
#'   stationary distribution and reused across candidate mixtures); required
#'   whenever \code{m_lev_hat} is supplied (an error is raised otherwise).
#' @param log_prior Optional function of \code{theta} returning a single
#'   scalar log-prior density; if \code{NULL} (the default), the log-prior is
#'   taken to be \code{0} (i.e. \code{logpost == loglik}).
#'
#' @return A list with:
#'   \item{logpost}{\code{loglik + logprior} (the quantity an MCMC sampler
#'     should target).}
#'   \item{loglik}{\code{loglik_macro + loglik_rw + loglik_level}, the data
#'     log-likelihood WITHOUT the prior (see Details for why this is kept
#'     separate); inactive channels contribute \code{0}.}
#'   \item{loglik_macro}{The structural Kalman-filter macro log-likelihood
#'     alone (\code{\link{hank_mixture_kf_loglik}}'s value at this
#'     \code{theta}), or \code{0} if the macro channel is inactive.}
#'   \item{loglik_rw}{The reweighting (response) log-likelihood alone,
#'     \code{-0.5 * hank_reweight_functional_loss(dD_hat, dD_mod, metric)$rho}
#'     at the date-\code{t_star} snapshot of this \code{theta}'s
#'     distribution-Jacobian response, or \code{0} if the response channel is
#'     inactive.}
#'   \item{loglik_level}{The LEVEL log-likelihood alone,
#'     \code{-0.5 * hank_reweight_functional_loss(m_lev_hat, D0, level_metric)$rho}
#'     at this \code{theta}'s stationary distribution \code{D0}, or \code{0}
#'     if the level channel is inactive.}
#'   \item{logprior}{\code{log_prior(theta)}, or \code{0} if \code{log_prior}
#'     is \code{NULL}.}
#' @seealso \code{\link{hank_mixture_kf_loglik}}, \code{\link{hank_reweight_functional_loss}},
#'   \code{\link{hank_reweight_level_metric}}, \code{\link{hank_dist_response_snapshot}},
#'   \code{\link{hank_mixture_dist_jacobian}}, \code{\link{hank_reweight_functional_metric}}
#' @export
hank_mixture_joint_logpost <- function(theta, data = NULL, dD_hat = NULL, metric = NULL,
                                       config, m_lev_hat = NULL, level_metric = NULL,
                                       log_prior = NULL) {
  use_macro <- !is.null(data)
  use_resp  <- !is.null(dD_hat) && !is.null(metric)
  use_level <- !is.null(m_lev_hat)
  if (use_level && is.null(level_metric))
    stop("hank_mixture_joint_logpost(): 'm_lev_hat' was supplied without 'level_metric'; ",
         "the level channel requires a hank_reweight_level_metric() object.")
  if (!use_macro && !use_resp && !use_level)
    stop("hank_mixture_joint_logpost(): no channel is active -- supply at least one of ",
         "'Y' (macro), 'm_lev_hat' (level), or 'dD_hat'+'metric' (response).")

  centre <- theta$centre; spread <- theta$spread
  omega  <- if (!is.null(theta$omega)) theta$omega else config$omega
  betas  <- c(centre - spread, centre + spread)

  ## ---- one shared mixture GE steady state (needed by macro, and to get
  ## r, w for level/response) ----
  mks <- hank_mixture_ks_steady(config$a_grid, config$Pi, config$e, betas, omega,
                                eis = config$eis, alpha = config$alpha,
                                delta = config$delta, Z = config$Z)

  ## ---- macro: truncated-MA state space + Kalman filter ----
  loglik_macro <- 0
  if (use_macro) {
    ss <- hank_state_space(hank_mixture_ks_model(mks, config$T_h),
                           config$shock_specs, config$observables, q = config$q)
    loglik_macro <- hank_kalman_loglik(data, ss, me_variance = config$me_var)
  }

  ## ---- one shared set of per-type blocks (needed by EITHER level or
  ## response -- reused for both) ----
  loglik_rw <- 0
  loglik_level <- 0
  if (use_level || use_resp) {
    b <- hank_mixture_blocks(config$a_grid, config$Pi, config$e, betas = betas,
                             eis = config$eis, r = mks$r, w = mks$w)

    ## ---- response: single post-shock cross-section snapshot reweighting ----
    if (use_resp) {
      JD <- hank_mixture_dist_jacobian(b, omega, config$T_h, inputs = "r")
      dD_mod <- config$rw_scale *
        hank_dist_response_snapshot(JD, config$rw_shock, config$t_star)
      loglik_rw <- -0.5 * hank_reweight_functional_loss(dD_hat, dD_mod, metric)$rho
    }

    ## ---- level: single stationary cross-section survey ----
    if (use_level) {
      D0 <- hank_mixture_dist(b, omega)$D
      loglik_level <- -0.5 * hank_reweight_functional_loss(m_lev_hat, D0, level_metric)$rho
    }
  }

  ## ---- prior + assemble (loglik kept separate from logpost) ----
  logprior <- if (is.null(log_prior)) 0 else log_prior(theta)
  loglik   <- loglik_macro + loglik_rw + loglik_level
  list(logpost = loglik + logprior, loglik = loglik,
       loglik_macro = loglik_macro, loglik_rw = loglik_rw, loglik_level = loglik_level,
       logprior = logprior)
}


#' Laplace (mode + curvature) proposal for the HANK-mixture joint posterior
#'
#' Finds the posterior mode of \code{\link{hank_mixture_joint_logpost}} over the
#' free scalar coordinates (\code{centre}, \code{spread}, and optionally the
#' first mixture weight \code{omega1}), computes the observed information
#' \eqn{-\nabla^2 \log p} there by a central finite difference, and returns the
#' Laplace covariance \eqn{(-\nabla^2 \log p)^{-1}} together with a Gaussian
#' proposal sampler.
#'
#' \strong{Why this exists.} The mixture posterior on \code{(centre, spread)} is
#' a strongly TILTED, ANISOTROPIC RIDGE: the two coordinates are highly
#' correlated and the channel Fisher informations differ by orders of magnitude
#' (the stationary-wealth LEVEL channel identifies the spread with Fisher
#' \eqn{\sim 10^7}, the macro channel identifies the centre with Fisher
#' \eqn{\sim 10^4}, the price-shock RESPONSE channel is nearly flat). A
#' DIAGONAL-metric random-walk Metropolis fails badly on this geometry (it
#' cannot climb the ridge and degenerates). The two routes that work are
#' (i) the exact evaluation GRID via \code{\link{hank_mixture_emulator}} +
#' \code{\link{hank_mixture_sbc}} (\code{sampler = "grid"} is the only supported
#' SBC sampler for exactly this reason), and (ii) a CURVATURE-AWARE proposal:
#' this function's Laplace covariance is the correlated metric a tilted-ridge
#' random-walk / independence proposal needs, and it is exact to \eqn{O(1/T)} at
#' the mode -- no pilot run, no importance-sampling degeneracy, no grid. Use it
#' to seed / scale a sampler or as an importance proposal; the exact grid
#' remains the gold standard for the final posterior when the ridge is
#' materially non-Gaussian.
#'
#' @param theta0 A named list giving the STARTING point and the FIXED values of
#'   any coordinate not in \code{par_names}: \code{$centre}, \code{$spread}, and
#'   (optionally) \code{$omega} (length-2 mixture weights). Same shape as the
#'   \code{theta} argument of \code{\link{hank_mixture_joint_logpost}}.
#' @param config,data,dD_hat,metric,m_lev_hat,level_metric,log_prior Passed through
#'   verbatim to \code{\link{hank_mixture_joint_logpost}} on every evaluation;
#'   supply the same channel arguments you intend to sample under (at least one
#'   of \code{data}, \code{m_lev_hat}, or \code{dD_hat}+\code{metric}).
#' @param par_names Character subset of \code{c("centre", "spread", "omega1")}
#'   giving the FREE coordinates (default \code{c("centre", "spread")}).
#'   \code{"omega1"} maps to \code{theta$omega = c(omega1, 1 - omega1)}.
#' @param method,lower,upper Passed to \code{\link[stats]{optim}} for the
#'   mode-find (default \code{"Nelder-Mead"}, unconstrained; pass box bounds
#'   with \code{method = "L-BFGS-B"} to constrain, e.g. \code{spread > 0}).
#' @param h_rel Relative central-FD step for the mode Hessian (default 2e-3;
#'   the step for coordinate \code{k} is \code{h_rel * max(abs(mode_k), 1e-4)}).
#'   This is DELIBERATELY LARGER than a textbook \code{~1e-5} Hessian step: the
#'   log-posterior is a general-equilibrium (uniroot market-clearing) solve, so
#'   it is smooth only down to the clearing tolerance, and a second difference
#'   (which divides by \code{h^2}) at a tiny step is swamped by that
#'   non-smoothness -- catastrophically in a TIGHT direction. Empirically the FD
#'   curvature converges as \code{h} grows: at \code{h_rel = 1e-4} a
#'   sharply-identified coordinate (e.g. \code{spread} under the LEVEL channel)
#'   can be over-curved by \code{~8x}; it is within a few percent of the true
#'   marginal by \code{h_rel = 2e-3}--\code{3e-3}. INCREASE \code{h_rel} if the
#'   tightest-direction \code{sd} looks under-estimated (Hessian noise-dominated);
#'   DECREASE it if a probe walks off the GE-solvable region (\code{cov = NULL}).
#' @param optim_control Extra \code{control} list merged into
#'   \code{list(fnscale = -1, reltol = 1e-10)} (the negative \code{fnscale}
#'   makes \code{optim} MAXIMISE the log-posterior).
#'
#' @return A list with \item{mode}{named numeric, the posterior mode over
#'   \code{par_names}.} \item{logpost}{log-posterior at the mode.}
#'   \item{hessian}{FD Hessian of the LOG-POSTERIOR at the mode (negative
#'     definite at a maximum).} \item{information}{\code{-hessian}, the observed
#'     information (should be positive definite).} \item{cov}{Laplace covariance
#'     \code{solve(information)}, or \code{NULL} with a warning if the
#'     information is not positive definite (mode not a strict max / a coordinate
#'     unidentified by the active channels).} \item{sd}{\code{sqrt(diag(cov))}.}
#'   \item{propose}{\code{function(n)} drawing \code{n} rows from
#'     \code{MVN(mode, cov)} (a matrix with columns \code{par_names}); errors if
#'     \code{cov} is \code{NULL}.} \item{to_theta}{\code{function(v)} mapping a
#'     named \code{par_names} vector back to the list-\code{theta} that
#'     \code{hank_mixture_joint_logpost} consumes (fixed coordinates from
#'     \code{theta0}).} \item{par_names, converged}{bookkeeping.}
#' @seealso \code{\link{hank_mixture_joint_logpost}},
#'   \code{\link{hank_mixture_emulator}}, \code{\link{hank_mixture_sbc}}
#' @export
hank_mixture_laplace <- function(theta0, config,
                                 data = NULL, dD_hat = NULL, metric = NULL,
                                 m_lev_hat = NULL, level_metric = NULL,
                                 log_prior = NULL,
                                 par_names = c("centre", "spread"),
                                 method = "Nelder-Mead",
                                 lower = -Inf, upper = Inf,
                                 h_rel = 2e-3,
                                 optim_control = list()) {

  par_names <- match.arg(par_names, c("centre", "spread", "omega1"),
                         several.ok = TRUE)
  if ("omega1" %in% par_names &&
      (is.null(theta0$omega) || length(theta0$omega) != 2L))
    stop("hank_mixture_laplace(): par_names includes 'omega1' but theta0$omega ",
         "is not a length-2 weight vector.")

  ## flat par vector -> list-theta (fixed coords come from theta0)
  to_theta <- function(v) {
    th <- theta0
    if ("centre" %in% names(v)) th$centre <- v[["centre"]]
    if ("spread" %in% names(v)) th$spread <- v[["spread"]]
    if ("omega1" %in% names(v)) th$omega  <- c(v[["omega1"]], 1 - v[["omega1"]])
    th
  }

  ## objective: the log-posterior as a function of the flat par vector.
  ## Infeasible / non-finite draws are penalised so the optimiser and the FD
  ## stencil stay inside the well-defined region.
  ## Objective evaluations during the mode-search and FD stencil routinely probe
  ## points where a type's household EGM / market-clearing solve does not
  ## converge (expected: the optimiser explores, the FD stencil steps out); such
  ## a probe returns the penalty and the search moves on, so its GE-solve
  ## warnings are noise here and are suppressed. The returned mode/cov are
  ## validated separately (PD information + `converged`).
  neg_inf_pen <- -1e18
  f <- function(v) {
    vv <- setNames(as.numeric(v), par_names)
    r <- tryCatch(
      suppressWarnings(
        hank_mixture_joint_logpost(to_theta(vv), data = data, dD_hat = dD_hat,
                                   metric = metric, config = config,
                                   m_lev_hat = m_lev_hat,
                                   level_metric = level_metric,
                                   log_prior = log_prior)),
      error = function(e) NULL)
    if (is.null(r) || !is.finite(r$logpost)) return(neg_inf_pen)
    r$logpost
  }

  v0 <- vapply(par_names, function(nm)
    if (nm == "omega1") theta0$omega[1L] else theta0[[nm]], numeric(1))
  names(v0) <- par_names

  ctrl <- utils::modifyList(list(fnscale = -1, reltol = 1e-10), optim_control)
  opt <- stats::optim(v0, f, method = method, lower = lower, upper = upper,
                      control = ctrl)
  mode <- setNames(opt$par, par_names)

  ## central-FD Hessian of the log-posterior at the mode (3-point diagonal,
  ## 4-corner mixed) -- small (<= 3 coords), so O(p^2) forward evals is cheap.
  p  <- length(par_names)
  hs <- h_rel * pmax(abs(mode), 1e-4)
  f0 <- f(mode)
  H  <- matrix(0, p, p, dimnames = list(par_names, par_names))
  fe <- function(delta) f(mode + delta)
  for (i in seq_len(p)) {
    ei <- numeric(p); ei[i] <- hs[i]
    H[i, i] <- (fe(ei) - 2 * f0 + fe(-ei)) / (hs[i]^2)
  }
  if (p > 1L) for (i in seq_len(p - 1L)) for (j in (i + 1L):p) {
    ei <- numeric(p); ei[i] <- hs[i]
    ej <- numeric(p); ej[j] <- hs[j]
    hij <- (fe(ei + ej) - fe(ei - ej) - fe(-ei + ej) + fe(-ei - ej)) /
      (4 * hs[i] * hs[j])
    H[i, j] <- hij; H[j, i] <- hij
  }

  information <- -H
  cov <- tryCatch({
    ch <- chol(information)          # errors unless PD
    chol2inv(ch)
  }, error = function(e) NULL)
  if (is.null(cov)) {
    warning("hank_mixture_laplace(): the observed information at the mode is ",
            "not positive definite (mode not a strict maximum, or a coordinate ",
            "is unidentified by the active channels). Returning cov = NULL; add ",
            "an identifying channel (e.g. the LEVEL survey for 'spread') or fix ",
            "that coordinate.", call. = FALSE)
    sd_out <- setNames(rep(NA_real_, p), par_names)
    propose <- function(n) stop("hank_mixture_laplace: cov is NULL; no proposal.")
  } else {
    dimnames(cov) <- list(par_names, par_names)
    sd_out <- setNames(sqrt(diag(cov)), par_names)
    L <- chol(cov)                   # cov = t(L) %*% L
    propose <- function(n) {
      Z <- matrix(stats::rnorm(n * p), n, p)
      out <- Z %*% L + matrix(mode, n, p, byrow = TRUE)
      colnames(out) <- par_names
      out
    }
  }

  list(mode = mode, logpost = f0, hessian = H, information = information,
       cov = cov, sd = sd_out, propose = propose, to_theta = to_theta,
       par_names = par_names, converged = (opt$convergence == 0L))
}
