## R/hank-aggregate-risk.R
## --------------------------------------------------------------------------
## Krusell-Smith (1998) with AGGREGATE RISK.
##
## Everything else in the HANK line is certainty-equivalent: the sequence-space
## Jacobians (hank_ks_ge_jacobian / hank_ks_linear_irf) are linear
## perfect-foresight objects, and hank_ks_nonlinear_irf / hank_td_nonlinear
## solve a DETERMINISTIC transition path.  Neither knows that the aggregate
## state is random, so neither can price aggregate risk or produce a
## state-dependent impulse response.
##
## This file adds the genuine aggregate-uncertainty solution for the SAME
## Krusell-Smith economy that hank_ks_steady() calibrates:
##
##   aggregate TFP  log Z_t  is a finite Markov chain (Z_grid, Pi_Z)
##   aggregate state (K, Z)  with K = beginning-of-period aggregate capital
##   firm            r(K, Z) = alpha Z K^(alpha-1) - delta
##                   w(K, Z) = (1 - alpha) Z K^alpha
##   household       EGM on the asset grid, with the continuation value read
##                   off the aggregate grid at the FORECAST K'
##   forecast rule   log K' = a_z + b_z log K            (one pair per Z state)
##   equilibrium     the rule reproduces the law of motion generated by the
##                   household policies it implies (Krusell-Smith fixed point)
##
## Timing convention (identical to R/hank-ge.R so the two are directly
## comparable): K entering period t is PREDETERMINED and prices at t are
## r_t = alpha Z_t K_t^(alpha-1) - delta.  In the sequence-space notation of
## hank_ks_linear_irf(), which indexes K by the date it is CHOSEN, the object
## called dK[h] there is the response of this file's K_{h+1}.  The oracle
## tests line the two up explicitly.
##
## Distribution dynamics use the NON-STOCHASTIC histogram method (Young 2010)
## already in R/hank-distribution.R (.hank_forward_push): the cross-sectional
## distribution is pushed forward by the policy, never simulated agent by
## agent, so the only Monte-Carlo noise anywhere is in the AGGREGATE shock
## path.
##
## Interpolation in the aggregate capital state is LINEAR IN log K (the same
## variable the forecast rule is linear in), on a log-spaced K grid.  Linear
## rather than Chebyshev: the policy is close to log-linear in K over the
## ergodic set, a piecewise-linear interpolant reproduces its SLOPE to
## O(h^2) on a smooth function, and the resulting operator is a fixed sparse
## matrix that can be applied to the whole (n_e*n_a) x (n_k*n_z) value array
## in a single matmul (see .hank_agg_expectation_operator).
## --------------------------------------------------------------------------


# =============================================================================
# Aggregate TFP chain
# =============================================================================

#' Discretize an AR(1) aggregate TFP process into a finite Markov chain
#'
#' Rouwenhorst (1995) discretization of
#' \deqn{\log Z_t = \rho \log Z_{t-1} + \varepsilon_t, \qquad
#'       \varepsilon_t \sim (0, \sigma_\varepsilon^2),}
#' parameterized by the STATIONARY standard deviation
#' \eqn{\sigma = \sigma_\varepsilon / \sqrt{1 - \rho^2}} (the same convention
#' as \code{\link{hank_income_rouwenhorst}}).
#'
#' The Rouwenhorst transition matrix itself is built by the package's existing
#' helper (\code{.hank_rouwenhorst_Pi}, R/hank-income.R) -- there is exactly
#' one Rouwenhorst implementation in dynhr.  The only difference from
#' \code{hank_income_rouwenhorst} is the LEVEL normalization: an idiosyncratic
#' efficiency process is rescaled so that \eqn{E[e] = 1} (labour supply is a
#' normalization), whereas aggregate TFP is a level with economic content and
#' is left as \eqn{Z = \exp(s)} with \eqn{E[\log Z] = 0}, so that the
#' deterministic steady state \eqn{Z = 1} is the \eqn{\sigma \to 0} limit of
#' the chain and \code{\link{hank_ks_steady}} is the certainty-equivalent
#' reference point.
#'
#' Two properties of Rouwenhorst that the oracles in
#' \code{tests/testthat/test-hank-aggregate-risk-oracle.R} rely on:
#' \itemize{
#'   \item the conditional mean is EXACTLY the AR(1) one,
#'     \eqn{E[s_{t+1} \mid s_t] = \rho s_t}, for every \code{n}; and
#'   \item the stationary variance is exactly \eqn{\sigma^2} for every
#'     \code{n} (so an \code{n = 2} and an \code{n = 5} chain target the same
#'     AR(1) and may be compared directly).
#' }
#'
#' @param rho Numeric in \eqn{(-1, 1)}: AR(1) persistence of \eqn{\log Z}.
#' @param sigma Numeric > 0: STATIONARY standard deviation of \eqn{\log Z}.
#'   Pass \code{sigma = sigma_eps / sqrt(1 - rho^2)} to target an innovation
#'   standard deviation.
#' @param n Integer >= 2: number of aggregate states.
#'
#' @return A list with \code{Z_grid} (length \code{n}, increasing, strictly
#'   positive), \code{Pi_Z} (\code{n x n} row-stochastic), \code{pi_Z} (the
#'   stationary distribution), \code{log_Z} (the log grid), and the
#'   calibration \code{rho}, \code{sigma}, \code{sigma_eps}, \code{n}.
#' @seealso \code{\link{hank_ks_aggregate_risk}},
#'   \code{\link{hank_income_rouwenhorst}}
#' @examples
#' ch <- hank_tfp_chain(rho = 0.9, sigma = 0.03, n = 5)
#' round(ch$Z_grid, 4)
#' ## Rouwenhorst matches the AR(1) conditional mean exactly:
#' max(abs(as.numeric(ch$Pi_Z %*% ch$log_Z) - ch$rho * ch$log_Z))
#' @export
hank_tfp_chain <- function(rho, sigma, n = 5L) {
  n <- as.integer(n)
  if (!is.finite(rho) || abs(rho) >= 1)
    stop("hank_tfp_chain(): 'rho' must be finite and in (-1, 1).")
  if (!is.finite(sigma) || sigma <= 0)
    stop("hank_tfp_chain(): 'sigma' must be a finite positive number (the ",
         "STATIONARY sd of log Z).")
  if (n < 2L)
    stop("hank_tfp_chain(): 'n' must be >= 2. For a degenerate (no aggregate ",
         "risk) chain pass Z_grid = 1 and Pi_Z = matrix(1) directly to ",
         "hank_ks_aggregate_risk().")
  p    <- (1 + rho) / 2
  Pi_Z <- .hank_rouwenhorst_Pi(n, p)
  piZ  <- .hank_stationary(Pi_Z)
  s0    <- seq(-1, 1, length.out = n)
  mean0 <- sum(piZ * s0)
  var0  <- sum(piZ * (s0 - mean0)^2)
  s     <- (s0 - mean0) * (sigma / sqrt(var0))
  list(Z_grid = exp(s), Pi_Z = Pi_Z, pi_Z = piZ, log_Z = s,
       rho = rho, sigma = sigma, sigma_eps = sigma * sqrt(1 - rho^2), n = n)
}


# =============================================================================
# Internals: aggregate-state grids, prices, expectation operator
# =============================================================================

#' Firm prices at an aggregate state
#'
#' \eqn{r = \alpha Z K^{\alpha-1} - \delta}, \eqn{w = (1-\alpha) Z K^{\alpha}},
#' with \eqn{K} the PREDETERMINED beginning-of-period aggregate capital (the
#' same closure as \code{\link{hank_ks_steady}} and
#' \code{\link{hank_ks_ge_jacobian}}).
#' @param K,Z Numeric (recycled against each other by \code{outer}-style ops).
#' @param alpha,delta Capital share and depreciation.
#' @return A list with \code{r} and \code{w}.
#' @keywords internal
.hank_agg_prices <- function(K, Z, alpha, delta) {
  list(r = alpha * Z * K^(alpha - 1) - delta,
       w = (1 - alpha) * Z * K^alpha)
}


#' Default aggregate-capital grid, sized off the LINEAR model
#'
#' The ergodic spread of \eqn{\log K} is not known before the model is solved,
#' so the default grid is sized from the certainty-equivalent (sequence-space)
#' solution, which is available for free: feed the AR(1) TFP impulse into
#' \code{\link{hank_ks_linear_irf}} to get the MA coefficients
#' \eqn{\psi_h = d\log K_{h}/d\varepsilon} and read off
#' \eqn{sd(\log K) = \sigma_\varepsilon \sqrt{\sum_h \psi_h^2}}.
#' The grid then spans \code{n_sd} stationary standard deviations either side
#' of \eqn{\log K_{ss}}, with a floor (\code{min_span}) so that a degenerate
#' or near-degenerate chain still gets a non-trivial, well-conditioned grid.
#'
#' @param ks A \code{\link{hank_ks_steady}} steady state.
#' @param sigma_eps Innovation sd of \eqn{\log Z} (0 for a degenerate chain).
#' @param rho Persistence of \eqn{\log Z}.
#' @param n_k Integer >= 2: number of aggregate-capital nodes.
#' @param n_sd Numeric: half-width in stationary sd of \eqn{\log K}.
#' @param min_span Numeric: floor on the half-width in log points.
#' @param T_h Integer: horizon used for the MA truncation.
#' @return A list with \code{K_grid} (increasing, log-spaced) and
#'   \code{sd_logK} (the linear-model stationary sd used to size it).
#' @keywords internal
.hank_agg_default_K_grid <- function(ks, sigma_eps, rho, n_k = 7L, n_sd = 4,
                                     min_span = 0.01, T_h = 200L) {
  sd_logK <- 0
  if (sigma_eps > 0) {
    ## AR(1) impulse of size 1 in log Z at date 1: dZ_h = Z_ss * rho^(h-1).
    dZ  <- ks$Z * rho^(seq_len(T_h) - 1L)
    irf <- hank_ks_linear_irf(ks, dZ)
    psi <- irf$dK / ks$K
    sd_logK <- sigma_eps * sqrt(sum(psi^2))
  }
  span <- max(n_sd * sd_logK, min_span)
  list(K_grid = exp(seq(log(ks$K) - span, log(ks$K) + span,
                        length.out = as.integer(n_k))),
       sd_logK = sd_logK)
}


#' Linear-in-log-K interpolation weights onto a log-spaced K grid
#'
#' Returns the lower bracketing index (clamped to \code{[1, n_k - 1]}) and the
#' weight on it.  Outside the grid the weights are NOT clamped, so the
#' interpolant extrapolates linearly with the nearest interval's slope --
#' matching \code{\link{.hank_interp1}}'s convention rather than flattening
#' the policy at the boundary (a flat extrapolation would create a spurious
#' kink exactly where the simulated path is least well covered).
#'
#' @param log_K_grid Increasing numeric: \code{log(K_grid)}.
#' @param log_Kq Numeric query points in logs.
#' @return A list with \code{i} (integer, same shape as \code{log_Kq}) and
#'   \code{w} (weight on node \code{i}; \code{1 - w} on \code{i + 1}).
#' @keywords internal
.hank_agg_K_weights <- function(log_K_grid, log_Kq) {
  n_k <- length(log_K_grid)
  if (n_k < 2L)
    stop(".hank_agg_K_weights(): the aggregate capital grid needs >= 2 nodes.")
  i <- findInterval(log_Kq, log_K_grid)
  i[i < 1L] <- 1L
  i[i > n_k - 1L] <- n_k - 1L
  dim(i) <- dim(log_Kq)
  lo <- log_K_grid[i]; hi <- log_K_grid[i + 1L]
  w  <- (hi - log_Kq) / (hi - lo)
  dim(w) <- dim(log_Kq)
  list(i = i, w = w)
}


#' Aggregate expectation operator for the backward EGM sweep
#'
#' Builds the \code{(n_k*n_z) x (n_k*n_z)} matrix \code{W} such that, with the
#' marginal-value array stored as a \code{(n_e*n_a) x (n_k*n_z)} matrix
#' \code{M} (column \code{(z-1)*n_k + k} holding \eqn{V_a(\cdot;K_k,Z_z)}),
#' \deqn{(M W)[\cdot, (z-1)n_k + k]
#'   = \sum_{z'} \Pi_Z[z, z']\, V_a(\cdot; K'(K_k, Z_z), Z_{z'}),}
#' i.e. one dense matmul does BOTH the aggregate expectation and the
#' interpolation of the continuation value at the forecast \eqn{K'}.
#'
#' The operator depends only on the forecast rule and the grids, not on the
#' iterate, so it is built once per backward solve and reused every backward
#' iteration.  (This is why the backward sweep costs one small matmul plus
#' \code{n_k*n_z} EGM steps per iteration, and not \code{n_k*n_z*n_z}
#' interpolations.)
#'
#' @param log_K_grid Increasing numeric \code{log(K_grid)}.
#' @param Pi_Z Row-stochastic \code{n_z x n_z} aggregate transition.
#' @param log_Kp Numeric \code{n_k x n_z}: \eqn{\log K'} implied by the rule.
#' @return A \code{(n_k*n_z) x (n_k*n_z)} numeric matrix.
#' @keywords internal
.hank_agg_expectation_operator <- function(log_K_grid, Pi_Z, log_Kp) {
  n_k <- length(log_K_grid); n_z <- nrow(Pi_Z)
  wk  <- .hank_agg_K_weights(log_K_grid, log_Kp)
  W   <- matrix(0, n_k * n_z, n_k * n_z)
  for (z in seq_len(n_z)) {
    for (k in seq_len(n_k)) {
      col <- (z - 1L) * n_k + k
      il  <- wk$i[k, z]; wl <- wk$w[k, z]
      for (zp in seq_len(n_z)) {
        pr <- Pi_Z[z, zp]
        if (pr == 0) next
        base <- (zp - 1L) * n_k
        W[base + il,      col] <- W[base + il,      col] + pr * wl
        W[base + il + 1L, col] <- W[base + il + 1L, col] + pr * (1 - wl)
      }
    }
  }
  W
}


#' Backward EGM sweep on the (a, e) x (K, Z) state space
#'
#' Iterates the SAME one-asset EGM kernel used by \code{\link{hank_egm_solve}}
#' (\code{\link{.hank_egm_step}}) at every aggregate node \code{(K_k, Z_z)},
#' with the continuation value supplied by
#' \code{\link{.hank_agg_expectation_operator}}.  Because idiosyncratic
#' \eqn{e'} and aggregate \eqn{Z'} are independent, the double expectation
#' factors: the \eqn{Z'} average is taken first (by the operator) and
#' \code{.hank_egm_step}'s own \code{Pi \%*\% Va_p} then takes the \eqn{e'}
#' average, so the kernel is reused verbatim rather than reimplemented.
#'
#' @param a_grid,Pi,e,beta,eis Household calibration (as
#'   \code{\link{hank_het_block}}).
#' @param alpha,delta Firm calibration.
#' @param Z_grid,Pi_Z Aggregate chain.
#' @param K_grid Aggregate capital grid (increasing, positive).
#' @param rule_a,rule_b Length-\code{n_z} forecast-rule coefficients,
#'   \eqn{\log K' = a_z + b_z \log K}.
#' @param amin Borrowing constraint.
#' @param Va_init Optional \code{(n_e*n_a) x (n_k*n_z)} warm start.
#' @param tol,maxit Convergence tolerance on the savings policy, iteration cap.
#' @return A list with \code{Va}, \code{a_pol}, \code{c_pol} (each
#'   \code{(n_e*n_a) x (n_k*n_z)}, column-major within the \code{n_e x n_a}
#'   block), \code{r_node}, \code{w_node} (\code{n_k x n_z}),
#'   \code{iterations}, \code{converged}, \code{gap}.
#' @keywords internal
.hank_agg_backward <- function(a_grid, Pi, e, beta, eis, alpha, delta,
                               Z_grid, Pi_Z, K_grid, rule_a, rule_b,
                               amin = NULL, Va_init = NULL,
                               tol = 1e-10, maxit = 5000L) {
  n_e <- length(e); n_a <- length(a_grid)
  n_k <- length(K_grid); n_z <- length(Z_grid)
  if (is.null(amin)) amin <- a_grid[1L]
  log_K <- log(K_grid)
  log_Kp <- outer(log_K, rule_b, "*") + rep(rule_a, each = n_k)  # n_k x n_z
  W <- .hank_agg_expectation_operator(log_K, Pi_Z, log_Kp)

  pr <- .hank_agg_prices(matrix(K_grid, n_k, n_z),
                         matrix(Z_grid, n_k, n_z, byrow = TRUE), alpha, delta)
  r_node <- pr$r; w_node <- pr$w
  n_node <- n_k * n_z

  if (is.null(Va_init)) {
    M <- matrix(0, n_e * n_a, n_node)
    for (z in seq_len(n_z)) for (k in seq_len(n_k)) {
      j <- (z - 1L) * n_k + k
      coh0 <- (1 + r_node[k, z]) * matrix(a_grid, n_e, n_a, byrow = TRUE) +
        w_node[k, z] * e
      M[, j] <- as.numeric((1 + r_node[k, z]) *
                             pmax(0.1 * coh0, 1e-12)^(-1 / eis))
    }
  } else {
    M <- Va_init
  }

  A_old <- matrix(-Inf, n_e * n_a, n_node)
  A_new <- matrix(0, n_e * n_a, n_node)
  C_new <- matrix(0, n_e * n_a, n_node)
  M_new <- matrix(0, n_e * n_a, n_node)
  converged <- FALSE; gap <- NA_real_; it <- 0L
  for (it in seq_len(maxit)) {
    EM <- M %*% W
    for (z in seq_len(n_z)) for (k in seq_len(n_k)) {
      j <- (z - 1L) * n_k + k
      st <- .hank_egm_step(matrix(EM[, j], n_e, n_a), a_grid,
                           y = w_node[k, z] * e, r = r_node[k, z],
                           beta = beta, eis = eis, Pi = Pi, amin = amin)
      M_new[, j] <- as.numeric(st$Va)
      A_new[, j] <- as.numeric(st$a)
      C_new[, j] <- as.numeric(st$c)
    }
    gap <- max(abs(A_new - A_old))
    M <- M_new; A_old <- A_new
    if (gap < tol) { converged <- TRUE; break }
  }
  list(Va = M, a_pol = A_new, c_pol = C_new,
       r_node = r_node, w_node = w_node,
       iterations = it, converged = converged, gap = gap)
}


#' Interpolate a stacked policy array in log K at one aggregate state
#'
#' @param P Numeric \code{(n_e*n_a) x (n_k*n_z)} policy array.
#' @param log_K_grid Increasing \code{log(K_grid)}.
#' @param log_K Scalar query in logs.
#' @param z Integer aggregate-state index.
#' @param n_e,n_a Household grid dimensions.
#' @param n_k Number of aggregate-capital nodes.
#' @return An \code{n_e x n_a} matrix.
#' @keywords internal
.hank_agg_policy_at <- function(P, log_K_grid, log_K, z, n_e, n_a, n_k) {
  wk <- .hank_agg_K_weights(log_K_grid, matrix(log_K, 1L, 1L))
  il <- wk$i[1L, 1L]; wl <- wk$w[1L, 1L]
  base <- (z - 1L) * n_k
  matrix(wl * P[, base + il] + (1 - wl) * P[, base + il + 1L], n_e, n_a)
}


#' One aggregate simulation of the distribution under a given Z-index path
#'
#' Non-stochastic histogram simulation: the cross-section is pushed forward by
#' \code{.hank_forward_push()}, never sampled.
#'
#' @param sol Backward solution from \code{\link{.hank_agg_backward}}.
#' @param a_grid,Pi,e,alpha,delta,Z_grid,K_grid Model objects.
#' @param z_path Integer vector of aggregate-state indices, length \code{T}.
#' @param D0 Initial distribution (length \code{n_e*n_a}, distribution order).
#' @param K0 Aggregate capital ENTERING period 1 (see Details).
#' @param keep_D Logical: also return the per-period distributions.
#'
#' @details
#' Aggregate capital is measured as \code{hank_aggregate(D_t, a_pol_t)} --
#' mass-weighted household SAVINGS -- which is the same quantity
#' \code{\link{hank_het_block}} reports as \code{A} and the same one
#' \code{\link{hank_ks_steady}} clears against the firm's capital demand. It
#' is NOT \code{sum(D_{t+1} * a_grid)}: Young's savings lottery preserves the
#' conditional mean only for policies strictly inside the grid, so at the top
#' of a finite asset grid the two differ (by 0.5\% on the small example grid
#' used in the tests). Using the distribution-mean version would silently
#' define a DIFFERENT aggregate from the one the sequence-space Jacobians
#' differentiate, and the certainty-equivalence limit against
#' \code{\link{hank_ks_linear_irf}} would then be off by that wedge no matter
#' how fine the aggregate grid -- which is exactly how this was caught.
#'
#' @return A list with \code{K} (length \code{T + 1}: \code{K[t]} is the
#'   capital entering period \code{t}, so \code{K[T+1]} is the capital chosen
#'   in the last simulated period), \code{r}, \code{w}, \code{C}, \code{Y}
#'   (length \code{T}), \code{D_last}, and \code{frac_offgrid}.
#' @keywords internal
.hank_agg_simulate_path <- function(sol, a_grid, Pi, e, alpha, delta,
                                    Z_grid, K_grid, z_path, D0, K0,
                                    keep_D = FALSE) {
  n_e <- length(e); n_a <- length(a_grid); n_k <- length(K_grid)
  Tn <- length(z_path)
  log_K_grid <- log(K_grid)
  D <- D0
  Kv <- numeric(Tn + 1L); rv <- numeric(Tn); wv <- numeric(Tn)
  Cv <- numeric(Tn); Yv <- numeric(Tn)
  Dstore <- if (keep_D) matrix(0, length(D0), Tn) else NULL
  off <- 0L
  lo <- log_K_grid[1L]; hi <- log_K_grid[n_k]
  K <- K0
  for (t in seq_len(Tn)) {
    Kv[t] <- K
    if (keep_D) Dstore[, t] <- D
    lK <- log(K)
    if (lK < lo || lK > hi) off <- off + 1L
    z <- z_path[t]
    Zt <- Z_grid[z]
    pr <- .hank_agg_prices(K, Zt, alpha, delta)
    rv[t] <- pr$r; wv[t] <- pr$w
    Yv[t] <- Zt * K^alpha
    a_pol <- .hank_agg_policy_at(sol$a_pol, log_K_grid, lK, z, n_e, n_a, n_k)
    c_pol <- .hank_agg_policy_at(sol$c_pol, log_K_grid, lK, z, n_e, n_a, n_k)
    Cv[t] <- hank_aggregate(D, c_pol)
    K <- hank_aggregate(D, a_pol)
    D <- .hank_forward_push(a_pol, a_grid, Pi, D)
  }
  Kv[Tn + 1L] <- K
  list(K = Kv, r = rv, w = wv, C = Cv, Y = Yv, D_last = D, D = Dstore,
       frac_offgrid = off / Tn)
}


#' Fit the per-Z log-linear forecast rule to a simulated path
#'
#' Regresses \eqn{\log K_{t+1}} on \eqn{\log K_t} separately within each
#' aggregate state \code{z_t}.  A state whose realized \eqn{\log K_t} has
#' a standard deviation below \code{1e-8} log points -- which is exactly what
#' a degenerate chain produces, since the simulation then converges to a
#' point -- gets the
#' DEGENERATE rule \eqn{b_z = 0}, \eqn{a_z = \overline{\log K_{t+1}}} and
#' \code{R2 = NA}: a slope is not identified there, and inventing one (or
#' inheriting the previous iteration's) would silently make the household
#' forecast off a number the data never spoke to.
#'
#' @param logK Numeric length \code{T + 1}: realized \eqn{\log K_t}.
#' @param z_path Integer length \code{T}.
#' @param n_z Number of aggregate states.
#' @return A list with \code{a}, \code{b}, \code{R2}, \code{n_obs} (each
#'   length \code{n_z}).
#' @keywords internal
.hank_agg_fit_rule <- function(logK, z_path, n_z) {
  a <- numeric(n_z); b <- numeric(n_z)
  R2 <- rep(NA_real_, n_z); n_obs <- integer(n_z)
  x_all <- logK[seq_along(z_path)]
  y_all <- logK[seq_along(z_path) + 1L]
  for (z in seq_len(n_z)) {
    sel <- which(z_path == z)
    n_obs[z] <- length(sel)
    if (length(sel) == 0L) { a[z] <- NA_real_; b[z] <- NA_real_; next }
    x <- x_all[sel]; y <- y_all[sel]
    xb <- mean(x); yb <- mean(y)
    sxx <- sum((x - xb)^2)
    ## Flat test on the SD OF A LOG, i.e. already a relative criterion, and
    ## set well above double-precision noise (1e-8 log points = 1e-6 percent
    ## of K). A tighter, purely-numerical threshold is worse than useless
    ## here: on a degenerate chain the simulated log K settles to ~1e-11
    ## dispersion, which is not "no variance" in floating point, so the
    ## regression happily fits a slope to ROUNDING NOISE, the slope is
    ## different every outer iteration, and the fixed point never converges
    ## even though K itself is pinned to 11 digits.
    if (!is.finite(sxx) || sqrt(sxx / length(sel)) < 1e-8) {
      b[z] <- 0; a[z] <- yb; R2[z] <- NA_real_
    } else {
      bz <- sum((x - xb) * (y - yb)) / sxx
      b[z] <- bz; a[z] <- yb - bz * xb
      sst <- sum((y - yb)^2)
      R2[z] <- if (sst > 0) 1 - sum((y - a[z] - bz * x)^2) / sst else NA_real_
    }
  }
  list(a = a, b = b, R2 = R2, n_obs = n_obs)
}


#' den Haan (2010) dynamic forecast accuracy of a Krusell-Smith rule
#'
#' The one-step \eqn{R^2} of a KS forecast rule is famously uninformative;
#' den Haan's diagnostic iterates the rule forward from a SINGLE initial
#' condition over the whole simulated sample, feeding it only the realized
#' aggregate-shock path, and compares that dynamic forecast with the
#' simulated series.
#'
#' @param logK Numeric length \code{T + 1}: realized \eqn{\log K_t}.
#' @param z_path Integer length \code{T}.
#' @param rule_a,rule_b Rule coefficients.
#' @return A list with \code{max_pct}, \code{mean_pct} (100 * absolute log
#'   deviation, i.e. approximate percent) and the forecast path \code{logK_hat}.
#' @keywords internal
.hank_agg_den_haan <- function(logK, z_path, rule_a, rule_b) {
  Tn <- length(z_path)
  hat <- numeric(Tn + 1L)
  hat[1L] <- logK[1L]
  for (t in seq_len(Tn))
    hat[t + 1L] <- rule_a[z_path[t]] + rule_b[z_path[t]] * hat[t]
  err <- 100 * abs(logK - hat)
  list(max_pct = max(err), mean_pct = mean(err), logK_hat = hat)
}


#' Draw an aggregate-state index path from a finite Markov chain
#' @param Pi_Z Row-stochastic transition.
#' @param Tn Integer path length.
#' @param z0 Integer starting state index.
#' @param u Optional length-\code{Tn} vector of uniforms (common random
#'   numbers); drawn if \code{NULL}.
#' @return An integer vector of length \code{Tn}.
#' @keywords internal
.hank_agg_draw_z <- function(Pi_Z, Tn, z0, u = NULL) {
  n_z <- nrow(Pi_Z)
  if (n_z == 1L) return(rep(1L, Tn))
  if (is.null(u)) u <- stats::runif(Tn)
  cdf <- t(apply(Pi_Z, 1L, cumsum))
  z <- integer(Tn)
  cur <- z0
  for (t in seq_len(Tn)) {
    cur <- as.integer(1L + sum(cdf[cur, ] < u[t]))
    if (cur > n_z) cur <- n_z
    z[t] <- cur
  }
  z
}


# =============================================================================
# Public: the Krusell-Smith aggregate-risk solve
# =============================================================================

#' Krusell-Smith equilibrium WITH aggregate risk
#'
#' Solves the Krusell-Smith (1998) economy in which aggregate TFP is a
#' genuinely stochastic finite Markov chain, by the standard bounded-rationality
#' algorithm: households forecast next period's aggregate capital with a
#' log-linear rule (one intercept/slope pair per aggregate state), the implied
#' policies are simulated forward with the non-stochastic histogram method, and
#' the rule is re-fitted to the simulated law of motion until it stops moving.
#'
#' This is the first object in the HANK line that is NOT certainty-equivalent.
#' \code{\link{hank_ks_linear_irf}} and \code{\link{hank_ks_nonlinear_irf}}
#' both solve deterministic (perfect-foresight) paths off
#' \code{\link{hank_ks_steady}}; here the household's Euler equation integrates
#' over the aggregate shock as well as the idiosyncratic one, so the solution
#' carries aggregate precautionary effects and state-dependent dynamics. The
#' certainty-equivalent solution is recovered in the \eqn{\sigma_Z \to 0}
#' limit (asserted in
#' \code{tests/testthat/test-hank-aggregate-risk-oracle.R}).
#'
#' @section Algorithm:
#' \enumerate{
#'   \item BACKWARD. At every aggregate node \eqn{(K_k, Z_z)}, one EGM sweep
#'     with the continuation marginal value read at the forecast
#'     \eqn{K' = \exp(a_z + b_z \log K_k)} and averaged over \eqn{Z'} with
#'     \code{Pi_Z} (\code{\link{.hank_agg_backward}}). Interpolation in the
#'     aggregate state is linear in \eqn{\log K}.
#'   \item FORWARD. One long simulation of the DISTRIBUTION (Young's histogram
#'     method, \code{.hank_forward_push()}) under a drawn \eqn{Z} path;
#'     aggregate capital is the distribution's asset mean, so the law of motion
#'     is generated by the policies, not assumed.
#'   \item FIT. Regress \eqn{\log K_{t+1}} on \eqn{\log K_t} within each
#'     \eqn{Z} state; damp the update; repeat until the coefficients stop
#'     moving.
#' }
#' Every backward solve after the first is WARM-STARTED from the previous
#' iteration's marginal value array, which is what keeps the whole fixed point
#' to a few seconds rather than a few minutes.
#'
#' @param ks A \code{\link{hank_ks_steady}} steady state. It supplies the
#'   household calibration (\code{a_grid}, \code{Pi}, \code{e}, \code{beta},
#'   \code{eis}, \code{amin}), the firm calibration (\code{alpha},
#'   \code{delta}) and the deterministic reference point \code{K_ss}.
#' @param Z_grid Numeric length-\code{n_z} aggregate TFP levels, or a list as
#'   returned by \code{\link{hank_tfp_chain}} (in which case \code{Pi_Z} is
#'   taken from it). \code{Z_grid = 1} with \code{Pi_Z = matrix(1)} is the
#'   degenerate (no aggregate risk) chain.
#' @param Pi_Z Row-stochastic \code{n_z x n_z} aggregate transition matrix.
#' @param K_grid Optional aggregate-capital grid. \code{NULL} (default) sizes a
#'   log-spaced grid off the LINEAR model's implied stationary sd of
#'   \eqn{\log K} (see \code{\link{.hank_agg_default_K_grid}}).
#' @param n_k Integer: number of aggregate-capital nodes when \code{K_grid} is
#'   \code{NULL}.
#' @param rule_init Optional list with \code{a} and \code{b} (each length
#'   \code{n_z}) giving the initial forecast rule; defaults to
#'   \eqn{b_z = 0.9}, \eqn{a_z = (1 - 0.9)\log K_{ss}}.
#' @param damp Numeric in \eqn{(0, 1]}: weight on the newly fitted rule in the
#'   outer update.
#' @param tol Numeric: convergence tolerance on the max absolute change in the
#'   rule coefficients across outer iterations.
#' @param maxit Integer: outer-iteration cap.
#' @param egm_tol,egm_maxit Backward-sweep tolerance and iteration cap.
#' @param T_sim Integer: simulated periods per outer iteration.
#' @param burn_in Integer: periods discarded before fitting the rule and
#'   computing the reported ergodic moments.
#' @param seed Integer or \code{NULL}: seed for the aggregate shock path. The
#'   SAME path is reused across outer iterations (a common-random-numbers
#'   choice: it removes simulation noise from the fixed-point criterion, so
#'   \code{tol} measures rule movement, not resampling).
#' @param verbose Logical: report outer-iteration progress.
#'
#' @return An object of class \code{hank_ks_agg_risk}: a list with
#'   \describe{
#'     \item{\code{rule}}{list with \code{a}, \code{b} (length \code{n_z}),
#'       \code{R2} and \code{n_obs}.}
#'     \item{\code{den_haan}}{\code{max_pct} / \code{mean_pct}: the den Haan
#'       (2010) DYNAMIC forecast error in (approximate) percent.}
#'     \item{\code{policy}}{list with \code{a_pol}, \code{c_pol}, \code{Va}
#'       (each \code{(n_e*n_a) x (n_k*n_z)}), and \code{r_node},
#'       \code{w_node}.}
#'     \item{\code{ergodic}}{list with \code{dist} (an \code{n_k x n_z}
#'       frequency table of the aggregate state, built with the same
#'       lottery weights used to interpolate policies), \code{z_freq},
#'       \code{K_mean}, \code{K_sd}, \code{logK_mean}, \code{logK_sd},
#'       \code{D_mean} (the average cross-sectional distribution) and
#'       \code{D_sample} (post-burn-in distributions, used as
#'       \code{\link{hank_ks_risk_irf}}'s ergodic initial conditions).}
#'     \item{\code{K_mean}, \code{K_sd}}{Mean and sd of aggregate capital
#'       under aggregate risk, and \code{K_ss} the deterministic reference.}
#'     \item{\code{sim}}{the final simulated aggregate paths.}
#'     \item{\code{converged}, \code{iterations}, \code{rule_gap},
#'       \code{elapsed}}{fixed-point diagnostics.}
#'   }
#' @seealso \code{\link{hank_ks_risk_irf}}, \code{\link{hank_tfp_chain}},
#'   \code{\link{hank_ks_steady}}, \code{\link{hank_ks_linear_irf}}
#' @references Krusell, P. and A. A. Smith (1998), "Income and Wealth
#'   Heterogeneity in the Macroeconomy", JPE 106(5). den Haan, W. J. (2010),
#'   "Assessing the accuracy of the aggregate law of motion in models with
#'   heterogeneous agents", JEDC 34(1).
#' @examples
#' \donttest{
#' inc    <- hank_income_rouwenhorst(rho = 0.95, sigma = 0.5, n = 3)
#' a_grid <- hank_asset_grid(amax = 50, n = 60, amin = 0)
#' ks     <- hank_ks_steady(a_grid, inc$Pi, inc$e, beta = 0.98, eis = 1,
#'                          alpha = 0.36, delta = 0.025)
#' ch  <- hank_tfp_chain(rho = 0.9, sigma = 0.03, n = 3)
#' fit <- hank_ks_aggregate_risk(ks, ch, T_sim = 400L, burn_in = 100L,
#'                               seed = 1L)
#' fit$rule$R2
#' fit$den_haan$max_pct
#' }
#' @export
hank_ks_aggregate_risk <- function(ks, Z_grid, Pi_Z = NULL, K_grid = NULL,
                                   n_k = 7L, rule_init = NULL, damp = 0.5,
                                   tol = 1e-6, maxit = 60L,
                                   egm_tol = 1e-10, egm_maxit = 5000L,
                                   T_sim = 1500L, burn_in = 300L,
                                   seed = NULL, verbose = FALSE) {
  if (!inherits(ks, "hank_ks"))
    stop("hank_ks_aggregate_risk(): 'ks' must be a hank_ks_steady() object ",
         "(got class ", paste(class(ks), collapse = "/"), ").")
  if (is.list(Z_grid)) {
    if (is.null(Z_grid$Z_grid) || is.null(Z_grid$Pi_Z))
      stop("hank_ks_aggregate_risk(): a list 'Z_grid' must carry 'Z_grid' ",
           "and 'Pi_Z' (i.e. be a hank_tfp_chain() object).")
    if (!is.null(Pi_Z))
      stop("hank_ks_aggregate_risk(): 'Pi_Z' must be NULL when 'Z_grid' is a ",
           "hank_tfp_chain() object (it already carries the transition ",
           "matrix); passing both is ambiguous.")
    chain <- Z_grid
    Pi_Z <- chain$Pi_Z; Z_grid <- chain$Z_grid
  } else {
    chain <- NULL
  }
  Z_grid <- as.numeric(Z_grid)
  n_z <- length(Z_grid)
  if (n_z < 1L || any(!is.finite(Z_grid)) || any(Z_grid <= 0))
    stop("hank_ks_aggregate_risk(): 'Z_grid' must be finite and strictly ",
         "positive.")
  if (is.null(Pi_Z)) Pi_Z <- matrix(1, 1L, 1L)
  Pi_Z <- as.matrix(Pi_Z)
  .hank_check_markov(Pi_Z, n_z, caller = "hank_ks_aggregate_risk")
  if (!is.numeric(damp) || length(damp) != 1L || damp <= 0 || damp > 1)
    stop("hank_ks_aggregate_risk(): 'damp' must be a scalar in (0, 1].")
  T_sim <- as.integer(T_sim); burn_in <- as.integer(burn_in)
  if (burn_in >= T_sim)
    stop("hank_ks_aggregate_risk(): 'burn_in' (", burn_in, ") must be less ",
         "than 'T_sim' (", T_sim, ").")

  t_start <- proc.time()[["elapsed"]]
  blk <- ks$block
  a_grid <- blk$a_grid; Pi <- blk$Pi; e <- blk$e
  beta <- blk$beta; eis <- blk$eis; amin <- blk$amin
  alpha <- ks$alpha; delta <- ks$delta
  n_e <- length(e); n_a <- length(a_grid)

  ## --- aggregate capital grid -------------------------------------------
  sd_logK_linear <- NA_real_
  if (is.null(K_grid)) {
    rho_Z <- if (!is.null(chain)) chain$rho else .hank_agg_chain_rho(Pi_Z, Z_grid)
    sig_e <- if (!is.null(chain)) chain$sigma_eps
             else .hank_agg_chain_sigma_eps(Pi_Z, Z_grid)
    kg <- .hank_agg_default_K_grid(ks, sig_e, rho_Z, n_k = n_k)
    K_grid <- kg$K_grid
    sd_logK_linear <- kg$sd_logK
  }
  K_grid <- as.numeric(K_grid)
  n_k <- length(K_grid)
  if (n_k < 2L || any(diff(K_grid) <= 0) || any(K_grid <= 0))
    stop("hank_ks_aggregate_risk(): 'K_grid' must be a strictly increasing ",
         "vector of at least 2 positive values.")
  log_K_grid <- log(K_grid)

  ## --- initial rule ------------------------------------------------------
  if (is.null(rule_init)) {
    rule_b <- rep(0.9, n_z)
    rule_a <- (1 - rule_b) * log(ks$K)
  } else {
    rule_a <- as.numeric(rule_init$a); rule_b <- as.numeric(rule_init$b)
    if (length(rule_a) != n_z || length(rule_b) != n_z)
      stop("hank_ks_aggregate_risk(): 'rule_init$a' and 'rule_init$b' must ",
           "each have length n_z (", n_z, ").")
  }

  ## --- aggregate shock path (fixed across outer iterations) --------------
  if (!is.null(seed)) {
    if (!exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
      stats::runif(1)
    }
    old_seed <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
    on.exit(assign(".Random.seed", old_seed, envir = globalenv()), add = TRUE)
    set.seed(as.integer(seed))
  }
  z0 <- if (n_z == 1L) 1L else as.integer(ceiling(n_z / 2))
  z_path <- .hank_agg_draw_z(Pi_Z, T_sim, z0)

  ## --- initial condition: the deterministic steady-state cross-section, and
  ## the aggregate capital it clears (blk$A == ks$K to the uniroot tolerance;
  ## blk$A is the household-side number, so the simulation starts EXACTLY on
  ## the household's own aggregate rather than on the firm's).
  D0 <- blk$D
  K0 <- blk$A

  Va_warm <- NULL
  converged <- FALSE; rule_gap <- Inf; it <- 0L
  sol <- NULL; sim <- NULL; fit <- NULL
  for (it in seq_len(maxit)) {
    sol <- .hank_agg_backward(a_grid, Pi, e, beta, eis, alpha, delta,
                              Z_grid, Pi_Z, K_grid, rule_a, rule_b,
                              amin = amin, Va_init = Va_warm,
                              tol = egm_tol, maxit = egm_maxit)
    if (!sol$converged)
      warning("hank_ks_aggregate_risk(): the backward EGM sweep did not ",
              "converge at outer iteration ", it, " (gap = ",
              format(sol$gap), " vs egm_tol = ", format(egm_tol), ").",
              call. = FALSE)
    Va_warm <- sol$Va
    sim <- .hank_agg_simulate_path(sol, a_grid, Pi, e, alpha, delta,
                                   Z_grid, K_grid, z_path, D0, K0,
                                   keep_D = TRUE)
    keep <- (burn_in + 1L):T_sim
    fit <- .hank_agg_fit_rule(log(sim$K[c(keep, T_sim + 1L)]),
                              z_path[keep], n_z)
    a_new <- ifelse(is.finite(fit$a), fit$a, rule_a)
    b_new <- ifelse(is.finite(fit$b), fit$b, rule_b)
    rule_gap <- max(abs(c(a_new - rule_a, b_new - rule_b)))
    rule_a <- (1 - damp) * rule_a + damp * a_new
    rule_b <- (1 - damp) * rule_b + damp * b_new
    if (verbose)
      message(sprintf("[hank_ks_aggregate_risk] iter %d  rule gap %.3e  R2 %s",
                      it, rule_gap,
                      paste(sprintf("%.5f", fit$R2), collapse = " ")))
    if (rule_gap < tol) { converged <- TRUE; break }
  }

  ## --- final pass on the converged rule ----------------------------------
  sol <- .hank_agg_backward(a_grid, Pi, e, beta, eis, alpha, delta,
                            Z_grid, Pi_Z, K_grid, rule_a, rule_b,
                            amin = amin, Va_init = Va_warm,
                            tol = egm_tol, maxit = egm_maxit)
  sim <- .hank_agg_simulate_path(sol, a_grid, Pi, e, alpha, delta,
                                 Z_grid, K_grid, z_path, D0, K0, keep_D = TRUE)
  keep <- (burn_in + 1L):T_sim
  logK_keep <- log(sim$K[c(keep, T_sim + 1L)])
  fit <- .hank_agg_fit_rule(logK_keep, z_path[keep], n_z)
  dh  <- .hank_agg_den_haan(logK_keep, z_path[keep], rule_a, rule_b)

  ## --- ergodic objects ---------------------------------------------------
  K_keep <- sim$K[keep]
  wk <- .hank_agg_K_weights(log_K_grid, matrix(log(K_keep), length(K_keep), 1L))
  erg <- matrix(0, n_k, n_z)
  zk <- z_path[keep]
  for (m in seq_along(K_keep)) {
    il <- wk$i[m, 1L]; wl <- min(max(wk$w[m, 1L], 0), 1)
    erg[il, zk[m]]      <- erg[il, zk[m]]      + wl
    erg[il + 1L, zk[m]] <- erg[il + 1L, zk[m]] + (1 - wl)
  }
  erg <- erg / sum(erg)
  z_freq <- tabulate(zk, nbins = n_z) / length(zk)
  D_sample <- sim$D[, keep, drop = FALSE]
  K_sample <- sim$K[keep]

  structure(list(
    ks = ks, Z_grid = Z_grid, Pi_Z = Pi_Z, K_grid = K_grid,
    chain = chain,
    rule = list(a = rule_a, b = rule_b, R2 = fit$R2, n_obs = fit$n_obs),
    den_haan = list(max_pct = dh$max_pct, mean_pct = dh$mean_pct),
    policy = list(a_pol = sol$a_pol, c_pol = sol$c_pol, Va = sol$Va,
                  r_node = sol$r_node, w_node = sol$w_node),
    ergodic = list(dist = erg, z_freq = z_freq,
                   K_mean = mean(K_keep), K_sd = stats::sd(K_keep),
                   logK_mean = mean(log(K_keep)),
                   logK_sd = stats::sd(log(K_keep)),
                   D_mean = rowMeans(D_sample), D_sample = D_sample,
                   K_sample = K_sample, z_sample = zk),
    K_mean = mean(K_keep), K_sd = stats::sd(K_keep), K_ss = ks$K,
    sd_logK_linear = sd_logK_linear,
    sim = list(K = sim$K, r = sim$r, w = sim$w, C = sim$C, Y = sim$Y,
               z_path = z_path, Z = Z_grid[z_path],
               frac_offgrid = sim$frac_offgrid),
    dims = c(n_e = n_e, n_a = n_a, n_k = n_k, n_z = n_z),
    egm = list(iterations = sol$iterations, converged = sol$converged,
               gap = sol$gap),
    converged = converged, iterations = it, rule_gap = rule_gap,
    T_sim = T_sim, burn_in = burn_in, seed = seed,
    elapsed = proc.time()[["elapsed"]] - t_start),
    class = "hank_ks_agg_risk")
}


#' Implied AR(1) persistence of a finite chain on log levels
#'
#' Least-squares persistence of \eqn{\log Z} under the chain's own stationary
#' distribution: \eqn{\rho = Cov(\log Z_{t+1}, \log Z_t) / Var(\log Z_t)}.
#' Used only to size the DEFAULT aggregate capital grid when the caller
#' supplies a raw \code{(Z_grid, Pi_Z)} pair rather than a
#' \code{\link{hank_tfp_chain}} object.
#' @param Pi_Z Row-stochastic transition.
#' @param Z_grid Level grid.
#' @return Numeric scalar (0 for a degenerate chain).
#' @keywords internal
.hank_agg_chain_rho <- function(Pi_Z, Z_grid) {
  if (length(Z_grid) < 2L) return(0)
  s  <- log(Z_grid)
  pz <- .hank_stationary(Pi_Z)
  m  <- sum(pz * s)
  v  <- sum(pz * (s - m)^2)
  if (v <= 0) return(0)
  cv <- sum(pz * (s - m) * (as.numeric(Pi_Z %*% s) - m))
  cv / v
}

#' Implied AR(1) innovation sd of a finite chain on log levels
#'
#' \eqn{\sigma_\varepsilon = \sigma \sqrt{1 - \rho^2}} with \eqn{\sigma} the
#' stationary sd of \eqn{\log Z} and \eqn{\rho} from
#' \code{\link{.hank_agg_chain_rho}}. Used only for the default K grid.
#' @param Pi_Z Row-stochastic transition.
#' @param Z_grid Level grid.
#' @return Numeric scalar (0 for a degenerate chain).
#' @keywords internal
.hank_agg_chain_sigma_eps <- function(Pi_Z, Z_grid) {
  if (length(Z_grid) < 2L) return(0)
  s  <- log(Z_grid)
  pz <- .hank_stationary(Pi_Z)
  m  <- sum(pz * s)
  sg <- sqrt(sum(pz * (s - m)^2))
  rho <- .hank_agg_chain_rho(Pi_Z, Z_grid)
  sg * sqrt(max(0, 1 - rho^2))
}


# =============================================================================
# S3: print and simulate
# =============================================================================

#' Print a Krusell-Smith aggregate-risk solution
#' @param x A \code{hank_ks_agg_risk} object.
#' @param ... Unused.
#' @return \code{x}, invisibly.
#' @export
print.hank_ks_agg_risk <- function(x, ...) {
  cat("=== hank_ks_agg_risk ===\n")
  cat(sprintf("Grids            : n_e = %d, n_a = %d, n_k = %d, n_z = %d\n",
              x$dims[["n_e"]], x$dims[["n_a"]], x$dims[["n_k"]],
              x$dims[["n_z"]]))
  cat(sprintf("Fixed point      : %s in %d outer iterations (gap %.2e)\n",
              if (isTRUE(x$converged)) "converged" else "NOT converged",
              x$iterations, x$rule_gap))
  cat(sprintf("Forecast rule R2 : %s\n",
              paste(sprintf("%.6f", x$rule$R2), collapse = "  ")))
  cat(sprintf("den Haan error   : max %.4f%%, mean %.4f%%\n",
              x$den_haan$max_pct, x$den_haan$mean_pct))
  cat(sprintf("Aggregate K      : mean %.6f, sd %.6f (deterministic ss %.6f)\n",
              x$K_mean, x$K_sd, x$K_ss))
  cat(sprintf("Elapsed          : %.2f s\n", x$elapsed))
  invisible(x)
}


#' Simulate aggregate paths from a Krusell-Smith aggregate-risk solution
#'
#' Runs the non-stochastic histogram simulation forward under a supplied or
#' drawn aggregate-shock path, returning the aggregate series the solution
#' implies.
#'
#' @param object A \code{hank_ks_agg_risk} object from
#'   \code{\link{hank_ks_aggregate_risk}}.
#' @param nsim Integer: number of independent simulated paths.
#' @param seed Integer or \code{NULL}: seed for the drawn aggregate paths (and
#'   restored on exit, per the \code{stats::simulate} contract).
#' @param T_sim Integer: length of each simulated path.
#' @param z_path Optional integer vector of aggregate-state indices to use
#'   instead of drawing one. When supplied, \code{nsim} must be 1 and
#'   \code{T_sim} is taken from its length.
#' @param D0 Optional initial cross-sectional distribution (length
#'   \code{n_e*n_a}, distribution order). Defaults to the solution's ergodic
#'   MEAN distribution, so a path starts from the stochastic steady state
#'   rather than from the deterministic one.
#' @param K0 Optional aggregate capital entering the first period; defaults to
#'   the ergodic mean of \code{K}.
#' @param burn_in Integer: leading periods dropped from the returned paths
#'   (0 by default -- the default \code{D0} is already ergodic).
#' @param ... Unused.
#'
#' @return A data frame (\code{nsim = 1}) or a list of data frames, with
#'   columns \code{t}, \code{Z}, \code{z_index}, \code{K} (capital ENTERING
#'   the period), \code{K_next}, \code{r}, \code{w}, \code{C}, \code{Y}.
#' @seealso \code{\link{hank_ks_aggregate_risk}}, \code{\link{hank_ks_risk_irf}}
#' @export
simulate.hank_ks_agg_risk <- function(object, nsim = 1, seed = NULL,
                                      T_sim = 200L, z_path = NULL,
                                      D0 = NULL, K0 = NULL, burn_in = 0L,
                                      ...) {
  nsim <- as.integer(nsim)
  if (nsim < 1L) stop("simulate.hank_ks_agg_risk(): 'nsim' must be >= 1.")
  if (!is.null(z_path) && nsim != 1L)
    stop("simulate.hank_ks_agg_risk(): 'z_path' fixes the aggregate path, so ",
         "'nsim' must be 1 (repeating the same path nsim times would return ",
         "nsim identical draws).")
  if (!is.null(seed)) {
    if (!exists(".Random.seed", envir = globalenv(), inherits = FALSE))
      stats::runif(1)
    old_seed <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
    on.exit(assign(".Random.seed", old_seed, envir = globalenv()), add = TRUE)
    set.seed(as.integer(seed))
  }
  ks <- object$ks; blk <- ks$block
  n_z <- object$dims[["n_z"]]
  if (is.null(D0)) D0 <- object$ergodic$D_mean
  if (is.null(K0)) K0 <- object$ergodic$K_mean
  D0 <- as.numeric(D0)
  if (length(D0) != object$dims[["n_e"]] * object$dims[["n_a"]])
    stop("simulate.hank_ks_agg_risk(): 'D0' must have n_e*n_a = ",
         object$dims[["n_e"]] * object$dims[["n_a"]], " entries.")
  sol <- list(a_pol = object$policy$a_pol, c_pol = object$policy$c_pol)
  z0 <- if (n_z == 1L) 1L else as.integer(ceiling(n_z / 2))
  out <- vector("list", nsim)
  for (s in seq_len(nsim)) {
    zp <- if (is.null(z_path)) .hank_agg_draw_z(object$Pi_Z, as.integer(T_sim), z0)
          else as.integer(z_path)
    sp <- .hank_agg_simulate_path(sol, blk$a_grid, blk$Pi, blk$e,
                                  ks$alpha, ks$delta, object$Z_grid,
                                  object$K_grid, zp, D0, K0)
    Tn <- length(zp)
    idx <- seq.int(as.integer(burn_in) + 1L, Tn)
    out[[s]] <- data.frame(
      t = idx, z_index = zp[idx], Z = object$Z_grid[zp[idx]],
      K = sp$K[idx], K_next = sp$K[idx + 1L],
      r = sp$r[idx], w = sp$w[idx], C = sp$C[idx], Y = sp$Y[idx])
  }
  if (nsim == 1L) out[[1L]] else out
}


# =============================================================================
# Public: generalized impulse response (Koop-Pesaran-Potter)
# =============================================================================

#' Generalized impulse response of the aggregate-risk Krusell-Smith model
#'
#' Koop, Pesaran and Potter (1996) GIRF: the average difference between the
#' economy's path WITH a date-1 aggregate innovation and the path WITHOUT it,
#' both started from the ERGODIC distribution and averaged over future
#' aggregate-shock paths.
#'
#' Both replications start from ERGODIC INITIAL CONDITIONS: each draw begins
#' at a post-burn-in \eqn{(D_t, K_t)} pair of the solve's own simulation
#' (sampled without replacement where possible), so the integration over
#' initial states is over the model's ergodic set and not over an arbitrary
#' reference point. The two branches of a draw share that initial condition,
#' and share one uniform sequence \eqn{u_2, \ldots, u_H} (common random
#' numbers).
#'
#' @section Continuation of the aggregate shock:
#' \describe{
#'   \item{\code{"chain"} (default)}{The Koop-Pesaran-Potter object. After
#'     date 1 each branch follows ITS OWN conditional chain, the shared
#'     \eqn{u_h} being applied to each branch's own conditional CDF (the
#'     Rosenblatt coupling), so the innovation genuinely persists at the
#'     chain's own rate and the two branches couple when their draws
#'     coincide. Because Rouwenhorst reproduces the AR(1) conditional mean
#'     exactly, the date-\eqn{1+j} MEAN of \eqn{\log Z} differs between the
#'     branches by exactly \eqn{\rho^j \Delta} with
#'     \eqn{\Delta = \log Z_{z_{shock}} - \log Z_{z_{ref}}}, so the scaled
#'     response is comparable with \code{\link{hank_ks_linear_irf}} at
#'     \code{dZ = Z * rho^(h-1)}. Its Monte-Carlo error does NOT shrink with
#'     the shock size: while the branches are uncoupled their realized
#'     \eqn{\log Z} differ by one whole grid step, i.e. by \eqn{\Delta}
#'     itself, so the SCALED difference carries O(1) sampling noise and needs
#'     large \code{n_draws}. \code{mcse} reports it.}
#'   \item{\code{"common"}}{The shocked branch inherits the BASELINE's
#'     realized aggregate-state path from date 2 on, so the realized log-TFP
#'     difference is exactly \eqn{(\Delta, 0, 0, \ldots)} on EVERY draw.
#'     This is the response to a one-off date-1 innovation that is not
#'     followed by further TFP differences -- the nonlinear analogue of the
#'     usual "shock at date 1, zero innovations after" impulse response --
#'     and its linear counterpart is \code{hank_ks_linear_irf(ks, c(Z, 0,
#'     ..., 0))}. Households still hold the aggregate-risk policy functions,
#'     so this is a different EXPERIMENT, not a different model. Because the
#'     TFP difference is deterministic, the only remaining sampling variation
#'     is the second-order effect of the common path on the branch gap, which
#'     vanishes with the shock size: this is the low-variance object the
#'     certainty-equivalence oracle uses, and it needs only tens of draws
#'     where \code{"chain"} needs tens of thousands.}
#' }
#'
#' @param obj A \code{hank_ks_agg_risk} object.
#' @param horizon Integer: response horizon.
#' @param n_draws Integer: number of Monte-Carlo replications (initial
#'   conditions x future shock paths).
#' @param z_shock,z_ref Integer aggregate-state indices for the date-1
#'   shocked and baseline branches. Defaults: \code{z_ref} the middle state,
#'   \code{z_shock} the one above it.
#' @param continuation Character: \code{"chain"} (default) or
#'   \code{"common"}; see the section above.
#' @param return_draws Logical: also return the per-replication response and
#'   realized log-TFP difference paths (\code{dlogK_draws},
#'   \code{dlogZ_draws}, each \code{n_draws x horizon}). These are what a
#'   PATH-MATCHED comparison with a linear model needs: pairing each
#'   replication with the linear model's response to that replication's OWN
#'   realized \code{dlogZ_draws} row cancels the aggregate-shock sampling
#'   noise, leaving only the nonlinearity. The certainty-equivalence oracle
#'   uses exactly that.
#' @param seed Integer or \code{NULL}.
#'
#' @return A list with
#'   \describe{
#'     \item{\code{dlogK}}{length-\code{horizon} GIRF of \eqn{\log K}, where
#'       entry \code{h} is the response of the capital CHOSEN at date
#'       \code{h} (i.e. entering date \code{h+1}) -- the same indexing as
#'       \code{\link{hank_ks_linear_irf}}'s \code{dK}.}
#'     \item{\code{dlogK_scaled}}{\code{dlogK / delta_logZ}.}
#'     \item{\code{dlogC}, \code{dlogY}, \code{dr}, \code{dw}}{the other
#'       aggregates, dated at the period they are observed.}
#'     \item{\code{delta_logZ}}{the date-1 log-TFP innovation.}
#'     \item{\code{mcse}}{Monte-Carlo standard error of \code{dlogK}.}
#'     \item{\code{dlogZ}}{the mean realized log-TFP difference path (for
#'       \code{"chain"} this is \eqn{\rho^{h-1}\Delta} up to sampling
#'       error; for \code{"common"} it is exactly \eqn{(\Delta, 0,
#'       \ldots)}).}
#'     \item{\code{n_draws}, \code{z_shock}, \code{z_ref},
#'       \code{continuation}}{}
#'   }
#' @seealso \code{\link{hank_ks_aggregate_risk}},
#'   \code{\link{hank_ks_linear_irf}}
#' @references Koop, G., M. H. Pesaran and S. M. Potter (1996), "Impulse
#'   response analysis in nonlinear multivariate models", J. Econometrics 74.
#' @examples
#' \donttest{
#' inc    <- hank_income_rouwenhorst(rho = 0.95, sigma = 0.5, n = 3)
#' a_grid <- hank_asset_grid(amax = 50, n = 60, amin = 0)
#' ks     <- hank_ks_steady(a_grid, inc$Pi, inc$e, beta = 0.98, eis = 1,
#'                          alpha = 0.36, delta = 0.025)
#' fit <- hank_ks_aggregate_risk(ks, hank_tfp_chain(0.9, 0.03, 3),
#'                               T_sim = 400L, burn_in = 100L, seed = 1L)
#' g <- hank_ks_risk_irf(fit, horizon = 20L, n_draws = 40L, seed = 2L)
#' g$dlogK_scaled[1:5]
#' }
#' @export
hank_ks_risk_irf <- function(obj, horizon = 40L, n_draws = 200L,
                             z_shock = NULL, z_ref = NULL,
                             continuation = c("chain", "common"),
                             return_draws = FALSE, seed = NULL) {
  continuation <- match.arg(continuation)
  if (!inherits(obj, "hank_ks_agg_risk"))
    stop("hank_ks_risk_irf(): 'obj' must be a hank_ks_aggregate_risk() ",
         "object.")
  n_z <- obj$dims[["n_z"]]
  if (n_z < 2L)
    stop("hank_ks_risk_irf(): the aggregate chain is degenerate (n_z = 1); ",
         "there is no aggregate innovation to respond to.")
  if (is.null(z_ref))   z_ref   <- as.integer(ceiling(n_z / 2))
  if (is.null(z_shock)) z_shock <- min(n_z, z_ref + 1L)
  z_ref <- as.integer(z_ref); z_shock <- as.integer(z_shock)
  if (z_ref < 1L || z_ref > n_z || z_shock < 1L || z_shock > n_z)
    stop("hank_ks_risk_irf(): 'z_ref' / 'z_shock' must index the aggregate ",
         "chain (1..", n_z, ").")
  if (z_ref == z_shock)
    stop("hank_ks_risk_irf(): 'z_shock' must differ from 'z_ref' -- an ",
         "identical pair has a zero innovation and the scaled response ",
         "would be 0/0.")
  horizon <- as.integer(horizon); n_draws <- as.integer(n_draws)
  if (horizon < 1L || n_draws < 1L)
    stop("hank_ks_risk_irf(): 'horizon' and 'n_draws' must be >= 1.")

  if (!is.null(seed)) {
    if (!exists(".Random.seed", envir = globalenv(), inherits = FALSE))
      stats::runif(1)
    old_seed <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
    on.exit(assign(".Random.seed", old_seed, envir = globalenv()), add = TRUE)
    set.seed(as.integer(seed))
  }

  ks <- obj$ks; blk <- ks$block
  sol <- list(a_pol = obj$policy$a_pol, c_pol = obj$policy$c_pol)
  Dsam <- obj$ergodic$D_sample
  Ksam <- obj$ergodic$K_sample
  n_sam <- ncol(Dsam)
  start_idx <- if (n_draws <= n_sam)
    sort(sample.int(n_sam, n_draws, replace = FALSE))
  else sample.int(n_sam, n_draws, replace = TRUE)

  cdf <- t(apply(obj$Pi_Z, 1L, cumsum))
  step_z <- function(cur, u) {
    nx <- as.integer(1L + sum(cdf[cur, ] < u))
    if (nx > n_z) n_z else nx
  }

  dK <- matrix(0, n_draws, horizon)
  dZl <- matrix(0, n_draws, horizon)
  dC <- matrix(0, n_draws, horizon); dY <- matrix(0, n_draws, horizon)
  drr <- matrix(0, n_draws, horizon); dww <- matrix(0, n_draws, horizon)
  for (d in seq_len(n_draws)) {
    D0 <- Dsam[, start_idx[d]]
    K0 <- Ksam[start_idx[d]]
    u  <- stats::runif(horizon)                 # common random numbers
    zb <- integer(horizon); zs <- integer(horizon)
    zb[1L] <- z_ref; zs[1L] <- z_shock
    if (horizon > 1L) for (h in 2L:horizon) {
      zb[h] <- step_z(zb[h - 1L], u[h])
      ## "chain": each branch steps from its OWN state (Rosenblatt coupling).
      ## "common": the shocked branch inherits the baseline's realized state,
      ## so the realized log-TFP gap is exactly (Delta, 0, 0, ...).
      zs[h] <- if (continuation == "chain") step_z(zs[h - 1L], u[h]) else zb[h]
    }
    pb <- .hank_agg_simulate_path(sol, blk$a_grid, blk$Pi, blk$e,
                                  ks$alpha, ks$delta, obj$Z_grid,
                                  obj$K_grid, zb, D0, K0)
    ps <- .hank_agg_simulate_path(sol, blk$a_grid, blk$Pi, blk$e,
                                  ks$alpha, ks$delta, obj$Z_grid,
                                  obj$K_grid, zs, D0, K0)
    ## K chosen at date h is K[h + 1] in the path's indexing.
    dK[d, ] <- log(ps$K[-1L]) - log(pb$K[-1L])
    dZl[d, ] <- log(obj$Z_grid[zs]) - log(obj$Z_grid[zb])
    dC[d, ] <- log(ps$C) - log(pb$C)
    dY[d, ] <- log(ps$Y) - log(pb$Y)
    drr[d, ] <- ps$r - pb$r
    dww[d, ] <- log(ps$w) - log(pb$w)
  }
  delta_logZ <- log(obj$Z_grid[z_shock]) - log(obj$Z_grid[z_ref])
  m <- colMeans(dK)
  out_draws <- if (return_draws) list(dlogK_draws = dK, dlogZ_draws = dZl)
               else NULL
  c(list(dlogK = m, dlogK_scaled = m / delta_logZ,
       dlogC = colMeans(dC), dlogY = colMeans(dY),
       dr = colMeans(drr), dlogw = colMeans(dww),
       delta_logZ = delta_logZ,
       mcse = apply(dK, 2L, stats::sd) / sqrt(n_draws),
       dlogZ = colMeans(dZl),
       n_draws = n_draws, horizon = horizon, continuation = continuation,
       z_shock = z_shock, z_ref = z_ref), out_draws)
}


# =============================================================================
# Variance-free ergodic mean of aggregate capital  (F2-B)
# =============================================================================
#
# WHY THIS EXISTS. hank_ks_aggregate_risk() reports K_mean as the sample mean
# of ONE simulated aggregate path. That is fine for the rule fit (a slope,
# estimated from T observations of a highly informative regression) and
# useless for the AGGREGATE PRECAUTIONARY TERM, which is O(sd_Z^2): at
# sd_Z = 0.01 the shift is ~1e-4 of K, while the batch-means standard error of
# the mean of a series with rule slope ~0.94 over 800 retained periods is
# ~1e-3 of K. The reported sign of K_mean - K_ss was therefore noise.
#
# The fix is not a longer simulation (the error falls like T^{-1/2} against a
# fixed target, so resolving a 10x-smaller effect needs a 100x-longer run per
# solve) but removing the sampling entirely. The economy's state is
# (D, K, Z): D the household cross-section, K the predetermined aggregate
# capital, Z the aggregate state. Given the converged policies the map
#
#   (D, K, z) -> (D' = Push(D; a(K,z)), K' = <D, a(K,z)>, z' ~ Pi_Z[z, .])
#
# is a Markov chain whose ONLY randomness is z'. Iterating the DISTRIBUTION of
# that chain forward with Pi_Z -- rather than drawing a path from it -- gives
# E[K] with no Monte-Carlo error at all.
#
# The obstacle is that the (D, K) part is deterministic, so the number of
# distinct (D, K) atoms multiplies by n_z every period: after t periods there
# is one atom per Z-HISTORY. The standard cure (and the one used here) is
# state-space quantisation: fix a fine log-spaced grid K_fine, and after each
# push split each atom's mass between the two bracketing K_fine nodes with the
# usual linear (lottery) weights, merging atoms that land on the same node.
# Merging is a MIXTURE of cross-sections, and both the push and the
# aggregation are LINEAR in D, so the merge is exact in the D direction; the
# only approximation is that the merged atom's policy is read at the grid
# node rather than at its own K. The lottery split matches the conditional
# mean of log K exactly, so that error is O(h^2) in the bin width h, and the
# spurious quantisation variance it injects, <= h^2/4, is what the halving
# check in the tests bounds. (At n_fine = 101 over a 0.1-log-point span,
# h = 1e-3 and h^2/4 = 2.5e-7 against an ergodic Var(log K) of ~6e-5 -- three
# orders of magnitude of headroom.)
#
# COST. Everything is precomputed once per node: the policy, its savings
# lottery, and the scatter keys. One iteration is then one `rowsum` (the
# batched forward push over all n_fine*n_z nodes at once) plus two small
# mixes over Z, so the whole fixed point costs seconds, not minutes. The
# batched push is checked column-by-column against .hank_forward_push() in
# tests/testthat/test-hank-aggregate-risk-precautionary.R.


#' Per-node policies, savings lotteries and scatter keys on the fine K grid
#'
#' One entry per aggregate node \eqn{(K_{fine,j}, Z_z)}; the node index is
#' \code{(z - 1) * n_fine + j}, matching the \code{(K, Z)} stacking used by
#' \code{\link{.hank_agg_backward}}.
#'
#' @param obj A \code{hank_ks_agg_risk} object.
#' @param K_fine Increasing positive numeric: the fine aggregate-capital grid.
#' @return A list with \code{APOL}, \code{CPOL} (\code{(n_e*n_a) x n_node},
#'   distribution order), \code{KEY} and \code{LOTW} (\code{2*(n_e*n_a) x
#'   n_node} scatter keys and lottery weights for the batched push),
#'   \code{perm} (distribution order -> \code{n_e x n_a} column-major), and
#'   the dimensions.
#' @keywords internal
.hank_agg_ergodic_nodes <- function(obj, K_fine) {
  blk <- obj$ks$block
  a_grid <- blk$a_grid; e <- blk$e
  n_e <- length(e); n_a <- length(a_grid); n_ea <- n_e * n_a
  n_k <- length(obj$K_grid); n_z <- length(obj$Z_grid)
  n_fine <- length(K_fine); n_node <- n_fine * n_z
  log_K_grid <- log(obj$K_grid); log_Kf <- log(K_fine)

  APOL <- matrix(0, n_ea, n_node); CPOL <- matrix(0, n_ea, n_node)
  KEY  <- matrix(0L, 2L * n_ea, n_node); LOTW <- matrix(0, 2L * n_ea, n_node)
  off  <- (seq_len(n_e) - 1L) * n_a
  for (z in seq_len(n_z)) for (j in seq_len(n_fine)) {
    nd <- (z - 1L) * n_fine + j
    ap <- .hank_agg_policy_at(obj$policy$a_pol, log_K_grid, log_Kf[j], z,
                              n_e, n_a, n_k)
    cp <- .hank_agg_policy_at(obj$policy$c_pol, log_K_grid, log_Kf[j], z,
                              n_e, n_a, n_k)
    APOL[, nd] <- .hank_mat_to_vec(ap)
    CPOL[, nd] <- .hank_mat_to_vec(cp)
    lot <- .hank_lottery(ap, a_grid)
    KEY[, nd]  <- c(off + lot$i, off + lot$i + 1L) + (nd - 1L) * n_ea
    LOTW[, nd] <- c(lot$p, 1 - lot$p)
  }
  ## Distribution order is (e-1)*n_a + a; the lottery keys above are in the
  ## n_e x n_a matrix's own column-major order, so the push needs this
  ## permutation of the rows (and only the push does).
  perm <- as.integer(matrix(seq_len(n_ea), n_e, n_a, byrow = TRUE))
  list(APOL = APOL, CPOL = CPOL, KEY = KEY, LOTW = LOTW, perm = perm,
       n_e = n_e, n_a = n_a, n_ea = n_ea, n_fine = n_fine, n_z = n_z,
       n_node = n_node)
}


#' Batched Young forward push: one push per aggregate node, in one scatter
#'
#' Identical, column by column, to
#' \code{.hank_forward_push(a_pol_j, a_grid, Pi, D[, j])} -- the savings
#' lottery is precomputed by \code{\link{.hank_agg_ergodic_nodes}} and every
#' node's scatter is offset into one long accumulator, so the whole sweep is a
#' single \code{rowsum} plus an \code{n_e^2} block mix over income states
#' instead of \code{n_fine * n_z} separate calls.
#'
#' The columns need NOT be probability distributions: the push is linear in
#' \code{D}, so unnormalized (mass-weighted) columns are pushed correctly and
#' the caller never has to divide by a node probability.
#'
#' @param nodes A \code{\link{.hank_agg_ergodic_nodes}} object.
#' @param Pi Income transition matrix.
#' @param Dm Numeric \code{(n_e*n_a) x n_node}, distribution order.
#' @return A matrix of the same shape.
#' @keywords internal
.hank_agg_push_many <- function(nodes, Pi, Dm) {
  n_ea <- nodes$n_ea; n_e <- nodes$n_e; n_a <- nodes$n_a
  n_node <- ncol(Dm)
  Dc  <- Dm[nodes$perm, , drop = FALSE]
  W   <- rbind(Dc, Dc) * nodes$LOTW
  acc <- numeric(n_ea * n_node)
  s   <- rowsum(as.numeric(W), as.integer(nodes$KEY), reorder = FALSE)
  acc[as.integer(rownames(s))] <- s[, 1L]
  ## acc index is (nd-1)*n_ea + (e-1)*n_a + a', i.e. a fastest, then e, then
  ## the node: reshaping to n_a x (n_e*n_node) puts income state e in column
  ## e + (nd-1)*n_e, so mixing over income is n_e^2 whole-block operations.
  A   <- matrix(acc, n_a, n_e * n_node)
  out <- matrix(0, n_a, n_e * n_node)
  base <- (seq_len(n_node) - 1L) * n_e
  for (ep in seq_len(n_e)) {
    tmp <- NULL
    for (ee in seq_len(n_e)) {
      pr <- Pi[ee, ep]
      if (pr == 0) next
      b <- pr * A[, ee + base, drop = FALSE]
      tmp <- if (is.null(tmp)) b else tmp + b
    }
    if (!is.null(tmp)) out[, ep + base] <- tmp
  }
  matrix(out, n_ea, n_node)
}


#' Sampling-free ergodic mean of aggregate capital under aggregate risk
#'
#' Computes \eqn{E[K]}, \eqn{sd(K)} and the ergodic distribution of the
#' aggregate state of a solved \code{\link{hank_ks_aggregate_risk}} economy by
#' iterating the JOINT distribution of (household cross-section, aggregate
#' capital, aggregate state) forward with the aggregate chain's own transition
#' probabilities -- never by drawing a shock path. There is therefore no
#' Monte-Carlo error in the result, which is what makes the
#' \eqn{O(\sigma_Z^2)} aggregate precautionary term \eqn{E[K] - K_{ss}}
#' resolvable: the simulated \code{obj$K_mean} carries a batch-means standard
#' error an order of magnitude LARGER than that term, so its sign is not
#' identified (see
#' \code{tests/testthat/test-hank-aggregate-risk-precautionary.R}).
#'
#' @section Method:
#' Given the converged policies the state \eqn{(D, K, z)} evolves as
#' \eqn{D' = \mathrm{Push}(D; a(K, z))}, \eqn{K' = \langle D, a(K,z)\rangle},
#' \eqn{z' \sim \Pi_Z[z, \cdot]}, so the only randomness is \eqn{z'}. The
#' \eqn{(D, K)} part being deterministic, the number of atoms would multiply
#' by \eqn{n_z} each period (one per \eqn{Z}-history); the atoms are therefore
#' QUANTISED onto a fine log-spaced grid \code{K_fine}, each pushed atom
#' splitting between its two bracketing nodes with the usual linear weights
#' and atoms on the same node merging. Merging is a mixture of
#' cross-sections and both the push and the aggregation are linear in
#' \eqn{D}, so the merge is exact in the \eqn{D} direction; the approximation
#' is only that a merged atom's policy is read at the node rather than at its
#' own \eqn{K}, which the lottery split makes \eqn{O(h^2)} in the bin width
#' \eqn{h}. \strong{Always check the answer against a halved bin width} --
#' \code{n_fine = 2 * n_fine - 1} reuses every node -- and treat the
#' difference as the error bar.
#'
#' The reported \code{K_mean} is NOT the quantised node value: each node
#' carries the probability-weighted sum of the EXACT \eqn{K'} that landed on
#' it, so quantisation enters only through the policy argument.
#'
#' @param obj A \code{hank_ks_agg_risk} object from
#'   \code{\link{hank_ks_aggregate_risk}}.
#' @param n_fine Integer >= 3: number of fine aggregate-capital nodes,
#'   log-spaced across the span of \code{obj$K_grid}. Ignored when
#'   \code{K_fine} is supplied.
#' @param K_fine Optional explicit fine grid (increasing, positive).
#' @param tol Numeric: convergence tolerance on the RELATIVE change in the
#'   reported moments of \eqn{K} and \eqn{\log K} (see \code{gap}, and the
#'   note under \code{dist_gap}, in the return value).
#' @param maxit Integer: iteration cap on the forward distribution iteration.
#' @param verbose Logical: report progress every 100 iterations.
#'
#' @return A list with
#'   \describe{
#'     \item{\code{K_mean}, \code{K_sd}, \code{logK_mean}, \code{logK_sd}}{the
#'       ergodic moments of aggregate capital, free of sampling error.}
#'     \item{\code{K_ss}}{the deterministic reference \code{obj$ks$K}.}
#'     \item{\code{precautionary}}{\code{K_mean - K_ss}, and
#'       \code{precautionary_pct} in percent of \code{K_ss}.}
#'     \item{\code{C_mean}, \code{Y_mean}, \code{r_mean}}{ergodic means of
#'       aggregate consumption, output and the interest rate. \code{C_mean} is
#'       exact in the same sense as \code{K_mean}; \code{Y_mean} and
#'       \code{r_mean} are evaluated at the QUANTISED node capital (they are
#'       diagnostics, not the object of the test).}
#'     \item{\code{dist}}{\code{n_fine x n_z} ergodic distribution of the
#'       aggregate state.}
#'     \item{\code{D_mean}}{the ergodic average cross-section.}
#'     \item{\code{K_fine}, \code{bin_width}}{the quantisation grid and its
#'       spacing in log points.}
#'     \item{\code{mass_offgrid}}{probability mass whose \eqn{K'} fell outside
#'       \code{K_fine} and was clamped onto its boundary; must be 0 for the
#'       answer to mean anything.}
#'     \item{\code{iterations}, \code{converged}, \code{gap},
#'       \code{elapsed}}{iteration diagnostics. \code{gap} is the last
#'       relative change in the reported moments.}
#'     \item{\code{dist_gap}}{the last \code{max|dP|} over the aggregate-state
#'       distribution. This is NOT the convergence criterion and on a fine
#'       grid it need not go to zero: quantisation makes the bin assignment a
#'       step function of \eqn{K'}, so mass can settle into a small limit
#'       cycle across a bin edge. The cycle is of order the bin width and is
#'       bounded by the halving check; it does not move the moments (\code{gap}
#'       reaches double-precision zero in runs where \code{dist_gap} plateaus
#'       at ~2e-4).}
#'   }
#' @seealso \code{\link{hank_ks_aggregate_risk}}, \code{\link{hank_tfp_chain}}
#' @examples
#' \donttest{
#' inc    <- hank_income_rouwenhorst(rho = 0.95, sigma = 0.5, n = 3)
#' a_grid <- hank_asset_grid(amax = 50, n = 60, amin = 0)
#' ks     <- hank_ks_steady(a_grid, inc$Pi, inc$e, beta = 0.98, eis = 1,
#'                          alpha = 0.36, delta = 0.025)
#' fit <- hank_ks_aggregate_risk(ks, hank_tfp_chain(0.9, 0.01, 3L),
#'                               T_sim = 400L, burn_in = 100L, seed = 1L)
#' em  <- hank_ks_ergodic_mean(fit, n_fine = 51L)
#' c(simulated = fit$K_mean - fit$K_ss, exact = em$precautionary)
#' }
#' @export
hank_ks_ergodic_mean <- function(obj, n_fine = 101L, K_fine = NULL,
                                 tol = 1e-12, maxit = 5000L,
                                 verbose = FALSE) {
  if (!inherits(obj, "hank_ks_agg_risk"))
    stop("hank_ks_ergodic_mean(): 'obj' must be a hank_ks_aggregate_risk() ",
         "object (got class ", paste(class(obj), collapse = "/"), ").")
  t_start <- proc.time()[["elapsed"]]
  ks  <- obj$ks; blk <- ks$block
  Pi  <- blk$Pi; Pi_Z <- obj$Pi_Z; Z_grid <- obj$Z_grid
  alpha <- ks$alpha; delta <- ks$delta
  n_z <- length(Z_grid)

  if (is.null(K_fine)) {
    n_fine <- as.integer(n_fine)
    if (is.na(n_fine) || n_fine < 3L)
      stop("hank_ks_ergodic_mean(): 'n_fine' must be >= 3.")
    K_fine <- exp(seq(log(obj$K_grid[1L]),
                      log(obj$K_grid[length(obj$K_grid)]),
                      length.out = n_fine))
  }
  K_fine <- as.numeric(K_fine)
  n_fine <- length(K_fine)
  if (n_fine < 3L || any(diff(K_fine) <= 0) || any(K_fine <= 0))
    stop("hank_ks_ergodic_mean(): 'K_fine' must be a strictly increasing ",
         "vector of at least 3 positive values.")
  log_Kf <- log(K_fine)

  nodes <- .hank_agg_ergodic_nodes(obj, K_fine)
  n_ea <- nodes$n_ea; n_node <- nodes$n_node
  APOL <- nodes$APOL; CPOL <- nodes$CPOL

  ## --- initial condition: the deterministic cross-section, at the aggregate
  ## capital it clears, with Z drawn from the chain's stationary distribution.
  piZ <- if (n_z == 1L) 1 else .hank_stationary(Pi_Z)
  D0  <- blk$D; K0 <- blk$A
  w0  <- .hank_agg_K_weights(log_Kf, matrix(log(K0), 1L, 1L))
  j0  <- w0$i[1L, 1L]; wl0 <- min(max(w0$w[1L, 1L], 0), 1)
  P <- matrix(0, n_fine, n_z)
  for (z in seq_len(n_z)) {
    P[j0, z]      <- P[j0, z]      + piZ[z] * wl0
    P[j0 + 1L, z] <- P[j0 + 1L, z] + piZ[z] * (1 - wl0)
  }
  M <- matrix(0, n_ea, n_node)
  pv <- as.numeric(P)
  if (any(pv > 0)) M[, pv > 0] <- outer(D0, pv[pv > 0])
  S <- pv * K0; S2 <- pv * K0^2
  SL <- pv * log(K0); SL2 <- pv * log(K0)^2
  K_mean <- K0

  src_z  <- rep(seq_len(n_z), each = n_fine)
  z_base <- (src_z - 1L) * n_fine
  blk_j  <- seq_len(n_fine)
  ## Mix an (n_ea x n_node) unnormalized measure over Z with Pi_Z.
  mixZ <- function(G) {
    out <- matrix(0, n_ea, n_node)
    for (zp in seq_len(n_z)) {
      tmp <- NULL
      for (zz in seq_len(n_z)) {
        pr <- Pi_Z[zz, zp]
        if (pr == 0) next
        b <- pr * G[, (zz - 1L) * n_fine + blk_j, drop = FALSE]
        tmp <- if (is.null(tmp)) b else tmp + b
      }
      if (!is.null(tmp)) out[, (zp - 1L) * n_fine + blk_j] <- tmp
    }
    out
  }
  scat <- function(v, key) {
    out <- numeric(n_node)
    s <- rowsum(v, key, reorder = FALSE)
    out[as.integer(rownames(s))] <- s[, 1L]
    out
  }

  converged <- FALSE; gap <- Inf; dist_gap <- Inf; it <- 0L; mass_off <- 0
  mom <- c(K0, K0^2, log(K0), log(K0)^2)
  for (it in seq_len(maxit)) {
    pv <- as.numeric(P)
    ## K' at each node: <D, a(K_node, z)>. M is mass-weighted, so divide.
    num <- colSums(M * APOL)
    Kp <- ifelse(pv > 0, num / pmax(pv, .Machine$double.xmin), K_fine[j0])
    Kp[!is.finite(Kp) | Kp <= 0] <- K_fine[j0]
    Dp <- .hank_agg_push_many(nodes, Pi, M)

    wq  <- .hank_agg_K_weights(log_Kf, matrix(log(Kp), n_node, 1L))
    jlv <- wq$i[, 1L]; wraw <- wq$w[, 1L]
    wlv <- pmin(pmax(wraw, 0), 1)
    mass_off <- sum(pv[wraw < 0 | wraw > 1])

    ## Stage 1: scatter onto (source z, K bin).  Stage 2: mix over Z. Doing it
    ## in that order costs n_z^2 block operations instead of n_z scatters.
    key <- c(z_base + jlv, z_base + jlv + 1L)
    massv <- c(pv * wlv, pv * (1 - wlv))
    contrib <- cbind(Dp * rep(wlv, each = n_ea),
                     Dp * rep(1 - wlv, each = n_ea))
    g  <- rowsum(t(contrib), key, reorder = FALSE)
    G  <- matrix(0, n_ea, n_node)
    G[, as.integer(rownames(g))] <- t(g)

    Mn  <- mixZ(G)
    Pn   <- matrix(scat(massv, key), n_fine, n_z) %*% Pi_Z
    Kp2  <- c(Kp, Kp); lKp2 <- log(Kp2)
    Sn   <- matrix(scat(massv * Kp2, key), n_fine, n_z) %*% Pi_Z
    S2n  <- matrix(scat(massv * Kp2^2, key), n_fine, n_z) %*% Pi_Z
    SLn  <- matrix(scat(massv * lKp2, key), n_fine, n_z) %*% Pi_Z
    SL2n <- matrix(scat(massv * lKp2^2, key), n_fine, n_z) %*% Pi_Z

    ## CONVERGENCE IS DECLARED ON THE REPORTED MOMENTS, not on the joint
    ## distribution. Quantisation makes the bin assignment a STEP function of
    ## K', so on a fine grid the mass at individual nodes can settle into a
    ## small limit cycle (measured at n_fine = 201: max|dP| plateaus around
    ## 2e-4 forever) as an atom's K' sits astride a bin edge and its two
    ## neighbouring merged compositions alternate. That jitter is a
    ## quantisation artefact of order the bin width -- it is bounded by the
    ## halving check, not by iterating longer -- and it does NOT move the
    ## moments: the split is mean-preserving and each node carries the exact
    ## K' that landed on it, so |dE[K]|/E[K] reaches 0 (to double precision)
    ## by iteration ~200 in exactly the runs where max|dP| never does.
    ## Iterating to a distribution tolerance would therefore burn 20x the
    ## iterations and then fail anyway, on a criterion the answer does not
    ## depend on. max|dP| is still reported, as dist_gap.
    mom_new <- c(sum(Sn), sum(S2n), sum(SLn), sum(SL2n))
    gap <- max(abs(mom_new - mom) / pmax(abs(mom), 1))
    dist_gap <- max(abs(Pn - P))
    P <- Pn; M <- Mn; S <- Sn; S2 <- S2n; SL <- SLn; SL2 <- SL2n
    mom <- mom_new; K_mean <- mom_new[1L]
    if (verbose && (it %% 100L == 0L))
      message(sprintf(paste0("[hank_ks_ergodic_mean] iter %d  gap %.3e  ",
                             "dist_gap %.3e  E[K] %.10f"),
                      it, gap, dist_gap, K_mean))
    if (gap < tol) { converged <- TRUE; break }
  }
  if (!converged)
    warning("hank_ks_ergodic_mean(): the ergodic moments did not converge in ",
            maxit, " iterations (gap = ", format(gap), " vs tol = ",
            format(tol), ").", call. = FALSE)

  tot <- sum(P)
  K_mean  <- sum(S) / tot
  K_var   <- max(sum(S2) / tot - K_mean^2, 0)
  lK_mean <- sum(SL) / tot
  lK_var  <- max(sum(SL2) / tot - lK_mean^2, 0)
  C_mean  <- sum(colSums(M * CPOL)) / tot
  Knode <- rep(K_fine, times = n_z); Znode <- rep(Z_grid, each = n_fine)
  prc <- .hank_agg_prices(Knode, Znode, alpha, delta)
  Y_mean <- sum(as.numeric(P) * Znode * Knode^alpha) / tot
  r_mean <- sum(as.numeric(P) * prc$r) / tot

  list(K_mean = K_mean, K_sd = sqrt(K_var),
       logK_mean = lK_mean, logK_sd = sqrt(lK_var),
       K_ss = ks$K,
       precautionary = K_mean - ks$K,
       precautionary_pct = 100 * (K_mean / ks$K - 1),
       C_mean = C_mean, Y_mean = Y_mean, r_mean = r_mean,
       dist = P / tot, D_mean = rowSums(M) / tot,
       K_fine = K_fine, n_fine = n_fine,
       bin_width = diff(log_Kf)[1L],
       mass_offgrid = mass_off,
       iterations = it, converged = converged, gap = gap,
       dist_gap = dist_gap,
       elapsed = proc.time()[["elapsed"]] - t_start)
}
