## R/plot.R
## --------------------------------------------------------------------------
## S3 plot() methods for key dynhr classes.
##
## Provides default visualisations:
##   plot.dynhr_chains()   — trace + density for MCMC output
##   plot.dynhr_steady()   — steady-state convergence diagnostic
##   plot.DecisionRules()  — impulse response functions (requires IRFs)
## --------------------------------------------------------------------------


#' Plot MCMC chains (trace + density)
#'
#' Generates a combined trace-plot and density-plot for each parameter in
#' a \code{dynhr_chains} object. Uses base R graphics by default; if
#' \code{ggplot2} is available, produces a faceted ggplot instead.
#'
#' @param x       A \code{dynhr_chains} object.
#' @param n_cols  Number of facet columns (ggplot2 mode) or columns for the
#'   base-R layout matrix.
#' @param warmup  Integer: number of warmup draws to shade (if known).
#' @param ...     Additional arguments passed to \code{plot()} or
#'   \code{ggplot2::geom_line()}.
#'
#' @return \code{x}, invisibly.
#' @export
plot.dynhr_chains <- function(x, n_cols = 3L, warmup = NULL, ...) {
  ch <- x$chain
  n_par <- ncol(ch)
  n_draws <- nrow(ch)
  pnames <- colnames(ch)

  if (requireNamespace("ggplot2", quietly = TRUE)) {
    .plot_chains_ggplot(ch, pnames, n_par, n_draws, n_cols, warmup)
  } else {
    .plot_chains_base(ch, pnames, n_par, n_draws, n_cols, warmup)
  }
  invisible(x)
}

.plot_chains_base <- function(ch, pnames, n_par, n_draws, n_cols, warmup) {
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))

  n_rows <- ceiling(n_par / n_cols)
  par(mfrow = c(n_rows, n_cols), mar = c(3, 3, 2, 1), mgp = c(1.5, 0.5, 0))

  for (i in seq_len(n_par)) {
    plot(ch[, i], type = "l", col = "#2166AC", main = pnames[i],
         xlab = "Draw", ylab = "Value", cex.main = 0.9)
    if (!is.null(warmup) && warmup > 0) {
      abline(v = warmup, col = "#B2182B", lty = 2, lwd = 0.8)
    }
    ## Overlay smoothed density
    dens <- density(ch[, i], adjust = 1.5)
    lines(dens$x, dens$y * diff(range(ch[, i])) / max(dens$y) +
            min(ch[, i]), col = "#B2182B", lwd = 0.8)
  }
}

.plot_chains_ggplot <- function(ch, pnames, n_par, n_draws, n_cols, warmup) {
  gg <- .ensure_ggplot2()
  long <- data.frame(
    draw = rep(seq_len(n_draws), n_par),
    value = as.numeric(ch),
    param = factor(rep(pnames, each = n_draws), levels = pnames)
  )
  p <- gg$ggplot(long, gg$aes(x = .data$draw, y = .data$value)) +
    gg$geom_line(colour = "#2166AC", linewidth = 0.3, alpha = 0.7) +
    gg$facet_wrap(~ param, ncol = n_cols, scales = "free_y") +
    gg$labs(x = "Draw", y = "Value", title = "Trace plots") +
    theme_dynhr()
  if (!is.null(warmup) && warmup > 0) {
    p <- p + gg$geom_vline(xintercept = warmup, colour = "#B2182B",
                           linetype = "dashed", linewidth = 0.4)
  }
  print(p)
}


#' Plot steady-state convergence diagnostic
#'
#' Shows the residual norm trajectory during the Newton solve.
#'
#' @param x       A \code{dynhr_steady} object with an \code{$iter_trace}
#'   component (optional), or just reports convergence status.
#' @param ...     Ignored.
#' @return \code{x}, invisibly.
#' @export
plot.dynhr_steady <- function(x, ...) {
  if (!is.null(x$iter_trace) && length(x$iter_trace) > 0) {
    plot(x$iter_trace, type = "b", col = "#2166AC", pch = 16, cex = 0.6,
         main = "Steady-state Newton convergence",
         xlab = "Iteration", ylab = "Max |residual|",
         log = "y")
    abline(h = 1e-10, col = "#B2182B", lty = 2, lwd = 0.8)
    legend("topright",
           legend = c("Residual norm", "Tolerance (1e-10)"),
           col = c("#2166AC", "#B2182B"), lty = c(1, 2), lwd = c(1, 0.8),
           cex = 0.7)
  } else {
    status <- if (isTRUE(x$converged)) "Converged" else "Did not converge"
    plot(0, type = "n", axes = FALSE, xlab = "", ylab = "",
         main = sprintf("Steady state: %s", status))
    text(0, 0, sprintf("Max |residual| = %s\nIterations: %d",
                       format(x$max_residual, digits = 3), x$iterations),
         cex = 1.2, font = 2)
  }
  invisible(x)
}


#' Plot decision rules (IRF overview)
#'
#' Displays impulse response functions generated by \code{compute_irfs()}
#' for the first few shocks. The model must have been solved and IRFs
#' computed separately; this method provides a quick visual summary.
#'
#' If the \code{DecisionRules} object has an \code{$irfs} element (populated
#' by \code{stoch_simul()} or \code{compute_irfs()}), it is used directly.
#' Otherwise, a message prompts the user to run \code{compute_irfs()}.
#'
#' @param x       A \code{DecisionRules} object.
#' @param n_shocks Number of shocks to show (default 4).
#' @param n_cols   Number of facet columns (default 3).
#' @param ...      Additional arguments (ignored).
#' @return \code{x}, invisibly.
#' @export
plot.DecisionRules <- function(x, n_shocks = 4L, n_cols = 3L, ...) {
  irfs <- x$irfs
  if (is.null(irfs)) {
    message("No IRFs stored in DecisionRules object. ",
            "Run compute_irfs() or stoch_simul() first.")
    return(invisible(x))
  }

  shock_names <- names(irfs)
  n_show <- min(length(shock_names), n_shocks)

  if (requireNamespace("ggplot2", quietly = TRUE)) {
    .plot_irfs_ggplot(irfs, shock_names, n_show, n_cols)
  } else {
    .plot_irfs_base(irfs, shock_names, n_show)
  }
  invisible(x)
}

.plot_irfs_base <- function(irfs, shock_names, n_show) {
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))

  for (s in seq_len(n_show)) {
    sn <- shock_names[s]
    mat <- irfs[[sn]]
    n_periods <- nrow(mat)
    endo_names <- colnames(mat)

    par(mfrow = c(ceiling(ncol(mat) / 3), 3),
        mar = c(2, 2.5, 2, 0.5), mgp = c(1.5, 0.5, 0))
    for (v in endo_names) {
      plot(mat[, v], type = "l", col = "#2166AC", lwd = 1.2,
           main = v, xlab = "", ylab = "")
      abline(h = 0, col = "grey80", lty = 2)
    }
    mtext(sprintf("Shock: %s", sn), outer = TRUE, side = 3,
          line = -1.5, cex = 1.1, font = 2)
  }
}

.plot_irfs_ggplot <- function(irfs, shock_names, n_show, n_cols) {
  gg <- .ensure_ggplot2()
  long_list <- vector("list", length(shock_names))
  names(long_list) <- shock_names

  for (s in seq_len(n_show)) {
    sn <- shock_names[s]
    mat <- irfs[[sn]]
    n_periods <- nrow(mat)
    endo_names <- colnames(mat)
    long_list[[s]] <- data.frame(
      shock = sn,
      horizon = rep(seq_len(n_periods) - 1L, ncol(mat)),
      variable = rep(endo_names, each = n_periods),
      value = as.numeric(mat),
      stringsAsFactors = FALSE
    )
  }
  long <- do.call(rbind, long_list[seq_len(n_show)])

  p <- gg$ggplot(long, gg$aes(x = .data$horizon, y = .data$value)) +
    gg$geom_line(colour = "#2166AC", linewidth = 0.6) +
    gg$geom_hline(yintercept = 0, colour = "grey60", linetype = "dashed",
                  linewidth = 0.3) +
    gg$facet_grid(variable ~ shock, scales = "free_y") +
    gg$labs(x = "Horizon", y = NULL,
            title = "Impulse Response Functions") +
    theme_dynhr()
  print(p)
}
