# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fdb_compose_folded_cpp <- function(Nc, n_out, shapes, Glist, Hlist) {
    .Call(`_dynhr_fdb_compose_folded_cpp`, Nc, n_out, shapes, Glist, Hlist)
}

eval_jac_tape_cpp <- function(dy, params, ss, op, ia, da, expr_len, out_row, out_col, n_eq, total_cols) {
    .Call(`_dynhr_eval_jac_tape_cpp`, dy, params, ss, op, ia, da, expr_len, out_row, out_col, n_eq, total_cols)
}

eval_triplet_tape_cpp <- function(dy, params, ss, op, ia, da, expr_len) {
    .Call(`_dynhr_eval_triplet_tape_cpp`, dy, params, ss, op, ia, da, expr_len)
}

kf_adjoint_cpp <- function(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat, return_bars = FALSE) {
    .Call(`_dynhr_kf_adjoint_cpp`, Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat, return_bars)
}

kf_adjoint_uni_cpp <- function(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, P0_in, p0_supplied) {
    .Call(`_dynhr_kf_adjoint_uni_cpp`, Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, P0_in, p0_supplied)
}

kalman_ss_loop_cpp <- function(Y_minus_d, ZZ, TT, K_ss, F_inv_ss, ll_ss_const, s, start_t, end_t, return_filtered) {
    .Call(`_dynhr_kalman_ss_loop_cpp`, Y_minus_d, ZZ, TT, K_ss, F_inv_ss, ll_ss_const, s, start_t, end_t, return_filtered)
}

kalman_standard_loop_cpp <- function(Y_minus_d, ZZ, TT, RR, DD, HH_full, Sigma_e, SS, P, ll_const, ss_tol, ll_min, return_filtered) {
    .Call(`_dynhr_kalman_standard_loop_cpp`, Y_minus_d, ZZ, TT, RR, DD, HH_full, Sigma_e, SS, P, ll_const, ss_tol, ll_min, return_filtered)
}

kalman_univariate_loop_cpp <- function(Y_minus_d, Zb, Tb, QQb, a, P_star, P_inf, me_variance, kalman_tol, diffuse_tol, conv_tol, max_diffuse, ll_min, return_filtered, n_state, ss_lock) {
    .Call(`_dynhr_kalman_univariate_loop_cpp`, Y_minus_d, Zb, Tb, QQb, a, P_star, P_inf, me_variance, kalman_tol, diffuse_tol, conv_tol, max_diffuse, ll_min, return_filtered, n_state, ss_lock)
}

kf_adjoint_diffuse_cpp <- function(Y, TT, RR, ZZ, DD, d_obs, Sigma_e, me_variance, ur_tol) {
    .Call(`_dynhr_kf_adjoint_diffuse_cpp`, Y, TT, RR, ZZ, DD, d_obs, Sigma_e, me_variance, ur_tol)
}

kf_loglik_dG_cpp <- function(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT, dRR, dZZ, dDD, dd_dir, dSig, me_variance, ll_min) {
    .Call(`_dynhr_kf_loglik_dG_cpp`, Y, TT, RR, ZZ, DD, d, Sigma_e, dTT, dRR, dZZ, dDD, dd_dir, dSig, me_variance, ll_min)
}

kf_score_sigma_cpp <- function(Yd, TT, RR, ZZ, DD, Sigma_e, HH, SS, me_diag, P0, dSigma, dH, dS, dP0, ss_tol = 1e-11) {
    .Call(`_dynhr_kf_score_sigma_cpp`, Yd, TT, RR, ZZ, DD, Sigma_e, HH, SS, me_diag, P0, dSigma, dH, dS, dP0, ss_tol)
}

kf_tangent_cpp <- function(Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat) {
    .Call(`_dynhr_kf_tangent_cpp`, Y, TT, RR, ZZ, DD, d, Sigma_e, dTT_cube, dRR_cube, dZZ_cube, dDD_cube, dd_mat, dSigma_cube, me_variance, ll_min, shock_scale_mat, me_extra_mat)
}

mcp_sparse_solve_cpp <- function(i_idx, j_idx, x_vals, rhs, n_dim) {
    .Call(`_dynhr_mcp_sparse_solve_cpp`, i_idx, j_idx, x_vals, rhs, n_dim)
}

ordered_qz_cpp <- function(E, D, critmod = 1.0000010) {
    .Call(`_dynhr_ordered_qz_cpp`, E, D, critmod)
}

qr_static_transform_cpp <- function(f_static, f_minus_r, f_zero_r, f_plus_r, f_exo_r) {
    .Call(`_dynhr_qr_static_transform_cpp`, f_static, f_minus_r, f_zero_r, f_plus_r, f_exo_r)
}

tpf_propagate_particles <- function(particles, shocks, hx, hu, hxx, hxu, huu, hss) {
    .Call(`_dynhr_tpf_propagate_particles`, particles, shocks, hx, hu, hxx, hxu, huu, hss)
}

tpf_run_period_cpp <- function(particles, y_t, L_e, hx, hu, hxx, hxu, huu, hss, ZZ, DD, d_obs, ghss_obs, me_variance, ess_target, n_mh, mh_scale, max_stages, U_normals = NULL, U_resample = NULL, U_mid = NULL, U_mutation = NULL) {
    .Call(`_dynhr_tpf_run_period_cpp`, particles, y_t, L_e, hx, hu, hxx, hxu, huu, hss, ZZ, DD, d_obs, ghss_obs, me_variance, ess_target, n_mh, mh_scale, max_stages, U_normals, U_resample, U_mid, U_mutation)
}

tpf_log_weights <- function(particles, y_t, ZZ, DD, shocks, d_obs, ghss_obs, me_variance, phi) {
    .Call(`_dynhr_tpf_log_weights`, particles, y_t, ZZ, DD, shocks, d_obs, ghss_obs, me_variance, phi)
}

