## R/shock-decomposition-shapley.R
## --------------------------------------------------------------------------
## Historical (shock) decomposition of a pruned order-1/2/3 path, with a
## Shapley allocation of the cross-shock interaction terms.
##
## Given a realised shock path eps_1..eps_T (e.g. smoothed or inverted
## shocks) and a starting state, the coalition value is
##
##   V_t(S) = y_t along the pruned path simulated from the SAME initial state
##            with every shock outside S set to zero in every period,
##
## so V_t(N) is the full path and V_t(empty) the shock-free path (initial
## condition plus, at order >= 2, the deterministic risk-correction drift of
## ghss / ghs3).  At pruned order k, y_t is a polynomial of degree <= k in the
## realised shocks, so V_t(S) is a multilinear polynomial of degree <= k in
## the membership indicators (x_i^m = x_i on {0,1}) and its exact Shapley
## value needs V only on the coalitions of size <= k (plus V(N) for the
## closure check): .shapley_poly_weights() in R/vardec-nonlinear.R.
##
## Relation to MacroModelling.jl v0.2.0 (get_shock_decomposition(...,
## marginal_contribution = true); docs/src/shapley_decompositions.md):
##   * SAME coalition value (the fitted variable at t with the shocks outside
##     S zeroed, from the same initial state), same output layout (one column
##     per shock plus the V(empty) "initial" column, which it calls
##     :Initial_values), same efficiency identity.
##   * DIFFERENT evaluation: MacroModelling.jl integrates the Aumann-Shapley
##     path integral along the diagonal of the cube with forward-mode tangents
##     of the SCALED-shock recursion.  At order 3 that is not the Shapley value
##     of the binary game: a term c * eps_i^2 * eps_j is split 2c/3 : c/3
##     there (documented, "O(1e-8)" on SW07), and c/2 : c/2 here, which is the
##     exact Shapley value of V.  At orders 1 and 2 the two agree.
##   * shocks: MacroModelling.jl takes them from its inversion filter; dynhr
##     has no order-2/3 inversion filter, so the shock path is an input (from
##     any filter / smoother, or a scenario).
## --------------------------------------------------------------------------


#' Historical decomposition of a pruned order-2/3 path with Shapley allocation
#'
#' Decomposes the path of every endogenous variable, generated by a pruned
#' order-1, -2 or -3 perturbation solution from a given shock path and
#' initial state, into one contribution per shock plus an initial-condition
#' component.  Beyond first order the shocks interact (\eqn{e_1 e_2},
#' \eqn{e_i^2}, state-shock products), so the path is not additive over
#' shocks; the default \code{method = "shapley"} allocates the interaction
#' with the Shapley value, so the components add up to the path exactly.
#'
#' @details
#' \strong{Coalition value.}  For a set \eqn{S} of shocks,
#' \eqn{V_t(S)} is the value of each variable at period \eqn{t} along the
#' pruned trajectory started from \code{init_state} with every shock outside
#' \eqn{S} set to zero in every period (the realised values of the shocks in
#' \eqn{S} are kept).  \eqn{V_t(N)} is the full path (returned as
#' \code{total}); \eqn{V_t(\emptyset)} is the shock-free path -- the
#' propagation of the initial state plus, at order \eqn{\ge 2}, the
#' deterministic drift towards the risky steady state from the
#' \code{ghss}/\code{ghs3} terms -- and is the \code{"initial"} component.
#' Shocks are the structural shocks themselves (no orthogonalisation), as in
#' \code{\link{historical_decomposition}}.
#'
#' \strong{Shapley allocation.}  The per-period, per-variable Shapley value
#' \eqn{\phi_{i,t} = \sum_{S \subseteq N\setminus\{i\}}
#' \frac{|S|!(n-|S|-1)!}{n!}(V_t(S\cup\{i\}) - V_t(S))} satisfies
#' \eqn{\sum_i \phi_{i,t} + V_t(\emptyset) = V_t(N)} (efficiency).  At pruned
#' order \eqn{k} each variable is a polynomial of degree \eqn{\le k} in the
#' realised shocks, so \eqn{V_t} is a multilinear polynomial of degree
#' \eqn{\le k} in the shock-membership indicators and its exact Shapley value
#' needs \eqn{V} only on the \eqn{\sum_{j \le k}\binom{n}{j}} coalitions of
#' size \eqn{\le k} (\code{shapley_algorithm = "polynomial"}, the default; see
#' \code{\link{variance_decomposition_nonlinear}} for the formula).  A term
#' \eqn{c\,\varepsilon_{i}\varepsilon_{j}} is split equally between shocks
#' \eqn{i} and \eqn{j}; \eqn{c\,\varepsilon_i^2} goes to shock \eqn{i}.  At
#' first order \eqn{V} is additive and the result equals
#' \code{\link{historical_decomposition}} with the same shocks and
#' \code{s0}.
#'
#' \strong{Relation to MacroModelling.jl} (\code{get_shock_decomposition(...,
#' marginal_contribution = true)}): same coalition value, same layout (its
#' \code{:Initial_values} is \code{"initial"} here).  It evaluates the Shapley
#' value by an Aumann-Shapley path integral of the scaled-shock recursion,
#' which at order 3 splits a term \eqn{c\,\varepsilon_i^2\varepsilon_j} as
#' \eqn{2c/3 : c/3} between \eqn{i} and \eqn{j}; here it is \eqn{c/2 : c/2},
#' the exact Shapley value of \eqn{V}.  Orders 1 and 2 agree.  dynhr has no
#' order-2/3 inversion filter, so the shock path is an argument.
#'
#' \strong{Sequential method.}  \code{method = "sequential"} reports each
#' shock on its own, \eqn{V_t(\{i\}) - V_t(\emptyset)}, plus an
#' \code{"interaction"} component \eqn{V_t(N) - V_t(\emptyset) - \sum_i
#' (V_t(\{i\}) - V_t(\emptyset))} (MacroModelling.jl's default table with its
#' \code{:Nonlinearities} column).
#'
#' @param dr A \code{DecisionRules} object from
#'   \code{\link{solve_perturbation}} (order 1, 2 or 3; higher-order rules are
#'   used up to their order-3 terms).
#' @param shocks \code{T x n_exo} matrix of realised structural shocks (rows
#'   are periods), e.g. smoothed shocks.  Columns are matched to
#'   \code{dr$exo_names} by name when named, else taken in that order.
#' @param init_state Initial state (the state entering period 1), in
#'   deviations from the deterministic steady state.  \code{NULL}: the
#'   steady state.  A numeric vector over the state variables
#'   \code{dr$endo_names[dr$state_idx]} (named, or unnamed in that order) is
#'   loaded into the first-order pruned component, as in
#'   \code{\link{simulate_model_order2}}; a list with elements \code{x1},
#'   \code{x2}, \code{x3} sets the pruned components separately.
#' @param order Pruning order: 1, 2 or 3, at most the order of \code{dr}.
#'   Default: the order of \code{dr}, capped at 3.
#' @param method \code{"shapley"} (default) or \code{"sequential"}.
#' @param shapley_algorithm \code{"polynomial"} (default; coalitions of size
#'   \eqn{\le} \code{order} only) or \code{"exact"} (all \eqn{2^n}
#'   coalitions; at most 20 shocks).  Both return the exact Shapley value.
#' @param tol Relative tolerance for the adding-up check (default
#'   \code{1e-8}).
#'
#' @return A list of class
#'   \code{c("dynhr_shock_decomposition_nonlinear", "dynhr_shock_decomposition")}
#'   (so \code{plot()} works) with
#'   \describe{
#'     \item{contributions}{Named list of \code{T x n_endo} matrices, one per
#'       shock (plus \code{"interaction"} for \code{method = "sequential"}),
#'       then \code{"initial"} (\eqn{V_t(\emptyset)}).}
#'     \item{total}{\code{T x n_endo}: the full path \eqn{V_t(N)}, deviations
#'       from the deterministic steady state (the path
#'       \code{\link{simulate_model_order2}} / \code{\link{simulate_model_order3}}
#'       produce from the same shocks and state).}
#'     \item{initial}{Same as \code{contributions$initial}.}
#'     \item{adding_up_residual, adding_up_relative, adding_up_ok,
#'       adding_up_tol}{Largest absolute gap between the sum of the components
#'       and \code{total}, the same relative to \code{max(abs(total))}, and
#'       whether that is within \code{tol}.  Efficiency is exact for
#'       \code{"exact"} and \code{"sequential"}; for \code{"polynomial"} it is
#'       CHECKED (a gap means the degree bound failed) and a warning of class
#'       \code{dynhr_shapley_closure} is raised when it exceeds \code{tol}.}
#'     \item{order, method, algorithm, n_evaluations}{What was computed;
#'       \code{n_evaluations} is the number of coalition paths simulated.}
#'     \item{init_state}{The pruned initial components \code{x1, x2, x3}.}
#'     \item{components, orientation, timing, has_nonlinear_column,
#'       has_residual_column}{As in \code{\link{historical_decomposition}}.}
#'   }
#'
#' @references
#'   Shapley, L. S. (1953). A value for n-person games. In \emph{Contributions
#'     to the Theory of Games II}, 307-317.
#'   Owen, G. (1972). Multilinear extensions of games. \emph{Management
#'     Science}, 18(5), 64-79.
#'   Kockerols, T. MacroModelling.jl v0.2.0 (2026), "Shapley decompositions
#'     for pruned higher-order perturbation".
#'
#' @seealso \code{\link{historical_decomposition}} (linear, from a Kalman
#'   smoother), \code{\link{variance_decomposition_nonlinear}}.
#' @export
historical_decomposition_nonlinear <- function(dr, shocks, init_state = NULL,
                                               order = NULL,
                                               method = c("shapley",
                                                          "sequential"),
                                               shapley_algorithm = c("polynomial",
                                                                     "exact"),
                                               tol = 1e-8) {
  method <- match.arg(method)
  shapley_algorithm <- match.arg(shapley_algorithm)
  if (!inherits(dr, "DecisionRules"))
    .dynhr_abort("historical_decomposition_nonlinear: `dr` must be a ",
                 "DecisionRules object from solve_perturbation().",
                 class = "dynhr_input_error")
  dr_order <- if (inherits(dr, "DecisionRules3")) 3L
              else if (inherits(dr, "DecisionRules2")) 2L else 1L
  if (is.null(order)) order <- dr_order
  if (length(order) != 1L || !is.numeric(order) || !(order %in% 1:3))
    .dynhr_abort("historical_decomposition_nonlinear: `order` must be 1, 2 or 3.",
                 class = "dynhr_input_error")
  order <- as.integer(order)
  if (order > dr_order)
    .dynhr_abort(sprintf(paste0(
      "historical_decomposition_nonlinear: order = %d requested but `dr` is ",
      "an order-%d solution; re-solve with solve_perturbation(order = %d)."),
      order, dr_order, order), class = "dynhr_input_error")

  endo <- dr$endo_names
  exo  <- dr$exo_names
  n    <- length(exo)
  if (n == 0L)
    .dynhr_abort("historical_decomposition_nonlinear: the model has no shocks.",
                 class = "dynhr_input_error")
  shocks <- .hdnl_shocks(shocks, exo)
  x0 <- .hdnl_init(init_state, endo[dr$state_idx])

  ## Coalitions (columns of `active`) whose paths are simulated.
  if (method == "sequential") {
    algorithm <- "standalone"
    active <- cbind(FALSE, diag(n) > 0, TRUE)
  } else if (shapley_algorithm == "exact") {
    if (n > 20L)
      .dynhr_abort(sprintf(paste0(
        "historical_decomposition_nonlinear: shapley_algorithm = \"exact\" ",
        "enumerates 2^n coalitions; n = %d shocks is too many. Use ",
        "\"polynomial\" (also exact)."), n), class = "dynhr_input_error")
    algorithm <- "exact"
    bits <- 2^(seq_len(n) - 1L)
    active <- vapply(0:(2^n - 1), function(mk) bitwAnd(mk, bits) > 0,
                     logical(n))
    active <- matrix(active, n)
  } else {
    algorithm <- "polynomial"
    co <- .shapley_small_coalitions(n, min(order, n))
    active <- cbind(FALSE, co$active)
    if (!any(colSums(active) == n)) active <- cbind(active, TRUE)
  }

  paths <- .hdnl_paths(dr, order, shocks, x0, active)   # T x n_endo x M
  TT <- nrow(shocks)
  sizes <- colSums(active)
  flat <- matrix(paths, TT * length(endo), ncol(active))
  v0   <- flat[, which(sizes == 0L)[1L]]
  vN   <- flat[, which(sizes == n)[1L]]
  dflat <- flat - v0

  if (method == "sequential") {
    cols <- dflat[, 1L + seq_len(n), drop = FALSE]
    cols <- cbind(cols, (vN - v0) - rowSums(cols))
    col_names <- c(exo, "interaction")
  } else {
    W <- matrix(0, ncol(active), n)
    if (algorithm == "exact") {
      ## phi_i = sum_S w(|S|) (V(S u i) - V(S)): a coalition U enters with
      ## +w(|U| - 1) when i is in U and -w(|U|) when it is not.
      w <- exp(lgamma(0:(n - 1L) + 1) + lgamma(n - 0:(n - 1L)) - lgamma(n + 1))
      for (k in seq_len(ncol(active))) {
        u <- sizes[k]
        W[k, ] <- ifelse(active[, k], if (u > 0L) w[u] else 0,
                         if (u < n) -w[u + 1L] else 0)
      }
    } else {
      pw <- .shapley_poly_weights(n, min(order, n))
      for (k in seq_len(ncol(active))) {
        u <- sizes[k]
        if (u == 0L || u > length(pw$w_in)) next     # V(empty); the V(N) check
        W[k, ] <- ifelse(active[, k], pw$w_in[u], pw$w_out[u])
      }
    }
    cols <- dflat %*% W
    col_names <- exo
  }

  contributions <- lapply(seq_along(col_names), function(j) {
    M <- matrix(cols[, j], TT, length(endo))
    colnames(M) <- endo
    M
  })
  names(contributions) <- col_names
  initial <- matrix(v0, TT, length(endo), dimnames = list(NULL, endo))
  total   <- matrix(vN, TT, length(endo), dimnames = list(NULL, endo))
  contributions$initial <- initial

  gap   <- max(abs(Reduce(`+`, contributions) - total))
  scale <- max(abs(total))
  rel   <- if (scale > 0) gap / scale else gap
  ok    <- rel <= tol
  if (!ok)
    .dynhr_warn(sprintf(paste0(
      "historical_decomposition_nonlinear: the components miss the path by ",
      "%.3g (relative); the degree-%d bound on the coalition value does not ",
      "hold to round-off. Use shapley_algorithm = \"exact\"."), rel, order),
      class = "dynhr_shapley_closure")

  out <- list(
    contributions = contributions, total = total, initial = initial,
    components = names(contributions), orientation = "time_endo",
    order = order, method = method, algorithm = algorithm,
    n_evaluations = ncol(active), init_state = x0,
    adding_up_residual = gap, adding_up_relative = rel, adding_up_ok = ok,
    adding_up_tol = tol,
    n_components = length(contributions),
    has_nonlinear_column = method == "sequential",
    has_residual_column = FALSE,
    timing = paste(
      "contribution row t is the model's variables DATED t, computed from the",
      "state entering period t and that period's shocks; row 1 loads",
      "`init_state`. Values are deviations from the deterministic steady",
      "state."))
  class(out) <- c("dynhr_shock_decomposition_nonlinear",
                  "dynhr_shock_decomposition")
  out
}


## ---- input normalisation ------------------------------------------------------

## T x n_exo numeric shock matrix in `exo` order (name-matched when named).
## @noRd
.hdnl_shocks <- function(shocks, exo) {
  if (is.data.frame(shocks)) shocks <- as.matrix(shocks)
  if (is.numeric(shocks) && !is.matrix(shocks) && length(exo) == 1L)
    shocks <- matrix(shocks, ncol = 1L, dimnames = list(NULL, exo))
  if (!is.matrix(shocks) || !is.numeric(shocks) || nrow(shocks) == 0L)
    .dynhr_abort("historical_decomposition_nonlinear: `shocks` must be a ",
                 "numeric T x n_exo matrix (rows are periods).",
                 class = "dynhr_input_error")
  if (ncol(shocks) != length(exo))
    .dynhr_abort(sprintf(paste0(
      "historical_decomposition_nonlinear: `shocks` has %d columns, the ",
      "model has %d shocks (%s)."), ncol(shocks), length(exo),
      paste(exo, collapse = ", ")), class = "dynhr_input_error")
  nm <- colnames(shocks)
  if (!is.null(nm)) {
    if (!setequal(nm, exo))
      .dynhr_abort(sprintf(paste0(
        "historical_decomposition_nonlinear: `shocks` column names do not ",
        "match the model's shocks.\n  supplied: %s\n  expected: %s"),
        paste(nm, collapse = ", "), paste(exo, collapse = ", ")),
        class = "dynhr_input_error")
    shocks <- shocks[, exo, drop = FALSE]
  }
  if (anyNA(shocks) || any(!is.finite(shocks)))
    .dynhr_abort("historical_decomposition_nonlinear: `shocks` contains ",
                 "NA or non-finite values.", class = "dynhr_input_error")
  colnames(shocks) <- exo
  shocks
}

## Pruned initial components list(x1, x2, x3), each over `st_names`.
## @noRd
.hdnl_init <- function(init_state, st_names) {
  n_s <- length(st_names)
  one <- function(v, what) {
    if (is.null(v)) return(stats::setNames(numeric(n_s), st_names))
    if (!is.numeric(v) || anyNA(v) || any(!is.finite(v)))
      .dynhr_abort(sprintf(paste0(
        "historical_decomposition_nonlinear: `%s` must be a finite numeric ",
        "vector over the state variables."), what), class = "dynhr_input_error")
    if (length(v) != n_s)
      .dynhr_abort(sprintf(paste0(
        "historical_decomposition_nonlinear: `%s` has length %d, the model ",
        "has %d state variables (%s)."), what, length(v), n_s,
        paste(st_names, collapse = ", ")), class = "dynhr_input_error")
    nm <- names(v)
    if (!is.null(nm)) {
      if (!setequal(nm, st_names))
        .dynhr_abort(sprintf(paste0(
          "historical_decomposition_nonlinear: `%s` names do not match the ",
          "state variables.\n  supplied: %s\n  expected: %s"), what,
          paste(nm, collapse = ", "), paste(st_names, collapse = ", ")),
          class = "dynhr_input_error")
      v <- v[st_names]
    }
    stats::setNames(as.numeric(v), st_names)
  }
  if (is.list(init_state)) {
    bad <- setdiff(names(init_state), c("x1", "x2", "x3"))
    if (is.null(names(init_state)) || length(bad) > 0L)
      .dynhr_abort("historical_decomposition_nonlinear: a list `init_state` ",
                   "must have elements named x1, x2 and/or x3.",
                   class = "dynhr_input_error")
    return(list(x1 = one(init_state$x1, "init_state$x1"),
                x2 = one(init_state$x2, "init_state$x2"),
                x3 = one(init_state$x3, "init_state$x3")))
  }
  list(x1 = one(init_state, "init_state"), x2 = one(NULL, ""),
       x3 = one(NULL, ""))
}


## ---- vectorised pruned paths ----------------------------------------------------

## Column-wise Kronecker (Khatri-Rao) product: column c is A[, c] %x% B[, c].
## @noRd
.hdnl_kr <- function(A, B) {
  A[rep(seq_len(nrow(A)), each = nrow(B)), , drop = FALSE] *
    B[rep(seq_len(nrow(B)), times = nrow(A)), , drop = FALSE]
}

## Pruned order-`order` paths for M shock coalitions at once (the columns of
## `active`, n_exo x M logical).  Same recursion and Kronecker conventions as
## simulate_model_order2() / simulate_model_order3() (pruning = TRUE); each
## pruned state layer is the state rows of the matching output layer,
## x_k = y_k[state_idx].  Returns an array [T, n_endo, M].
## @noRd
.hdnl_paths <- function(dr, order, shocks, x0, active) {
  TT   <- nrow(shocks)
  n_e  <- ncol(shocks)
  M    <- ncol(active)
  sidx <- dr$state_idx
  n_s  <- length(sidx)
  n_endo <- nrow(dr$ghx)
  ghx <- dr$ghx; ghu <- dr$ghu
  if (order >= 2L) {
    ghxx <- dr$ghxx; ghxu <- dr$ghxu; ghuu <- dr$ghuu
    ghss <- as.numeric(dr$ghss)
  }
  if (order >= 3L) {
    ghxxx <- dr$ghxxx; ghxxu <- dr$ghxxu; ghxuu <- dr$ghxuu; ghuuu <- dr$ghuuu
    ghxss <- dr$ghxss; ghuss <- dr$ghuss
    ghs3  <- if (is.null(dr$ghs3)) NULL else as.numeric(dr$ghs3)
  }
  ## Widest Kronecker block per column; chunk the coalitions to bound memory.
  width <- switch(order, max(n_e, n_s, 1),
                  max(n_e^2, n_s^2, n_e * n_s, 1),
                  max(n_e^3, n_s^3, n_e * n_s^2, n_e^2 * n_s, 1))
  chunk <- max(1L, as.integer(floor(4e6 / width)))
  out <- array(0, c(TT, n_endo, M))
  for (c0 in seq(1L, M, by = chunk)) {
    cols <- c0:min(M, c0 + chunk - 1L)
    m    <- length(cols)
    mask <- active[, cols, drop = FALSE] * 1
    X1 <- matrix(x0$x1, n_s, m)
    X2 <- matrix(x0$x2, n_s, m)
    X3 <- matrix(x0$x3, n_s, m)
    for (t in seq_len(TT)) {
      E  <- mask * shocks[t, ]                      # n_e x m
      Y1 <- ghx %*% X1 + ghu %*% E
      Y  <- Y1
      if (order >= 2L) {
        XX <- .hdnl_kr(X1, X1)
        EX <- .hdnl_kr(E, X1)
        EE <- .hdnl_kr(E, E)
        Y2 <- ghx %*% X2 + 0.5 * (ghxx %*% XX) + ghxu %*% EX +
          0.5 * (ghuu %*% EE) + 0.5 * ghss
        Y <- Y + Y2
      }
      if (order >= 3L) {
        Y3 <- ghx %*% X3 + ghxx %*% .hdnl_kr(X1, X2) +
          ghxu %*% .hdnl_kr(E, X2) +
          0.5 * (ghxxu %*% .hdnl_kr(E, XX)) +
          0.5 * (ghxuu %*% .hdnl_kr(EE, X1)) +
          (1 / 6) * (ghxxx %*% .hdnl_kr(XX, X1)) +
          (1 / 6) * (ghuuu %*% .hdnl_kr(EE, E))
        if (!is.null(ghxss)) Y3 <- Y3 + 0.5 * (ghxss %*% X1)
        if (!is.null(ghuss)) Y3 <- Y3 + 0.5 * (ghuss %*% E)
        if (!is.null(ghs3))  Y3 <- Y3 + ghs3 / 6
        Y <- Y + Y3
        X3 <- Y3[sidx, , drop = FALSE]
      }
      if (order >= 2L) X2 <- Y2[sidx, , drop = FALSE]
      X1 <- Y1[sidx, , drop = FALSE]
      out[t, , cols] <- Y
    }
  }
  out
}
